"""Ce qui peut apparaître, par saison, par zone et par condition météo.

Deux sources : le relevé de Ryzom Armory pour le couple saison × zone, et
la fourchette d'humidité de chaque gisement, relevée au tracker d'atys.us,
pour la condition. Le jeu range l'humidité en quatre bandes et chaque
gisement en occupe exactement deux — sec vaut mieux qu'humide.

La table est donc **complète** : chaque matière de chaque zone y figure
sous ses deux conditions. Le classeur de la guilde, qu'elle remplace,
était rempli de mémoire et ne s'accordait avec le jeu que sur une matière
sur quarante-six.

Fichier produit par ../zyroom-android/outils/table_pop.py — ne pas
modifier à la main.
"""

#: {saison: {zone: {condition: {famille: [matières]}}}}
POP = {
    "PRINTEMPS": {
        "Sources Interdites": {
            "WORST": {
                "Ambres": ["Pha", "Zun"],
                "Graines": ["Sarina", "Silvio"],
                "Fibres": ["Buo"],
                "Résine": ["Lune"],
                "Huile": ["Irin", "Pilan"],
                "Sève": ["Dante"],
                "Carapace": ["Grosse", "Splinter"],
                "Écorce": ["Oath", "Perfling"],
                "Bois": ["Kachine"],
                "Boucles": ["Nita"],
            },
            "BAD": {
                "Ambres": ["Beng", "Soo", "Zun"],
                "Graines": ["Caprice", "Saurona"],
                "Fibres": ["Anète", "Buo"],
                "Résine": ["Colle"],
                "Huile": ["Gulatch", "Pilan"],
                "Sève": ["Ardente", "Dante", "Silverweed"],
                "Carapace": ["Inteligente", "Mignonne"],
                "Écorce": ["Beckers"],
                "Bois": ["Tama"],
                "Boucles": ["Scratch", "Yana"],
            },
            "GOOD": {
                "Ambres": ["Beng", "Pha", "Sha"],
                "Graines": ["Saurona", "Silvio"],
                "Résine": ["Colle", "Dung", "Lune"],
                "Huile": ["Irin"],
                "Sève": ["Ardente"],
                "Carapace": ["Mignonne", "Splinter"],
                "Écorce": ["Beckers", "Oath"],
                "Bois": ["Eyota"],
                "Boucles": ["Patee", "Scratch"],
            },
            "BEST": {
                "Ambres": ["Sha", "Soo"],
                "Graines": ["Caprice", "Sarina"],
                "Fibres": ["Anète"],
                "Résine": ["Dung"],
                "Huile": ["Gulatch"],
                "Sève": ["Silverweed"],
                "Carapace": ["Grosse", "Inteligente"],
                "Écorce": ["Perfling"],
                "Bois": ["Eyota", "Kachine", "Tama"],
                "Boucles": ["Nita", "Patee", "Yana"],
            },
        },
        "Terre de la Continuité": {
            "WORST": {
                "Ambres": ["Hash", "Pha", "Zun"],
                "Graines": ["Sarina", "Silvio"],
                "Fibres": ["Buo"],
                "Résine": ["Lune"],
                "Huile": ["Irin", "Pilan"],
                "Sève": ["Dante", "Visc"],
                "Carapace": ["Grosse", "Splinter"],
                "Écorce": ["Perfling"],
                "Bois": ["Motega"],
                "Boucles": ["Nita", "Tansy"],
            },
            "BAD": {
                "Ambres": ["Zun"],
                "Graines": ["Caprice"],
                "Fibres": ["Anète", "Buo"],
                "Résine": ["Colle"],
                "Huile": ["Koorin", "Pilan"],
                "Sève": ["Dante"],
                "Carapace": ["Inteligente"],
                "Écorce": ["Beckers"],
                "Bois": ["Motega"],
                "Boucles": ["Tansy", "Yana"],
            },
            "GOOD": {
                "Ambres": ["Pha", "Sha"],
                "Graines": ["Silvio"],
                "Fibres": ["Shu"],
                "Résine": ["Colle", "Lune"],
                "Huile": ["Irin", "Koorin"],
                "Sève": ["Enola", "Visc"],
                "Carapace": ["Cornée", "Splinter"],
                "Écorce": ["Adriel", "Beckers"],
                "Boucles": ["Patee"],
            },
            "BEST": {
                "Ambres": ["Hash", "Sha"],
                "Graines": ["Caprice", "Sarina"],
                "Fibres": ["Anète", "Shu"],
                "Sève": ["Enola"],
                "Carapace": ["Cornée", "Grosse", "Inteligente"],
                "Écorce": ["Adriel", "Perfling"],
                "Boucles": ["Nita", "Patee", "Yana"],
            },
        },
        "Cité Engloutie": {
            "WORST": {
                "Ambres": ["Pha"],
                "Graines": ["Silvio"],
                "Fibres": ["Buo", "Dzao"],
                "Résine": ["Lune"],
                "Sève": ["Dante"],
                "Carapace": ["Grosse", "Splinter"],
                "Écorce": ["Mitexi", "Oath"],
                "Bois": ["Abhaya", "Motega"],
                "Boucles": ["Nita", "Tansy"],
            },
            "BAD": {
                "Ambres": ["Soo"],
                "Graines": ["Caprice", "Saurona"],
                "Fibres": ["Anète", "Buo"],
                "Huile": ["Gulatch", "Koorin"],
                "Sève": ["Ardente", "Dante"],
                "Carapace": ["Inteligente", "Mignonne"],
                "Écorce": ["Beckers", "Mitexi"],
                "Bois": ["Motega"],
                "Boucles": ["Scratch", "Tansy", "Yana"],
            },
            "GOOD": {
                "Ambres": ["Pha"],
                "Graines": ["Saurona", "Silvio"],
                "Fibres": ["Shu"],
                "Résine": ["Dung", "Lune"],
                "Huile": ["Koorin"],
                "Sève": ["Ardente"],
                "Carapace": ["Cornée", "Mignonne", "Splinter"],
                "Écorce": ["Adriel", "Beckers", "Oath"],
                "Bois": ["Abhaya", "Eyota"],
                "Boucles": ["Patee", "Scratch"],
            },
            "BEST": {
                "Ambres": ["Soo"],
                "Graines": ["Caprice"],
                "Fibres": ["Anète", "Dzao", "Shu"],
                "Résine": ["Dung"],
                "Huile": ["Gulatch"],
                "Carapace": ["Cornée", "Grosse", "Inteligente"],
                "Écorce": ["Adriel"],
                "Bois": ["Eyota"],
                "Boucles": ["Nita", "Patee", "Yana"],
            },
        },
        "Profondeurs Interdites": {
            "WORST": {
                "Ambres": ["Hash", "Pha", "Zun"],
                "Graines": ["Sarina", "Silvio"],
                "Fibres": ["Buo", "Dzao"],
                "Résine": ["Lune"],
                "Huile": ["Irin"],
                "Sève": ["Dante"],
                "Carapace": ["Splinter"],
                "Écorce": ["Mitexi", "Perfling"],
                "Bois": ["Abhaya", "Motega"],
                "Boucles": ["Nita", "Tansy"],
            },
            "BAD": {
                "Ambres": ["Beng", "Zun"],
                "Fibres": ["Anète", "Buo"],
                "Huile": ["Gulatch", "Koorin"],
                "Sève": ["Dante", "Silverweed"],
                "Carapace": ["Inteligente", "Mignonne"],
                "Écorce": ["Beckers", "Mitexi"],
                "Bois": ["Motega"],
                "Boucles": ["Scratch", "Tansy", "Yana"],
            },
            "GOOD": {
                "Ambres": ["Beng", "Pha"],
                "Graines": ["Silvio"],
                "Fibres": ["Shu"],
                "Résine": ["Dung", "Lune"],
                "Huile": ["Irin", "Koorin"],
                "Sève": ["Enola"],
                "Carapace": ["Cornée", "Mignonne", "Splinter"],
                "Écorce": ["Adriel", "Beckers"],
                "Bois": ["Abhaya", "Eyota"],
                "Boucles": ["Patee", "Scratch"],
            },
            "BEST": {
                "Ambres": ["Hash"],
                "Graines": ["Sarina"],
                "Fibres": ["Anète", "Dzao", "Shu"],
                "Résine": ["Dung"],
                "Huile": ["Gulatch"],
                "Sève": ["Enola", "Silverweed"],
                "Carapace": ["Cornée", "Inteligente"],
                "Écorce": ["Adriel", "Perfling"],
                "Bois": ["Eyota"],
                "Boucles": ["Nita", "Patee", "Yana"],
            },
        },
    },
    "ETE": {
        "Sources Interdites": {
            "WORST": {
                "Ambres": ["Hash", "Pha", "Zun"],
                "Graines": ["Sarina", "Silvio"],
                "Fibres": ["Buo"],
                "Résine": ["Lune"],
                "Huile": ["Irin", "Pilan"],
                "Sève": ["Dante"],
                "Écorce": ["Oath", "Perfling"],
                "Bois": ["Abhaya", "Kachine"],
                "Boucles": ["Nita"],
            },
            "BAD": {
                "Ambres": ["Beng", "Zun"],
                "Graines": ["Caprice"],
                "Fibres": ["Anète", "Buo"],
                "Résine": ["Colle"],
                "Huile": ["Gulatch", "Pilan"],
                "Sève": ["Ardente", "Dante", "Silverweed"],
                "Carapace": ["Inteligente", "Mignonne"],
                "Écorce": ["Beckers"],
                "Bois": ["Tama"],
                "Boucles": ["Scratch", "Yana"],
            },
            "GOOD": {
                "Ambres": ["Beng", "Pha", "Sha"],
                "Graines": ["Silvio"],
                "Fibres": ["Shu"],
                "Résine": ["Colle", "Dung", "Lune"],
                "Huile": ["Irin"],
                "Sève": ["Ardente"],
                "Carapace": ["Cornée", "Mignonne"],
                "Écorce": ["Adriel", "Beckers", "Oath"],
                "Bois": ["Abhaya", "Eyota"],
                "Boucles": ["Patee", "Scratch"],
            },
            "BEST": {
                "Ambres": ["Hash", "Sha"],
                "Graines": ["Caprice", "Sarina"],
                "Fibres": ["Anète", "Shu"],
                "Résine": ["Dung"],
                "Huile": ["Gulatch"],
                "Sève": ["Silverweed"],
                "Carapace": ["Cornée", "Inteligente"],
                "Écorce": ["Adriel", "Perfling"],
                "Bois": ["Eyota", "Kachine", "Tama"],
                "Boucles": ["Nita", "Patee", "Yana"],
            },
        },
        "Terre de la Continuité": {
            "WORST": {
                "Ambres": ["Hash", "Pha", "Zun"],
                "Graines": ["Sarina", "Silvio"],
                "Résine": ["Fung", "Lune"],
                "Huile": ["Irin", "Pilan"],
                "Sève": ["Dante"],
                "Carapace": ["Grosse", "Splinter"],
                "Écorce": ["Mitexi", "Oath"],
                "Bois": ["Kachine", "Motega"],
                "Boucles": ["Nita"],
            },
            "BAD": {
                "Ambres": ["Zun"],
                "Graines": ["Caprice", "Saurona"],
                "Fibres": ["Anète"],
                "Résine": ["Colle", "Fung"],
                "Huile": ["Gulatch", "Koorin", "Pilan"],
                "Sève": ["Dante"],
                "Carapace": ["Inteligente"],
                "Écorce": ["Beckers", "Mitexi"],
                "Bois": ["Motega"],
                "Boucles": ["Scratch"],
            },
            "GOOD": {
                "Ambres": ["Pha", "Sha"],
                "Graines": ["Saurona", "Silvio"],
                "Fibres": ["Shu"],
                "Résine": ["Colle", "Lune"],
                "Huile": ["Irin", "Koorin"],
                "Sève": ["Enola"],
                "Carapace": ["Cornée", "Splinter"],
                "Écorce": ["Adriel", "Beckers", "Oath"],
                "Boucles": ["Patee", "Scratch"],
            },
            "BEST": {
                "Ambres": ["Hash", "Sha"],
                "Graines": ["Caprice", "Sarina"],
                "Fibres": ["Anète", "Shu"],
                "Huile": ["Gulatch"],
                "Sève": ["Enola"],
                "Carapace": ["Cornée", "Grosse", "Inteligente"],
                "Écorce": ["Adriel"],
                "Bois": ["Kachine"],
                "Boucles": ["Nita", "Patee"],
            },
        },
        "Cité Engloutie": {
            "WORST": {
                "Ambres": ["Hash", "Pha", "Zun"],
                "Graines": ["Sarina", "Silvio"],
                "Fibres": ["Buo", "Dzao"],
                "Résine": ["Fung", "Lune"],
                "Huile": ["Pilan"],
                "Sève": ["Dante"],
                "Carapace": ["Grosse", "Splinter"],
                "Écorce": ["Mitexi", "Oath"],
                "Bois": ["Abhaya", "Kachine", "Motega"],
                "Boucles": ["Nita", "Tansy"],
            },
            "BAD": {
                "Ambres": ["Soo", "Zun"],
                "Graines": ["Caprice", "Saurona"],
                "Fibres": ["Anète", "Buo"],
                "Résine": ["Colle", "Fung"],
                "Huile": ["Gulatch", "Koorin", "Pilan"],
                "Sève": ["Ardente", "Dante", "Silverweed"],
                "Carapace": ["Inteligente"],
                "Écorce": ["Beckers", "Mitexi"],
                "Bois": ["Motega", "Tama"],
                "Boucles": ["Scratch", "Tansy"],
            },
            "GOOD": {
                "Ambres": ["Pha"],
                "Graines": ["Saurona", "Silvio"],
                "Fibres": ["Shu"],
                "Résine": ["Colle", "Dung", "Lune"],
                "Huile": ["Koorin"],
                "Sève": ["Ardente"],
                "Carapace": ["Cornée", "Splinter"],
                "Écorce": ["Adriel", "Beckers", "Oath"],
                "Bois": ["Abhaya"],
                "Boucles": ["Patee", "Scratch"],
            },
            "BEST": {
                "Ambres": ["Hash", "Soo"],
                "Graines": ["Caprice", "Sarina"],
                "Fibres": ["Anète", "Dzao", "Shu"],
                "Résine": ["Dung"],
                "Huile": ["Gulatch"],
                "Sève": ["Silverweed"],
                "Carapace": ["Cornée", "Grosse", "Inteligente"],
                "Écorce": ["Adriel"],
                "Bois": ["Kachine", "Tama"],
                "Boucles": ["Nita", "Patee"],
            },
        },
        "Profondeurs Interdites": {
            "WORST": {
                "Ambres": ["Pha"],
                "Graines": ["Sarina", "Silvio"],
                "Fibres": ["Buo"],
                "Résine": ["Fung", "Lune"],
                "Huile": ["Irin"],
                "Sève": ["Dante"],
                "Écorce": ["Mitexi", "Oath", "Perfling"],
                "Bois": ["Kachine"],
                "Boucles": ["Nita", "Tansy"],
            },
            "BAD": {
                "Ambres": ["Beng"],
                "Graines": ["Saurona"],
                "Fibres": ["Anète", "Buo"],
                "Résine": ["Colle", "Fung"],
                "Huile": ["Gulatch", "Koorin"],
                "Sève": ["Dante", "Silverweed"],
                "Carapace": ["Inteligente", "Mignonne"],
                "Écorce": ["Mitexi"],
                "Bois": ["Tama"],
                "Boucles": ["Scratch", "Tansy"],
            },
            "GOOD": {
                "Ambres": ["Beng", "Pha", "Sha"],
                "Graines": ["Saurona", "Silvio"],
                "Fibres": ["Shu"],
                "Résine": ["Colle", "Dung", "Lune"],
                "Huile": ["Irin", "Koorin"],
                "Carapace": ["Cornée", "Mignonne"],
                "Écorce": ["Adriel", "Oath"],
                "Bois": ["Eyota"],
                "Boucles": ["Patee", "Scratch"],
            },
            "BEST": {
                "Ambres": ["Sha"],
                "Graines": ["Sarina"],
                "Fibres": ["Anète", "Shu"],
                "Résine": ["Dung"],
                "Huile": ["Gulatch"],
                "Sève": ["Silverweed"],
                "Carapace": ["Cornée", "Inteligente"],
                "Écorce": ["Adriel", "Perfling"],
                "Bois": ["Eyota", "Kachine", "Tama"],
                "Boucles": ["Nita", "Patee"],
            },
        },
    },
    "AUTOMNE": {
        "Sources Interdites": {
            "WORST": {
                "Ambres": ["Pha", "Zun"],
                "Graines": ["Silvio"],
                "Fibres": ["Buo"],
                "Résine": ["Fung", "Lune"],
                "Huile": ["Irin", "Pilan"],
                "Sève": ["Dante"],
                "Carapace": ["Grosse"],
                "Écorce": ["Mitexi", "Oath", "Perfling"],
                "Bois": ["Abhaya", "Kachine", "Motega"],
                "Boucles": ["Nita", "Tansy"],
            },
            "BAD": {
                "Ambres": ["Beng", "Zun"],
                "Graines": ["Caprice"],
                "Fibres": ["Anète", "Buo"],
                "Résine": ["Colle", "Fung"],
                "Huile": ["Gulatch", "Pilan"],
                "Sève": ["Ardente", "Dante", "Silverweed"],
                "Carapace": ["Inteligente", "Mignonne"],
                "Écorce": ["Beckers", "Mitexi"],
                "Bois": ["Motega", "Tama"],
                "Boucles": ["Scratch", "Tansy", "Yana"],
            },
            "GOOD": {
                "Ambres": ["Beng", "Pha", "Sha"],
                "Graines": ["Silvio"],
                "Résine": ["Colle", "Dung", "Lune"],
                "Huile": ["Irin"],
                "Sève": ["Ardente", "Enola"],
                "Carapace": ["Mignonne"],
                "Écorce": ["Beckers", "Oath"],
                "Bois": ["Abhaya", "Eyota"],
                "Boucles": ["Patee", "Scratch"],
            },
            "BEST": {
                "Ambres": ["Sha"],
                "Graines": ["Caprice"],
                "Fibres": ["Anète"],
                "Résine": ["Dung"],
                "Huile": ["Gulatch"],
                "Sève": ["Enola", "Silverweed"],
                "Carapace": ["Grosse", "Inteligente"],
                "Écorce": ["Perfling"],
                "Bois": ["Eyota", "Kachine", "Tama"],
                "Boucles": ["Nita", "Patee", "Yana"],
            },
        },
        "Terre de la Continuité": {
            "WORST": {
                "Ambres": ["Hash", "Pha", "Zun"],
                "Graines": ["Sarina", "Silvio"],
                "Fibres": ["Buo", "Dzao"],
                "Résine": ["Lune"],
                "Huile": ["Irin", "Pilan"],
                "Sève": ["Dante"],
                "Carapace": ["Grosse", "Splinter"],
                "Bois": ["Abhaya", "Motega"],
                "Boucles": ["Nita"],
            },
            "BAD": {
                "Ambres": ["Beng", "Zun"],
                "Graines": ["Caprice", "Saurona"],
                "Fibres": ["Buo"],
                "Résine": ["Colle"],
                "Huile": ["Koorin", "Pilan"],
                "Sève": ["Ardente", "Dante", "Silverweed"],
                "Carapace": ["Inteligente"],
                "Écorce": ["Beckers"],
                "Bois": ["Motega"],
            },
            "GOOD": {
                "Ambres": ["Beng", "Pha", "Sha"],
                "Graines": ["Saurona", "Silvio"],
                "Fibres": ["Shu"],
                "Résine": ["Colle", "Lune"],
                "Huile": ["Irin", "Koorin"],
                "Sève": ["Ardente", "Enola"],
                "Carapace": ["Cornée", "Splinter"],
                "Écorce": ["Adriel", "Beckers"],
                "Bois": ["Abhaya"],
                "Boucles": ["Patee"],
            },
            "BEST": {
                "Ambres": ["Hash", "Sha"],
                "Graines": ["Caprice", "Sarina"],
                "Fibres": ["Dzao", "Shu"],
                "Sève": ["Enola", "Silverweed"],
                "Carapace": ["Cornée", "Grosse", "Inteligente"],
                "Écorce": ["Adriel"],
                "Boucles": ["Nita", "Patee"],
            },
        },
        "Cité Engloutie": {
            "WORST": {
                "Ambres": ["Pha"],
                "Graines": ["Silvio"],
                "Fibres": ["Buo", "Dzao"],
                "Résine": ["Lune"],
                "Sève": ["Dante"],
                "Carapace": ["Grosse", "Splinter"],
                "Écorce": ["Mitexi", "Perfling"],
                "Bois": ["Abhaya", "Motega"],
                "Boucles": ["Nita", "Tansy"],
            },
            "BAD": {
                "Graines": ["Caprice", "Saurona"],
                "Fibres": ["Anète", "Buo"],
                "Résine": ["Colle"],
                "Huile": ["Gulatch", "Koorin"],
                "Sève": ["Dante", "Silverweed"],
                "Carapace": ["Inteligente"],
                "Écorce": ["Mitexi"],
                "Bois": ["Motega", "Tama"],
                "Boucles": ["Scratch", "Tansy"],
            },
            "GOOD": {
                "Ambres": ["Pha", "Sha"],
                "Graines": ["Saurona", "Silvio"],
                "Fibres": ["Shu"],
                "Résine": ["Colle", "Dung", "Lune"],
                "Huile": ["Koorin"],
                "Sève": ["Enola"],
                "Carapace": ["Cornée", "Splinter"],
                "Écorce": ["Adriel"],
                "Bois": ["Abhaya"],
                "Boucles": ["Patee", "Scratch"],
            },
            "BEST": {
                "Ambres": ["Sha"],
                "Graines": ["Caprice"],
                "Fibres": ["Anète", "Dzao", "Shu"],
                "Résine": ["Dung"],
                "Huile": ["Gulatch"],
                "Sève": ["Enola", "Silverweed"],
                "Carapace": ["Cornée", "Grosse", "Inteligente"],
                "Écorce": ["Adriel", "Perfling"],
                "Bois": ["Tama"],
                "Boucles": ["Nita", "Patee"],
            },
        },
        "Profondeurs Interdites": {
            "WORST": {
                "Ambres": ["Pha", "Zun"],
                "Graines": ["Sarina", "Silvio"],
                "Fibres": ["Buo"],
                "Résine": ["Fung", "Lune"],
                "Huile": ["Irin"],
                "Sève": ["Dante", "Visc"],
                "Écorce": ["Mitexi", "Perfling"],
                "Bois": ["Motega"],
                "Boucles": ["Nita", "Tansy"],
            },
            "BAD": {
                "Ambres": ["Beng", "Zun"],
                "Graines": ["Caprice"],
                "Fibres": ["Anète", "Buo"],
                "Résine": ["Fung"],
                "Huile": ["Gulatch", "Koorin"],
                "Sève": ["Ardente", "Dante", "Silverweed"],
                "Carapace": ["Inteligente", "Mignonne"],
                "Écorce": ["Beckers", "Mitexi"],
                "Bois": ["Motega", "Tama"],
                "Boucles": ["Scratch", "Tansy"],
            },
            "GOOD": {
                "Ambres": ["Beng", "Pha"],
                "Graines": ["Silvio"],
                "Résine": ["Dung", "Lune"],
                "Huile": ["Irin", "Koorin"],
                "Sève": ["Ardente", "Visc"],
                "Carapace": ["Cornée", "Mignonne"],
                "Écorce": ["Adriel", "Beckers"],
                "Bois": ["Eyota"],
                "Boucles": ["Patee", "Scratch"],
            },
            "BEST": {
                "Graines": ["Caprice", "Sarina"],
                "Fibres": ["Anète"],
                "Résine": ["Dung"],
                "Huile": ["Gulatch"],
                "Sève": ["Silverweed"],
                "Carapace": ["Cornée", "Inteligente"],
                "Écorce": ["Adriel", "Perfling"],
                "Bois": ["Eyota", "Tama"],
                "Boucles": ["Nita", "Patee"],
            },
        },
    },
    "HIVER": {
        "Sources Interdites": {
            "WORST": {
                "Ambres": ["Pha", "Zun"],
                "Graines": ["Silvio"],
                "Fibres": ["Buo", "Dzao"],
                "Résine": ["Lune"],
                "Huile": ["Irin", "Pilan"],
                "Sève": ["Dante", "Visc"],
                "Écorce": ["Mitexi", "Oath", "Perfling"],
                "Bois": ["Kachine"],
                "Boucles": ["Nita"],
            },
            "BAD": {
                "Ambres": ["Beng", "Zun"],
                "Graines": ["Caprice"],
                "Fibres": ["Anète", "Buo"],
                "Résine": ["Colle"],
                "Huile": ["Gulatch", "Koorin", "Pilan"],
                "Sève": ["Ardente", "Dante", "Silverweed"],
                "Carapace": ["Inteligente", "Mignonne"],
                "Écorce": ["Beckers", "Mitexi"],
                "Bois": ["Tama"],
                "Boucles": ["Scratch", "Yana"],
            },
            "GOOD": {
                "Ambres": ["Beng", "Pha", "Sha"],
                "Graines": ["Silvio"],
                "Fibres": ["Shu"],
                "Résine": ["Colle", "Dung", "Lune"],
                "Huile": ["Irin", "Koorin"],
                "Sève": ["Ardente", "Visc"],
                "Carapace": ["Mignonne"],
                "Écorce": ["Beckers", "Oath"],
                "Bois": ["Eyota"],
                "Boucles": ["Patee", "Scratch"],
            },
            "BEST": {
                "Ambres": ["Sha"],
                "Graines": ["Caprice"],
                "Fibres": ["Anète", "Dzao", "Shu"],
                "Résine": ["Dung"],
                "Huile": ["Gulatch"],
                "Sève": ["Silverweed"],
                "Carapace": ["Inteligente"],
                "Écorce": ["Perfling"],
                "Bois": ["Eyota", "Kachine", "Tama"],
                "Boucles": ["Nita", "Patee", "Yana"],
            },
        },
        "Terre de la Continuité": {
            "WORST": {
                "Ambres": ["Hash", "Pha", "Zun"],
                "Graines": ["Sarina", "Silvio"],
                "Fibres": ["Buo", "Dzao"],
                "Résine": ["Lune"],
                "Huile": ["Irin", "Pilan"],
                "Sève": ["Dante", "Visc"],
                "Carapace": ["Grosse", "Splinter"],
                "Bois": ["Kachine", "Motega"],
                "Boucles": ["Nita"],
            },
            "BAD": {
                "Ambres": ["Beng", "Soo", "Zun"],
                "Graines": ["Caprice"],
                "Fibres": ["Buo"],
                "Résine": ["Colle"],
                "Huile": ["Koorin", "Pilan"],
                "Sève": ["Dante"],
                "Carapace": ["Inteligente", "Mignonne"],
                "Écorce": ["Beckers"],
                "Bois": ["Motega", "Tama"],
                "Boucles": ["Scratch"],
            },
            "GOOD": {
                "Ambres": ["Beng", "Pha", "Sha"],
                "Graines": ["Silvio"],
                "Fibres": ["Shu"],
                "Résine": ["Colle", "Dung", "Lune"],
                "Huile": ["Irin", "Koorin"],
                "Sève": ["Enola", "Visc"],
                "Carapace": ["Cornée", "Mignonne", "Splinter"],
                "Écorce": ["Adriel", "Beckers"],
                "Boucles": ["Patee", "Scratch"],
            },
            "BEST": {
                "Ambres": ["Hash", "Sha", "Soo"],
                "Graines": ["Caprice", "Sarina"],
                "Fibres": ["Dzao", "Shu"],
                "Résine": ["Dung"],
                "Sève": ["Enola"],
                "Carapace": ["Cornée", "Grosse", "Inteligente"],
                "Écorce": ["Adriel"],
                "Bois": ["Kachine", "Tama"],
                "Boucles": ["Nita", "Patee"],
            },
        },
        "Cité Engloutie": {
            "WORST": {
                "Ambres": ["Hash", "Pha", "Zun"],
                "Graines": ["Silvio"],
                "Fibres": ["Buo", "Dzao"],
                "Résine": ["Lune"],
                "Huile": ["Irin"],
                "Sève": ["Dante", "Visc"],
                "Carapace": ["Grosse", "Splinter"],
                "Écorce": ["Mitexi", "Perfling"],
                "Bois": ["Abhaya"],
                "Boucles": ["Nita", "Tansy"],
            },
            "BAD": {
                "Ambres": ["Beng", "Zun"],
                "Graines": ["Caprice", "Saurona"],
                "Fibres": ["Anète", "Buo"],
                "Résine": ["Colle"],
                "Huile": ["Gulatch", "Koorin"],
                "Sève": ["Dante", "Silverweed"],
                "Carapace": ["Inteligente"],
                "Écorce": ["Mitexi"],
                "Bois": ["Tama"],
                "Boucles": ["Scratch", "Tansy"],
            },
            "GOOD": {
                "Ambres": ["Beng", "Pha", "Sha"],
                "Graines": ["Saurona", "Silvio"],
                "Fibres": ["Shu"],
                "Résine": ["Colle", "Dung", "Lune"],
                "Huile": ["Irin", "Koorin"],
                "Sève": ["Enola", "Visc"],
                "Carapace": ["Cornée", "Splinter"],
                "Bois": ["Abhaya"],
                "Boucles": ["Patee", "Scratch"],
            },
            "BEST": {
                "Ambres": ["Hash", "Sha"],
                "Graines": ["Caprice"],
                "Fibres": ["Anète", "Dzao", "Shu"],
                "Résine": ["Dung"],
                "Huile": ["Gulatch"],
                "Sève": ["Enola", "Silverweed"],
                "Carapace": ["Cornée", "Grosse", "Inteligente"],
                "Écorce": ["Perfling"],
                "Bois": ["Tama"],
                "Boucles": ["Nita", "Patee"],
            },
        },
        "Profondeurs Interdites": {
            "WORST": {
                "Ambres": ["Pha"],
                "Graines": ["Sarina", "Silvio"],
                "Fibres": ["Buo", "Dzao"],
                "Résine": ["Lune"],
                "Huile": ["Irin", "Pilan"],
                "Sève": ["Dante"],
                "Carapace": ["Grosse"],
                "Écorce": ["Mitexi", "Perfling"],
                "Bois": ["Abhaya"],
                "Boucles": ["Nita", "Tansy"],
            },
            "BAD": {
                "Ambres": ["Beng", "Soo"],
                "Graines": ["Caprice", "Saurona"],
                "Fibres": ["Anète", "Buo"],
                "Huile": ["Gulatch", "Koorin", "Pilan"],
                "Sève": ["Dante", "Silverweed"],
                "Carapace": ["Inteligente", "Mignonne"],
                "Écorce": ["Mitexi"],
                "Bois": ["Tama"],
                "Boucles": ["Scratch", "Tansy"],
            },
            "GOOD": {
                "Ambres": ["Beng", "Pha"],
                "Graines": ["Saurona", "Silvio"],
                "Résine": ["Dung", "Lune"],
                "Huile": ["Irin", "Koorin"],
                "Carapace": ["Cornée", "Mignonne"],
                "Écorce": ["Adriel"],
                "Bois": ["Abhaya"],
                "Boucles": ["Patee", "Scratch"],
            },
            "BEST": {
                "Ambres": ["Soo"],
                "Graines": ["Caprice", "Sarina"],
                "Fibres": ["Anète", "Dzao"],
                "Résine": ["Dung"],
                "Huile": ["Gulatch"],
                "Sève": ["Silverweed"],
                "Carapace": ["Cornée", "Grosse", "Inteligente"],
                "Écorce": ["Adriel", "Perfling"],
                "Bois": ["Tama"],
                "Boucles": ["Nita", "Patee"],
            },
        },
    },
}

#: Zone du relevé -> continent interrogé pour la météo.
CONTINENT_DE_ZONE = {
    "Sources Interdites": "sources",
    "Terre de la Continuité": "terre",
    "Cité Engloutie": "terre",
    "Profondeurs Interdites": "terre",
}
