"""Les matières suprêmes et excellentes, par saison.

Fichier produit par ../zyroom-android/outils/table_armory.py — ne pas
modifier à la main. Relevé de Ryzom Armory, figé ici : ces listes ne
changent qu'avec le jeu, et l'application doit tenir le jour où ce site
fermera.
"""

#: {saison: {zone des Primes: {groupe: [noms]}}}
SUPREMES = {
    "PRINTEMPS": {
        "Sources Interdites": {
            "Graines": ["Caprice", "Sarina", "Saurona", "Silvio"],
            "Carapace": ["Big", "Cuty", "Smart", "Splinter"],
            "Fibres": ["Anete", "Buo"],
            "Bois": ["Eyota", "Kachine", "Tama"],
            "Boucles": ["Nita", "Patee", "Scrath", "Yana"],
            "Ambres": ["Beng", "Pha", "Sha", "Soo", "Zun"],
            "Huile": ["Gulatch", "Irin", "Pilan"],
            "Résine": ["Dung", "Glue", "Moon"],
            "Écorce": ["Beckers", "Oath", "Perfling"],
            "Sève": ["Dante", "Redhot", "Silverweed"],
        },
        "Profondeurs Interdites": {
            "Graines": ["Sarina", "Silvio"],
            "Carapace": ["Cuty", "Horny", "Smart", "Splinter"],
            "Fibres": ["Anete", "Buo", "Dzao", "Shu"],
            "Bois": ["Abhaya", "Eyota", "Motega"],
            "Boucles": ["Nita", "Patee", "Scrath", "Tansy", "Yana"],
            "Ambres": ["Beng", "Hash", "Pha", "Zun"],
            "Huile": ["Gulatch", "Irin", "Koorin"],
            "Résine": ["Dung", "Moon"],
            "Écorce": ["Adriel", "Beckers", "Mitexi", "Perfling"],
            "Sève": ["Dante", "Enola", "Silverweed"],
        },
        "Terre de la Continuité": {
            "Graines": ["Caprice", "Sarina", "Silvio"],
            "Carapace": ["Big", "Horny", "Smart", "Splinter"],
            "Fibres": ["Anete", "Buo", "Shu"],
            "Bois": ["Motega"],
            "Boucles": ["Nita", "Patee", "Tansy", "Yana"],
            "Ambres": ["Hash", "Pha", "Sha", "Zun"],
            "Huile": ["Irin", "Koorin", "Pilan"],
            "Résine": ["Glue", "Moon"],
            "Écorce": ["Adriel", "Beckers", "Perfling"],
            "Sève": ["Dante", "Enola", "Visc"],
        },
        "Cité Engloutie": {
            "Graines": ["Caprice", "Saurona", "Silvio"],
            "Carapace": ["Big", "Cuty", "Horny", "Smart", "Splinter"],
            "Fibres": ["Anete", "Buo", "Dzao", "Shu"],
            "Bois": ["Abhaya", "Eyota", "Motega"],
            "Boucles": ["Nita", "Patee", "Scrath", "Tansy", "Yana"],
            "Ambres": ["Pha", "Soo"],
            "Huile": ["Gulatch", "Koorin"],
            "Résine": ["Dung", "Moon"],
            "Écorce": ["Adriel", "Beckers", "Mitexi", "Oath"],
            "Sève": ["Dante", "Redhot"],
        },
    },
    "ETE": {
        "Cité Engloutie": {
            "Graines": ["Caprice", "Sarina", "Saurona", "Silvio"],
            "Carapace": ["Big", "Horny", "Smart", "Splinter"],
            "Fibres": ["Anete", "Buo", "Dzao", "Shu"],
            "Bois": ["Abhaya", "Kachine", "Motega", "Tama"],
            "Boucles": ["Nita", "Patee", "Scrath", "Tansy"],
            "Ambres": ["Hash", "Pha", "Soo", "Zun"],
            "Huile": ["Gulatch", "Koorin", "Pilan"],
            "Résine": ["Dung", "Fung", "Glue", "Moon"],
            "Écorce": ["Adriel", "Beckers", "Mitexi", "Oath"],
            "Sève": ["Dante", "Redhot", "Silverweed"],
        },
        "Profondeurs Interdites": {
            "Graines": ["Sarina", "Saurona", "Silvio"],
            "Carapace": ["Cuty", "Horny", "Smart"],
            "Fibres": ["Anete", "Buo", "Shu"],
            "Bois": ["Eyota", "Kachine", "Tama"],
            "Boucles": ["Nita", "Patee", "Scrath", "Tansy"],
            "Huile": ["Gulatch", "Irin", "Koorin"],
            "Résine": ["Dung", "Fung", "Glue", "Moon"],
            "Ambres": ["Beng", "Pha", "Sha"],
            "Écorce": ["Adriel", "Mitexi", "Oath", "Perfling"],
            "Sève": ["Dante", "Silverweed"],
        },
        "Sources Interdites": {
            "Graines": ["Caprice", "Sarina", "Silvio"],
            "Carapace": ["Cuty", "Horny", "Smart"],
            "Fibres": ["Anete", "Buo", "Shu"],
            "Bois": ["Abhaya", "Eyota", "Kachine", "Tama"],
            "Boucles": ["Nita", "Patee", "Scrath", "Yana"],
            "Ambres": ["Beng", "Hash", "Pha", "Sha", "Zun"],
            "Huile": ["Gulatch", "Irin", "Pilan"],
            "Résine": ["Dung", "Glue", "Moon"],
            "Écorce": ["Adriel", "Beckers", "Oath", "Perfling"],
            "Sève": ["Dante", "Redhot", "Silverweed"],
        },
        "Terre de la Continuité": {
            "Graines": ["Caprice", "Sarina", "Saurona", "Silvio"],
            "Carapace": ["Big", "Horny", "Smart", "Splinter"],
            "Fibres": ["Anete", "Shu"],
            "Bois": ["Kachine", "Motega"],
            "Boucles": ["Nita", "Patee", "Scrath"],
            "Ambres": ["Hash", "Pha", "Sha", "Zun"],
            "Huile": ["Gulatch", "Irin", "Koorin", "Pilan"],
            "Résine": ["Fung", "Glue", "Moon"],
            "Écorce": ["Adriel", "Beckers", "Mitexi", "Oath"],
            "Sève": ["Dante", "Enola"],
        },
    },
    "AUTOMNE": {
        "Profondeurs Interdites": {
            "Graines": ["Caprice", "Sarina", "Silvio"],
            "Carapace": ["Cuty", "Horny", "Smart"],
            "Fibres": ["Anete", "Buo"],
            "Bois": ["Eyota", "Motega", "Tama"],
            "Boucles": ["Nita", "Patee", "Scrath", "Tansy"],
            "Ambres": ["Beng", "Pha", "Zun"],
            "Huile": ["Gulatch", "Irin", "Koorin"],
            "Résine": ["Dung", "Fung", "Moon"],
            "Écorce": ["Adriel", "Beckers", "Mitexi", "Perfling"],
            "Sève": ["Dante", "Redhot", "Silverweed", "Visc"],
        },
        "Terre de la Continuité": {
            "Graines": ["Caprice", "Sarina", "Saurona", "Silvio"],
            "Carapace": ["Big", "Horny", "Smart", "Splinter"],
            "Fibres": ["Buo", "Dzao", "Shu"],
            "Bois": ["Abhaya", "Motega"],
            "Boucles": ["Nita", "Patee"],
            "Ambres": ["Beng", "Hash", "Pha", "Sha", "Zun"],
            "Huile": ["Irin", "Koorin", "Pilan"],
            "Résine": ["Glue", "Moon"],
            "Écorce": ["Adriel", "Beckers"],
            "Sève": ["Dante", "Enola", "Redhot", "Silverweed"],
        },
        "Cité Engloutie": {
            "Graines": ["Caprice", "Saurona", "Silvio"],
            "Carapace": ["Big", "Horny", "Smart", "Splinter"],
            "Fibres": ["Anete", "Buo", "Dzao", "Shu"],
            "Bois": ["Abhaya", "Motega", "Tama"],
            "Boucles": ["Nita", "Patee", "Scrath", "Tansy"],
            "Huile": ["Gulatch", "Koorin"],
            "Résine": ["Dung", "Glue", "Moon"],
            "Ambres": ["Pha", "Sha"],
            "Écorce": ["Adriel", "Mitexi", "Perfling"],
            "Sève": ["Dante", "Enola", "Silverweed"],
        },
        "Sources Interdites": {
            "Graines": ["Caprice", "Silvio"],
            "Carapace": ["Big", "Cuty", "Smart"],
            "Fibres": ["Anete", "Buo"],
            "Bois": ["Abhaya", "Eyota", "Kachine", "Motega", "Tama"],
            "Boucles": ["Nita", "Patee", "Scrath", "Tansy", "Yana"],
            "Ambres": ["Beng", "Pha", "Sha", "Zun"],
            "Huile": ["Gulatch", "Irin", "Pilan"],
            "Résine": ["Dung", "Fung", "Glue", "Moon"],
            "Écorce": ["Beckers", "Mitexi", "Oath", "Perfling"],
            "Sève": ["Dante", "Enola", "Redhot", "Silverweed"],
        },
    },
    "HIVER": {
        "Cité Engloutie": {
            "Graines": ["Caprice", "Saurona", "Silvio"],
            "Carapace": ["Big", "Horny", "Smart", "Splinter"],
            "Fibres": ["Anete", "Buo", "Dzao", "Shu"],
            "Bois": ["Abhaya", "Tama"],
            "Boucles": ["Nita", "Patee", "Scrath", "Tansy"],
            "Ambres": ["Beng", "Hash", "Pha", "Sha", "Zun"],
            "Huile": ["Gulatch", "Irin", "Koorin"],
            "Résine": ["Dung", "Glue", "Moon"],
            "Écorce": ["Mitexi", "Perfling"],
            "Sève": ["Dante", "Enola", "Silverweed", "Visc"],
        },
        "Profondeurs Interdites": {
            "Graines": ["Caprice", "Sarina", "Saurona", "Silvio"],
            "Carapace": ["Big", "Cuty", "Horny", "Smart"],
            "Fibres": ["Anete", "Buo", "Dzao"],
            "Bois": ["Abhaya", "Tama"],
            "Boucles": ["Nita", "Patee", "Scrath", "Tansy"],
            "Ambres": ["Beng", "Pha", "Soo"],
            "Huile": ["Gulatch", "Irin", "Koorin", "Pilan"],
            "Résine": ["Dung", "Moon"],
            "Écorce": ["Adriel", "Mitexi", "Perfling"],
            "Sève": ["Dante", "Silverweed"],
        },
        "Terre de la Continuité": {
            "Graines": ["Caprice", "Sarina", "Silvio"],
            "Carapace": ["Big", "Cuty", "Horny", "Smart", "Splinter"],
            "Fibres": ["Buo", "Dzao", "Shu"],
            "Bois": ["Kachine", "Motega", "Tama"],
            "Boucles": ["Nita", "Patee", "Scrath"],
            "Ambres": ["Beng", "Hash", "Pha", "Sha", "Soo", "Zun"],
            "Huile": ["Irin", "Koorin", "Pilan"],
            "Résine": ["Dung", "Glue", "Moon"],
            "Écorce": ["Adriel", "Beckers"],
            "Sève": ["Dante", "Enola", "Visc"],
        },
        "Sources Interdites": {
            "Graines": ["Caprice", "Silvio"],
            "Carapace": ["Cuty", "Smart"],
            "Fibres": ["Anete", "Buo", "Dzao", "Shu"],
            "Bois": ["Eyota", "Kachine", "Tama"],
            "Boucles": ["Nita", "Patee", "Scrath", "Yana"],
            "Ambres": ["Beng", "Pha", "Sha", "Zun"],
            "Huile": ["Gulatch", "Irin", "Koorin", "Pilan"],
            "Résine": ["Dung", "Glue", "Moon"],
            "Écorce": ["Beckers", "Mitexi", "Oath", "Perfling"],
            "Sève": ["Dante", "Redhot", "Silverweed", "Visc"],
        },
    },
}

#: {saison: {"JOUR"|"NUIT": {groupe: [noms]}}}
#: L'API ne les répartit pas par zone mais par moment de la journée :
#: c'est ainsi que le jeu les fait apparaître.
EXCELLENTES = {
    "PRINTEMPS": {
        "JOUR": {
            "Carapace": ["Big", "Cuty", "Horny", "Smart", "Splinter"],
            "Bois": ["Eyota", "Kachine", "Tama"],
            "Boucles": ["Tansy"],
            "Écorce": ["Beckers", "Mitexi", "Perfling"],
            "Sève": ["Dante", "Enola", "Redhot", "Silverweed", "Visc"],
        },
        "NUIT": {
            "Fibres": ["Anete", "Dzao", "Shu"],
            "Résine": ["Dung", "Fung", "Glue", "Moon"],
        },
    },
    "ETE": {
        "JOUR": {
            "Graines": ["Caprice", "Sarina", "Saurona", "Silvio"],
            "Fibres": ["Buo"],
            "Bois": ["Eyota", "Kachine", "Tama"],
            "Boucles": ["Nita", "Patee", "Scrath", "Yana"],
            "Ambres": ["Pha", "Zun"],
            "Écorce": ["Adriel"],
            "Sève": ["Dante", "Redhot", "Visc"],
        },
        "NUIT": {
            "Fibres": ["Anete", "Dzao", "Shu"],
            "Résine": ["Dung", "Fung", "Glue", "Moon"],
        },
    },
    "AUTOMNE": {
        "JOUR": {
            "Carapace": ["Big", "Cuty", "Horny", "Smart", "Splinter"],
            "Bois": ["Abhaya", "Motega"],
            "Boucles": ["Nita", "Patee", "Scrath", "Tansy", "Yana"],
            "Ambres": ["Beng", "Hash", "Pha", "Sha", "Soo", "Zun"],
        },
        "NUIT": {
            "Huile": ["Gulatch", "Irin", "Koorin", "Pilan"],
            "Résine": ["Dung"],
        },
    },
    "HIVER": {
        "JOUR": {
            "Graines": ["Caprice", "Sarina", "Saurona", "Silvio"],
            "Bois": ["Abhaya", "Motega"],
            "Ambres": ["Beng", "Hash", "Sha", "Soo"],
            "Écorce": ["Adriel", "Beckers", "Mitexi", "Oath", "Perfling"],
            "Sève": ["Enola", "Silverweed"],
        },
        "NUIT": {
            "Huile": ["Gulatch", "Irin", "Koorin", "Pilan"],
            "Résine": ["Dung"],
        },
    },
}
