"""Ce que rend un gisement des Primes, selon la zone, la saison et le temps.

Fichier produit par ../zyroom-android/outils/table_forage.py — ne pas
modifier à la main. Il croise `armory.py`, qui dit quelle matière sort
dans quelle zone et à quelle saison, avec les fourchettes d'humidité
de `donnees/humidites-gisements.json`, qui disent par quel temps.

**Les deux viennent du tracker d'atys.us**, et c'est ce qui compte :
c'est lui qu'on ouvre à côté pour vérifier. Une table qui ne lui
répond pas est fausse, si cohérente soit-elle avec elle-même.

Le choix reste vide : le tracker ne le suit pas, et le déduire par
élimination ferait dire à l'écran plus que ce qu'on sait.
"""

#: {zone: {(famille, matière): {(saison, condition)}}} — le suprême.
#:
#: Chaque gisement occupe deux des quatre bandes d'humidité : à toute
#: heure, une moitié des matières de la zone sort.
SUPREMES = {
    "Sources Interdites": {
        ("Ambres", "Beng"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Ambres", "Hash"): {
            ("ETE", "BEST"),
            ("ETE", "WORST"),
        },
        ("Ambres", "Pha"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Ambres", "Sha"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Ambres", "Soo"): {
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Ambres", "Zun"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BAD"),
            ("ETE", "WORST"),
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Bois", "Abhaya"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
        },
        ("Bois", "Eyota"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Bois", "Kachine"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
        ("Bois", "Motega"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
        },
        ("Bois", "Tama"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Boucles", "Nita"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
        ("Boucles", "Patee"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Boucles", "Scrath"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Boucles", "Tansy"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
        },
        ("Boucles", "Yana"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Carapace", "Big"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
        ("Carapace", "Cuty"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Carapace", "Horny"): {
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
        },
        ("Carapace", "Smart"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Carapace", "Splinter"): {
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Fibres", "Anete"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Fibres", "Buo"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BAD"),
            ("ETE", "WORST"),
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Fibres", "Dzao"): {
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
        },
        ("Fibres", "Shu"): {
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
        },
        ("Graines", "Caprice"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Graines", "Sarina"): {
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
        ("Graines", "Saurona"): {
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Graines", "Silvio"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Huile", "Gulatch"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Huile", "Irin"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Huile", "Koorin"): {
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
        },
        ("Huile", "Pilan"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BAD"),
            ("ETE", "WORST"),
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Résine", "Dung"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Résine", "Fung"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
        },
        ("Résine", "Glue"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Résine", "Moon"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Sève", "Dante"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BAD"),
            ("ETE", "WORST"),
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Sève", "Enola"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
        },
        ("Sève", "Redhot"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Sève", "Silverweed"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Sève", "Visc"): {
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
        },
        ("Écorce", "Adriel"): {
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
        },
        ("Écorce", "Beckers"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Écorce", "Mitexi"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
        },
        ("Écorce", "Oath"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Écorce", "Perfling"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
    },
    "Terre de la Continuité": {
        ("Ambres", "Beng"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
        },
        ("Ambres", "Hash"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
        ("Ambres", "Pha"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Ambres", "Sha"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Ambres", "Soo"): {
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
        },
        ("Ambres", "Zun"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BAD"),
            ("ETE", "WORST"),
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Bois", "Abhaya"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
        },
        ("Bois", "Kachine"): {
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
        },
        ("Bois", "Motega"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BAD"),
            ("ETE", "WORST"),
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Bois", "Tama"): {
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
        },
        ("Boucles", "Nita"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
        ("Boucles", "Patee"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Boucles", "Scrath"): {
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
        },
        ("Boucles", "Tansy"): {
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Boucles", "Yana"): {
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Carapace", "Big"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
        ("Carapace", "Cuty"): {
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
        },
        ("Carapace", "Horny"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Carapace", "Smart"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Carapace", "Splinter"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Fibres", "Anete"): {
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Fibres", "Buo"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Fibres", "Dzao"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
        },
        ("Fibres", "Shu"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Graines", "Caprice"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Graines", "Sarina"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
        ("Graines", "Saurona"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
        },
        ("Graines", "Silvio"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Huile", "Gulatch"): {
            ("ETE", "BAD"),
            ("ETE", "BEST"),
        },
        ("Huile", "Irin"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Huile", "Koorin"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Huile", "Pilan"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BAD"),
            ("ETE", "WORST"),
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Résine", "Dung"): {
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
        },
        ("Résine", "Fung"): {
            ("ETE", "BAD"),
            ("ETE", "WORST"),
        },
        ("Résine", "Glue"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Résine", "Moon"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Sève", "Dante"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BAD"),
            ("ETE", "WORST"),
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Sève", "Enola"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Sève", "Redhot"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
        },
        ("Sève", "Silverweed"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
        },
        ("Sève", "Visc"): {
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Écorce", "Adriel"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Écorce", "Beckers"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Écorce", "Mitexi"): {
            ("ETE", "BAD"),
            ("ETE", "WORST"),
        },
        ("Écorce", "Oath"): {
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
        },
        ("Écorce", "Perfling"): {
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
    },
    "Cité Engloutie": {
        ("Ambres", "Beng"): {
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
        },
        ("Ambres", "Hash"): {
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
        },
        ("Ambres", "Pha"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Ambres", "Sha"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
        },
        ("Ambres", "Soo"): {
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Ambres", "Zun"): {
            ("ETE", "BAD"),
            ("ETE", "WORST"),
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
        },
        ("Bois", "Abhaya"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Bois", "Eyota"): {
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Bois", "Kachine"): {
            ("ETE", "BEST"),
            ("ETE", "WORST"),
        },
        ("Bois", "Motega"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BAD"),
            ("ETE", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Bois", "Tama"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
        },
        ("Boucles", "Nita"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
        ("Boucles", "Patee"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Boucles", "Scrath"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Boucles", "Tansy"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BAD"),
            ("ETE", "WORST"),
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Boucles", "Yana"): {
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Carapace", "Big"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
        ("Carapace", "Cuty"): {
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Carapace", "Horny"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Carapace", "Smart"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Carapace", "Splinter"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Fibres", "Anete"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Fibres", "Buo"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BAD"),
            ("ETE", "WORST"),
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Fibres", "Dzao"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
        ("Fibres", "Shu"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Graines", "Caprice"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Graines", "Sarina"): {
            ("ETE", "BEST"),
            ("ETE", "WORST"),
        },
        ("Graines", "Saurona"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Graines", "Silvio"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Huile", "Gulatch"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Huile", "Irin"): {
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
        },
        ("Huile", "Koorin"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Huile", "Pilan"): {
            ("ETE", "BAD"),
            ("ETE", "WORST"),
        },
        ("Résine", "Dung"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Résine", "Fung"): {
            ("ETE", "BAD"),
            ("ETE", "WORST"),
        },
        ("Résine", "Glue"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
        },
        ("Résine", "Moon"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Sève", "Dante"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BAD"),
            ("ETE", "WORST"),
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Sève", "Enola"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
        },
        ("Sève", "Redhot"): {
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Sève", "Silverweed"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
        },
        ("Sève", "Visc"): {
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
        },
        ("Écorce", "Adriel"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Écorce", "Beckers"): {
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Écorce", "Mitexi"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BAD"),
            ("ETE", "WORST"),
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Écorce", "Oath"): {
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Écorce", "Perfling"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
        },
    },
    "Profondeurs Interdites": {
        ("Ambres", "Beng"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Ambres", "Hash"): {
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
        ("Ambres", "Pha"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Ambres", "Sha"): {
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
        },
        ("Ambres", "Soo"): {
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
        },
        ("Ambres", "Zun"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Bois", "Abhaya"): {
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Bois", "Eyota"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Bois", "Kachine"): {
            ("ETE", "BEST"),
            ("ETE", "WORST"),
        },
        ("Bois", "Motega"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Bois", "Tama"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
        },
        ("Boucles", "Nita"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
        ("Boucles", "Patee"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Boucles", "Scrath"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Boucles", "Tansy"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BAD"),
            ("ETE", "WORST"),
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Boucles", "Yana"): {
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Carapace", "Big"): {
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
        },
        ("Carapace", "Cuty"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Carapace", "Horny"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Carapace", "Smart"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Carapace", "Splinter"): {
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Fibres", "Anete"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Fibres", "Buo"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BAD"),
            ("ETE", "WORST"),
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Fibres", "Dzao"): {
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
        ("Fibres", "Shu"): {
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Graines", "Caprice"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
        },
        ("Graines", "Sarina"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
        ("Graines", "Saurona"): {
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
        },
        ("Graines", "Silvio"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Huile", "Gulatch"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Huile", "Irin"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Huile", "Koorin"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Huile", "Pilan"): {
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
        },
        ("Résine", "Dung"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Résine", "Fung"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BAD"),
            ("ETE", "WORST"),
        },
        ("Résine", "Glue"): {
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
        },
        ("Résine", "Moon"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Sève", "Dante"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BAD"),
            ("ETE", "WORST"),
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Sève", "Enola"): {
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Sève", "Redhot"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
        },
        ("Sève", "Silverweed"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Sève", "Visc"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
        },
        ("Écorce", "Adriel"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Écorce", "Beckers"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Écorce", "Mitexi"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BAD"),
            ("ETE", "WORST"),
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Écorce", "Oath"): {
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
        },
        ("Écorce", "Perfling"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
    },
}

#: {zone: {(famille, matière): {(saison, condition)}}} — l'excellente.
#:
#: Armory ne range pas les excellentes par zone : elles valent pour
#: les quatre, restreintes aux matières que la zone porte.
EXCELLENTES = {
    "Sources Interdites": {
        ("Ambres", "Beng"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
        },
        ("Ambres", "Hash"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
        },
        ("Ambres", "Pha"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
        },
        ("Ambres", "Sha"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
        },
        ("Ambres", "Soo"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
        },
        ("Ambres", "Zun"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BAD"),
            ("ETE", "WORST"),
        },
        ("Bois", "Abhaya"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
        },
        ("Bois", "Eyota"): {
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Bois", "Kachine"): {
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
        ("Bois", "Motega"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
        },
        ("Bois", "Tama"): {
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Boucles", "Nita"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BEST"),
            ("ETE", "WORST"),
        },
        ("Boucles", "Patee"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
        },
        ("Boucles", "Scrath"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
        },
        ("Boucles", "Tansy"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Boucles", "Yana"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("ETE", "BAD"),
            ("ETE", "BEST"),
        },
        ("Carapace", "Big"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
        ("Carapace", "Cuty"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Carapace", "Horny"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Carapace", "Smart"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Carapace", "Splinter"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Fibres", "Anete"): {
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Fibres", "Buo"): {
            ("ETE", "BAD"),
            ("ETE", "WORST"),
        },
        ("Fibres", "Dzao"): {
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
        ("Fibres", "Shu"): {
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Graines", "Caprice"): {
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
        },
        ("Graines", "Sarina"): {
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
        },
        ("Graines", "Saurona"): {
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
        },
        ("Graines", "Silvio"): {
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
        },
        ("Huile", "Gulatch"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
        },
        ("Huile", "Irin"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
        },
        ("Huile", "Koorin"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
        },
        ("Huile", "Pilan"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
        },
        ("Résine", "Dung"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Résine", "Fung"): {
            ("ETE", "BAD"),
            ("ETE", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Résine", "Glue"): {
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Résine", "Moon"): {
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Sève", "Dante"): {
            ("ETE", "BAD"),
            ("ETE", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Sève", "Enola"): {
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Sève", "Redhot"): {
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Sève", "Silverweed"): {
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Sève", "Visc"): {
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Écorce", "Adriel"): {
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
        },
        ("Écorce", "Beckers"): {
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Écorce", "Mitexi"): {
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Écorce", "Oath"): {
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
        },
        ("Écorce", "Perfling"): {
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
    },
    "Terre de la Continuité": {
        ("Ambres", "Beng"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
        },
        ("Ambres", "Hash"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
        },
        ("Ambres", "Pha"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
        },
        ("Ambres", "Sha"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
        },
        ("Ambres", "Soo"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
        },
        ("Ambres", "Zun"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BAD"),
            ("ETE", "WORST"),
        },
        ("Bois", "Abhaya"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
        },
        ("Bois", "Kachine"): {
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
        ("Bois", "Motega"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
        },
        ("Bois", "Tama"): {
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Boucles", "Nita"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BEST"),
            ("ETE", "WORST"),
        },
        ("Boucles", "Patee"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
        },
        ("Boucles", "Scrath"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
        },
        ("Boucles", "Tansy"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Boucles", "Yana"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("ETE", "BAD"),
            ("ETE", "BEST"),
        },
        ("Carapace", "Big"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
        ("Carapace", "Cuty"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Carapace", "Horny"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Carapace", "Smart"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Carapace", "Splinter"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Fibres", "Anete"): {
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Fibres", "Buo"): {
            ("ETE", "BAD"),
            ("ETE", "WORST"),
        },
        ("Fibres", "Dzao"): {
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
        ("Fibres", "Shu"): {
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Graines", "Caprice"): {
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
        },
        ("Graines", "Sarina"): {
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
        },
        ("Graines", "Saurona"): {
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
        },
        ("Graines", "Silvio"): {
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
        },
        ("Huile", "Gulatch"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
        },
        ("Huile", "Irin"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
        },
        ("Huile", "Koorin"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
        },
        ("Huile", "Pilan"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
        },
        ("Résine", "Dung"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Résine", "Fung"): {
            ("ETE", "BAD"),
            ("ETE", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Résine", "Glue"): {
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Résine", "Moon"): {
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Sève", "Dante"): {
            ("ETE", "BAD"),
            ("ETE", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Sève", "Enola"): {
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Sève", "Redhot"): {
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Sève", "Silverweed"): {
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Sève", "Visc"): {
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Écorce", "Adriel"): {
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
        },
        ("Écorce", "Beckers"): {
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Écorce", "Mitexi"): {
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Écorce", "Oath"): {
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
        },
        ("Écorce", "Perfling"): {
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
    },
    "Cité Engloutie": {
        ("Ambres", "Beng"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
        },
        ("Ambres", "Hash"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
        },
        ("Ambres", "Pha"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
        },
        ("Ambres", "Sha"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
        },
        ("Ambres", "Soo"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
        },
        ("Ambres", "Zun"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BAD"),
            ("ETE", "WORST"),
        },
        ("Bois", "Abhaya"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
        },
        ("Bois", "Eyota"): {
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Bois", "Kachine"): {
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
        ("Bois", "Motega"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
        },
        ("Bois", "Tama"): {
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Boucles", "Nita"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BEST"),
            ("ETE", "WORST"),
        },
        ("Boucles", "Patee"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
        },
        ("Boucles", "Scrath"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
        },
        ("Boucles", "Tansy"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Boucles", "Yana"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("ETE", "BAD"),
            ("ETE", "BEST"),
        },
        ("Carapace", "Big"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
        ("Carapace", "Cuty"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Carapace", "Horny"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Carapace", "Smart"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Carapace", "Splinter"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Fibres", "Anete"): {
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Fibres", "Buo"): {
            ("ETE", "BAD"),
            ("ETE", "WORST"),
        },
        ("Fibres", "Dzao"): {
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
        ("Fibres", "Shu"): {
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Graines", "Caprice"): {
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
        },
        ("Graines", "Sarina"): {
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
        },
        ("Graines", "Saurona"): {
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
        },
        ("Graines", "Silvio"): {
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
        },
        ("Huile", "Gulatch"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
        },
        ("Huile", "Irin"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
        },
        ("Huile", "Koorin"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
        },
        ("Huile", "Pilan"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
        },
        ("Résine", "Dung"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Résine", "Fung"): {
            ("ETE", "BAD"),
            ("ETE", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Résine", "Glue"): {
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Résine", "Moon"): {
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Sève", "Dante"): {
            ("ETE", "BAD"),
            ("ETE", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Sève", "Enola"): {
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Sève", "Redhot"): {
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Sève", "Silverweed"): {
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Sève", "Visc"): {
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Écorce", "Adriel"): {
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
        },
        ("Écorce", "Beckers"): {
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Écorce", "Mitexi"): {
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Écorce", "Oath"): {
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
        },
        ("Écorce", "Perfling"): {
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
    },
    "Profondeurs Interdites": {
        ("Ambres", "Beng"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
        },
        ("Ambres", "Hash"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
        },
        ("Ambres", "Pha"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
        },
        ("Ambres", "Sha"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
        },
        ("Ambres", "Soo"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
        },
        ("Ambres", "Zun"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BAD"),
            ("ETE", "WORST"),
        },
        ("Bois", "Abhaya"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
        },
        ("Bois", "Eyota"): {
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Bois", "Kachine"): {
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
        ("Bois", "Motega"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
        },
        ("Bois", "Tama"): {
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Boucles", "Nita"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("ETE", "BEST"),
            ("ETE", "WORST"),
        },
        ("Boucles", "Patee"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
        },
        ("Boucles", "Scrath"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
        },
        ("Boucles", "Tansy"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Boucles", "Yana"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("ETE", "BAD"),
            ("ETE", "BEST"),
        },
        ("Carapace", "Big"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
        ("Carapace", "Cuty"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Carapace", "Horny"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Carapace", "Smart"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Carapace", "Splinter"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Fibres", "Anete"): {
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Fibres", "Buo"): {
            ("ETE", "BAD"),
            ("ETE", "WORST"),
        },
        ("Fibres", "Dzao"): {
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
        ("Fibres", "Shu"): {
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Graines", "Caprice"): {
            ("ETE", "BAD"),
            ("ETE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
        },
        ("Graines", "Sarina"): {
            ("ETE", "BEST"),
            ("ETE", "WORST"),
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
        },
        ("Graines", "Saurona"): {
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
        },
        ("Graines", "Silvio"): {
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
        },
        ("Huile", "Gulatch"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "BEST"),
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
        },
        ("Huile", "Irin"): {
            ("AUTOMNE", "GOOD"),
            ("AUTOMNE", "WORST"),
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
        },
        ("Huile", "Koorin"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "GOOD"),
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
        },
        ("Huile", "Pilan"): {
            ("AUTOMNE", "BAD"),
            ("AUTOMNE", "WORST"),
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
        },
        ("Résine", "Dung"): {
            ("AUTOMNE", "BEST"),
            ("AUTOMNE", "GOOD"),
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Résine", "Fung"): {
            ("ETE", "BAD"),
            ("ETE", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Résine", "Glue"): {
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Résine", "Moon"): {
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Sève", "Dante"): {
            ("ETE", "BAD"),
            ("ETE", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Sève", "Enola"): {
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Sève", "Redhot"): {
            ("ETE", "BAD"),
            ("ETE", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Sève", "Silverweed"): {
            ("HIVER", "BAD"),
            ("HIVER", "BEST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "BEST"),
        },
        ("Sève", "Visc"): {
            ("ETE", "GOOD"),
            ("ETE", "WORST"),
            ("PRINTEMPS", "GOOD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Écorce", "Adriel"): {
            ("ETE", "BEST"),
            ("ETE", "GOOD"),
            ("HIVER", "BEST"),
            ("HIVER", "GOOD"),
        },
        ("Écorce", "Beckers"): {
            ("HIVER", "BAD"),
            ("HIVER", "GOOD"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "GOOD"),
        },
        ("Écorce", "Mitexi"): {
            ("HIVER", "BAD"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BAD"),
            ("PRINTEMPS", "WORST"),
        },
        ("Écorce", "Oath"): {
            ("HIVER", "GOOD"),
            ("HIVER", "WORST"),
        },
        ("Écorce", "Perfling"): {
            ("HIVER", "BEST"),
            ("HIVER", "WORST"),
            ("PRINTEMPS", "BEST"),
            ("PRINTEMPS", "WORST"),
        },
    },
}

#: {zone: {(famille, matière): {(saison, condition)}}} — le choix.
#:
#: Vide, et volontairement : aucune source ne le suit.
CHOIX = {
    "Sources Interdites": {
    },
    "Terre de la Continuité": {
    },
    "Cité Engloutie": {
    },
    "Profondeurs Interdites": {
    },
}

#: {(famille, matière): {(saison, condition)}} — les excellentes des
#: **continents**, qui ne parlent pas des Primes.
#:
#: Le tutoriel écrit que ce pop est identique sur tous les continents,
#: et les gisements correspondants sont au Gouffre d'Ichor ou à la
#: Porte des Vents. Deux saisons, deux conditions par matière.
EXCELLENTES_CONTINENTS = {
    ("Ambres", "Beng"): {
        ("AUTOMNE", "BAD"),
        ("AUTOMNE", "GOOD"),
        ("HIVER", "BAD"),
        ("HIVER", "GOOD"),
    },
    ("Ambres", "Hash"): {
        ("AUTOMNE", "BEST"),
        ("AUTOMNE", "WORST"),
        ("HIVER", "BEST"),
        ("HIVER", "WORST"),
    },
    ("Ambres", "Pha"): {
        ("AUTOMNE", "GOOD"),
        ("AUTOMNE", "WORST"),
        ("ETE", "GOOD"),
        ("ETE", "WORST"),
    },
    ("Ambres", "Sha"): {
        ("AUTOMNE", "BEST"),
        ("AUTOMNE", "GOOD"),
        ("HIVER", "BEST"),
        ("HIVER", "GOOD"),
    },
    ("Ambres", "Soo"): {
        ("AUTOMNE", "BAD"),
        ("AUTOMNE", "BEST"),
        ("HIVER", "BAD"),
        ("HIVER", "BEST"),
    },
    ("Ambres", "Zun"): {
        ("AUTOMNE", "BAD"),
        ("AUTOMNE", "WORST"),
        ("ETE", "BAD"),
        ("ETE", "WORST"),
    },
    ("Bois", "Abhaya"): {
        ("AUTOMNE", "GOOD"),
        ("AUTOMNE", "WORST"),
        ("HIVER", "GOOD"),
        ("HIVER", "WORST"),
    },
    ("Bois", "Eyota"): {
        ("ETE", "BEST"),
        ("ETE", "GOOD"),
        ("PRINTEMPS", "BEST"),
        ("PRINTEMPS", "GOOD"),
    },
    ("Bois", "Kachine"): {
        ("ETE", "BEST"),
        ("ETE", "WORST"),
        ("PRINTEMPS", "BEST"),
        ("PRINTEMPS", "WORST"),
    },
    ("Bois", "Motega"): {
        ("AUTOMNE", "BAD"),
        ("AUTOMNE", "WORST"),
        ("HIVER", "BAD"),
        ("HIVER", "WORST"),
    },
    ("Bois", "Tama"): {
        ("ETE", "BAD"),
        ("ETE", "BEST"),
        ("PRINTEMPS", "BAD"),
        ("PRINTEMPS", "BEST"),
    },
    ("Boucles", "Nita"): {
        ("AUTOMNE", "BEST"),
        ("AUTOMNE", "WORST"),
        ("ETE", "BEST"),
        ("ETE", "WORST"),
    },
    ("Boucles", "Patee"): {
        ("AUTOMNE", "BEST"),
        ("AUTOMNE", "GOOD"),
        ("ETE", "BEST"),
        ("ETE", "GOOD"),
    },
    ("Boucles", "Scrath"): {
        ("AUTOMNE", "BAD"),
        ("AUTOMNE", "GOOD"),
        ("ETE", "BAD"),
        ("ETE", "GOOD"),
    },
    ("Boucles", "Tansy"): {
        ("AUTOMNE", "BAD"),
        ("AUTOMNE", "WORST"),
        ("PRINTEMPS", "BAD"),
        ("PRINTEMPS", "WORST"),
    },
    ("Boucles", "Yana"): {
        ("AUTOMNE", "BAD"),
        ("AUTOMNE", "BEST"),
        ("ETE", "BAD"),
        ("ETE", "BEST"),
    },
    ("Carapace", "Big"): {
        ("AUTOMNE", "BEST"),
        ("AUTOMNE", "WORST"),
        ("PRINTEMPS", "BEST"),
        ("PRINTEMPS", "WORST"),
    },
    ("Carapace", "Cuty"): {
        ("AUTOMNE", "BAD"),
        ("AUTOMNE", "GOOD"),
        ("PRINTEMPS", "BAD"),
        ("PRINTEMPS", "GOOD"),
    },
    ("Carapace", "Horny"): {
        ("AUTOMNE", "BEST"),
        ("AUTOMNE", "GOOD"),
        ("PRINTEMPS", "BEST"),
        ("PRINTEMPS", "GOOD"),
    },
    ("Carapace", "Smart"): {
        ("AUTOMNE", "BAD"),
        ("AUTOMNE", "BEST"),
        ("PRINTEMPS", "BAD"),
        ("PRINTEMPS", "BEST"),
    },
    ("Carapace", "Splinter"): {
        ("AUTOMNE", "GOOD"),
        ("AUTOMNE", "WORST"),
        ("PRINTEMPS", "GOOD"),
        ("PRINTEMPS", "WORST"),
    },
    ("Fibres", "Anete"): {
        ("ETE", "BAD"),
        ("ETE", "BEST"),
        ("PRINTEMPS", "BAD"),
        ("PRINTEMPS", "BEST"),
    },
    ("Fibres", "Buo"): {
        ("ETE", "BAD"),
        ("ETE", "WORST"),
        ("HIVER", "BAD"),
        ("HIVER", "WORST"),
    },
    ("Fibres", "Dzao"): {
        ("ETE", "BEST"),
        ("ETE", "WORST"),
        ("PRINTEMPS", "BEST"),
        ("PRINTEMPS", "WORST"),
    },
    ("Fibres", "Shu"): {
        ("ETE", "BEST"),
        ("ETE", "GOOD"),
        ("PRINTEMPS", "BEST"),
        ("PRINTEMPS", "GOOD"),
    },
    ("Graines", "Caprice"): {
        ("ETE", "BAD"),
        ("ETE", "BEST"),
        ("HIVER", "BAD"),
        ("HIVER", "BEST"),
    },
    ("Graines", "Sarina"): {
        ("ETE", "BEST"),
        ("ETE", "WORST"),
        ("HIVER", "BEST"),
        ("HIVER", "WORST"),
    },
    ("Graines", "Saurona"): {
        ("ETE", "BAD"),
        ("ETE", "GOOD"),
        ("HIVER", "BAD"),
        ("HIVER", "GOOD"),
    },
    ("Graines", "Silvio"): {
        ("ETE", "GOOD"),
        ("ETE", "WORST"),
        ("HIVER", "GOOD"),
        ("HIVER", "WORST"),
    },
    ("Huile", "Gulatch"): {
        ("AUTOMNE", "BAD"),
        ("AUTOMNE", "BEST"),
        ("HIVER", "BAD"),
        ("HIVER", "BEST"),
    },
    ("Huile", "Irin"): {
        ("AUTOMNE", "GOOD"),
        ("AUTOMNE", "WORST"),
        ("HIVER", "GOOD"),
        ("HIVER", "WORST"),
    },
    ("Huile", "Koorin"): {
        ("AUTOMNE", "BAD"),
        ("AUTOMNE", "GOOD"),
        ("HIVER", "BAD"),
        ("HIVER", "GOOD"),
    },
    ("Huile", "Pilan"): {
        ("AUTOMNE", "BAD"),
        ("AUTOMNE", "WORST"),
        ("HIVER", "BAD"),
        ("HIVER", "WORST"),
    },
    ("Résine", "Dung"): {
        ("AUTOMNE", "BEST"),
        ("AUTOMNE", "GOOD"),
        ("HIVER", "BEST"),
        ("HIVER", "GOOD"),
    },
    ("Résine", "Fung"): {
        ("ETE", "BAD"),
        ("ETE", "WORST"),
        ("PRINTEMPS", "BAD"),
        ("PRINTEMPS", "WORST"),
    },
    ("Résine", "Glue"): {
        ("ETE", "BAD"),
        ("ETE", "GOOD"),
        ("PRINTEMPS", "BAD"),
        ("PRINTEMPS", "GOOD"),
    },
    ("Résine", "Moon"): {
        ("ETE", "GOOD"),
        ("ETE", "WORST"),
        ("PRINTEMPS", "GOOD"),
        ("PRINTEMPS", "WORST"),
    },
    ("Sève", "Dante"): {
        ("ETE", "BAD"),
        ("ETE", "WORST"),
        ("PRINTEMPS", "BAD"),
        ("PRINTEMPS", "WORST"),
    },
    ("Sève", "Enola"): {
        ("HIVER", "BEST"),
        ("HIVER", "GOOD"),
        ("PRINTEMPS", "BEST"),
        ("PRINTEMPS", "GOOD"),
    },
    ("Sève", "Redhot"): {
        ("ETE", "BAD"),
        ("ETE", "GOOD"),
        ("PRINTEMPS", "BAD"),
        ("PRINTEMPS", "GOOD"),
    },
    ("Sève", "Silverweed"): {
        ("HIVER", "BAD"),
        ("HIVER", "BEST"),
        ("PRINTEMPS", "BAD"),
        ("PRINTEMPS", "BEST"),
    },
    ("Sève", "Visc"): {
        ("ETE", "GOOD"),
        ("ETE", "WORST"),
        ("PRINTEMPS", "GOOD"),
        ("PRINTEMPS", "WORST"),
    },
    ("Écorce", "Adriel"): {
        ("HIVER", "BEST"),
        ("HIVER", "GOOD"),
        ("PRINTEMPS", "BEST"),
        ("PRINTEMPS", "GOOD"),
    },
    ("Écorce", "Beckers"): {
        ("HIVER", "BAD"),
        ("HIVER", "GOOD"),
        ("PRINTEMPS", "BAD"),
        ("PRINTEMPS", "GOOD"),
    },
    ("Écorce", "Mitexi"): {
        ("HIVER", "BAD"),
        ("HIVER", "WORST"),
        ("PRINTEMPS", "BAD"),
        ("PRINTEMPS", "WORST"),
    },
    ("Écorce", "Oath"): {
        ("HIVER", "GOOD"),
        ("HIVER", "WORST"),
        ("PRINTEMPS", "GOOD"),
        ("PRINTEMPS", "WORST"),
    },
    ("Écorce", "Perfling"): {
        ("HIVER", "BEST"),
        ("HIVER", "WORST"),
        ("PRINTEMPS", "BEST"),
        ("PRINTEMPS", "WORST"),
    },
}
