"""Ce qui peut apparaître, par saison, par zone et par condition météo.

Fichier produit par ../zyroom-android/outils/table_pop.py — ne pas
modifier à la main.

Le relevé est celui de La Lune Eternelle, et c'est la seule source connue
pour cette correspondance : les sites publics disent quelles matières sont
suprêmes à une saison, jamais dans quelle météo elles sortent.

Il est **incomplet par construction** — il se remplit au fil des sorties
des joueurs. Une case vide veut donc dire « pas encore relevé », et non
« rien ».
"""

#: {saison: {zone: {condition: {famille: [matières]}}}}
POP = {
    "PRINTEMPS": {
        "Sources Interdites": {
            "WORST": {
                "Ambres": ["Beng", "Pha", "Sha", "Zun"],
                "Graines": ["Caprice", "Silvio"],
                "Fibres": ["Anète", "Buo"],
                "Résine": ["Dung", "Colle", "Lune"],
                "Huile": ["Gulatch", "Irin", "Pilan"],
                "Sève": ["Dante", "Ardente", "Silverweed"],
                "Carapace": ["Mignonne", "Inteligente"],
                "Écorce": ["Beckers", "Oath", "Perfling"],
                "Bois": ["Eyota", "Kachine", "Tama"],
                "Boucles": ["Nita", "Patee", "Scratch", "Yana"],
            },
            "BAD": {
                "Ambres": ["Soo", "Hash"],
                "Écorce": ["Adriel"],
                "Boucles": ["Tansy"],
            },
            "GOOD": {
                "Graines": ["Saurona", "Sarina"],
                "Carapace": ["Splinter", "Cornée"],
                "Résine": ["Fung"],
                "Huile": ["Enola", "Koorin"],
                "Bois": ["Motega"],
                "Fibres": ["Dzao"],
                "Sève": ["Visc"],
            },
            "BEST": {
                "Carapace": ["Grosse"],
                "Fibres": ["Shu"],
                "Bois": ["Abhaya"],
                "Écorce": ["Mitexi"],
            },
        },
        "Terre de la Continuité": {
            "WORST": {
                "Ambres": ["Hash", "Pha", "Sha", "Zun"],
                "Graines": ["Caprice", "Sarina", "Silvio"],
                "Fibres": ["Shu"],
                "Résine": ["Colle", "Lune"],
                "Huile": ["Irin", "Koorin", "Pilan"],
                "Sève": ["Dante", "Enola"],
                "Carapace": ["Grosse", "Cornée", "Inteligente", "Splinter"],
                "Écorce": ["Adriel", "Beckers"],
                "Bois": ["Motega"],
                "Boucles": ["Nita", "Patee", "Scratch"],
            },
            "BAD": {
                "Écorce": ["Perfling"],
                "Bois": ["Eyota"],
                "Carapace": ["Mignonne"],
            },
            "GOOD": {
                "Boucles": ["Tansy", "Yana"],
                "Résine": ["Fung"],
                "Huile": ["Gulatch"],
                "Sève": ["Ardente", "Silverweed"],
                "Bois": ["Abhaya", "Tama"],
                "Ambres": ["Soo"],
            },
            "BEST": {
                "Fibres": ["Anète", "Buo", "Dzao"],
                "Sève": ["Visc"],
                "Écorce": ["Oath"],
                "Graines": ["Saurona"],
                "Bois": ["Kachine"],
                "Ambres": ["Beng"],
                "Résine": ["Dung"],
                "Boucles": ["Scratch"],
            },
        },
        "Cité Engloutie": {
            "WORST": {
                "Ambres": ["Pha"],
                "Graines": ["Caprice", "Saurona", "Silvio"],
                "Fibres": ["Anète", "Buo", "Dzao", "Shu"],
                "Résine": ["Dung", "Colle", "Lune"],
                "Huile": ["Gulatch", "Koorin"],
                "Sève": ["Dante"],
                "Carapace": ["Grosse", "Cornée", "Inteligente", "Splinter"],
                "Écorce": ["Adriel", "Beckers", "Mitexi"],
                "Bois": ["Abhaya", "Tama"],
                "Boucles": ["Nita", "Patee", "Scratch", "Tansy"],
            },
            "BAD": {
                "Bois": ["Eyota", "Kachine"],
                "Boucles": ["Yana ?"],
                "Graines": ["Sarina"],
                "Huile": ["Irin"],
            },
            "GOOD": {
                "Carapace": ["Mignonne"],
                "Boucles": ["Yana ?"],
                "Résine": ["Fung"],
                "Huile": ["Pilan"],
                "Sève": ["Enola", "Visc agro KKT"],
                "Ambres": ["Beng"],
            },
            "BEST": {
                "Ambres": ["Soo", "Hash", "Zun", "Sha"],
                "Sève": ["Ardente", "Silverweed"],
                "Écorce": ["Oath", "Perfling"],
                "Bois": ["Motega"],
            },
        },
        "Profondeurs Interdites": {
            "WORST": {
                "Ambres": ["Beng Agro", "Pha"],
                "Graines": ["Sarina", "Silvio"],
                "Fibres": ["Anète", "Buo"],
                "Résine": ["Dung", "Lune"],
                "Huile": ["Gulatch", "Irin", "Koorin"],
                "Sève": ["Dante", "Silverweed"],
                "Carapace": ["Mignonne", "Cornée", "Inteligente"],
                "Écorce": ["Adriel", "Mitexi", "Perfling"],
                "Bois": ["Tama"],
                "Boucles": ["Nita", "Patee", "Scratch", "Tansy"],
            },
            "BAD": {
                "Ambres": ["Hash"],
                "Sève": ["Enola", "Ardente ?"],
                "Écorce": ["Oath"],
                "Bois": ["Kachine"],
                "Huile": ["Pilan"],
                "Carapace": ["Grosse"],
            },
            "GOOD": {
                "Carapace": ["Splinter"],
                "Boucles": ["Yana"],
                "Résine": ["Fung", "Colle"],
                "Sève": ["Ardente ?", "Visc"],
                "Bois": ["Motega", "Abhaya"],
                "Ambres": ["Soo"],
            },
            "BEST": {
                "Ambres": ["Sha", "Zun"],
                "Fibres": ["Dzao", "Shu"],
                "Écorce": ["Beckers"],
                "Graines": ["Saurona", "Caprice"],
                "Bois": ["Eyota"],
                "Sève": ["Ardente ?"],
            },
        },
    },
    "ETE": {
        "Sources Interdites": {
            "WORST": {
                "Ambres": ["Beng", "Pha", "Sha", "Zun"],
                "Graines": ["Caprice", "Silvio"],
                "Fibres": ["Anète", "Buo"],
                "Résine": ["Dung", "Colle", "Lune"],
                "Huile": ["Gulatch", "Irin", "Pilan"],
                "Sève": ["Dante", "Ardente", "Silverweed"],
                "Carapace": ["Mignonne", "Inteligente"],
                "Écorce": ["Beckers", "Oath", "Perfling"],
                "Bois": ["Eyota", "Kachine", "Tama"],
                "Boucles": ["Nita", "Patee", "Scratch", "Yana"],
            },
            "BAD": {
                "Ambres": ["Hash"],
                "Écorce": ["Adriel"],
                "Boucles": ["Tansy"],
            },
            "GOOD": {
                "Graines": ["Sarina"],
                "Carapace": ["Cornée"],
                "Résine": ["Fung"],
                "Huile": ["Enola"],
                "Bois": ["Motega"],
            },
            "BEST": {
                "Fibres": ["Shu"],
                "Bois": ["Abhaya"],
                "Carapace": ["Grosse"],
                "Écorce": ["Mitexi"],
            },
        },
        "Terre de la Continuité": {
            "WORST": {
                "Ambres": ["Hash", "Pha", "Sha", "Zun"],
                "Graines": ["Caprice", "Sarina", "Silvio"],
                "Fibres": ["Shu"],
                "Résine": ["Colle", "Lune"],
                "Huile": ["Irin", "Koorin", "Pilan"],
                "Sève": ["Dante", "Enola"],
                "Carapace": ["Grosse", "Cornée", "Inteligente", "Splinter"],
                "Écorce": ["Adriel", "Beckers"],
                "Bois": ["Motega"],
                "Boucles": ["Nita", "Patee", "Scratch"],
            },
            "BAD": {
                "Bois": ["Eyota"],
                "Carapace": ["Migno Omg AGGRO"],
                "Écorce": ["Perfling"],
            },
            "GOOD": {
                "Résine": ["Fung"],
                "Huile": ["Gulatch"],
                "Sève": ["Ardente", "Silverweed"],
                "Bois": ["Abhaya", "Tama"],
                "Ambres": ["Soo"],
                "Boucles": ["Tansy", "Yana"],
            },
            "BEST": {
                "Graines": ["Saurona"],
                "Fibres": ["Anète", "Dzao", "Buo"],
                "Bois": ["Kachine"],
                "Ambres": ["Beng"],
                "Résine": ["Dung"],
                "Sève": ["Visc"],
                "Boucles": ["Scratch"],
                "Écorce": ["Oath"],
            },
        },
        "Cité Engloutie": {
            "WORST": {
                "Ambres": ["Pha"],
                "Graines": ["Caprice", "Saurona", "Silvio"],
                "Fibres": ["Anète", "Buo", "Dzao", "Shu"],
                "Résine": ["Dung", "Colle", "Lune"],
                "Huile": ["Gulatch", "Koorin"],
                "Sève": ["Dante"],
                "Carapace": ["Grosse", "Cornée", "Inteligente", "Splinter"],
                "Écorce": ["Adriel", "Beckers", "Mitexi"],
                "Bois": ["Abhaya", "Tama"],
                "Boucles": ["Nita", "Patee", "Scratch", "Tansy"],
            },
            "BAD": {
                "Graines": ["Sarina"],
                "Bois": ["Kachine", "Eyota"],
                "Huile": ["Irin"],
                "Boucles": ["Yana ?"],
            },
            "GOOD": {
                "Résine": ["Fung"],
                "Huile": ["Pilan"],
                "Sève": ["Enola", "Visc agro KKT"],
                "Ambres": ["Beng"],
                "Carapace": ["Mignonne"],
                "Boucles": ["Yana ?"],
            },
            "BEST": {
                "Ambres": ["Hash", "Soo", "Zun", "Sha"],
                "Sève": ["Ardente", "Silverweed"],
                "Écorce": ["Oath", "Perfling"],
                "Bois": ["Motega"],
            },
        },
        "Profondeurs Interdites": {
            "WORST": {
                "Ambres": ["Beng", "Pha"],
                "Graines": ["Sarina", "Silvio"],
                "Fibres": ["Anète", "Buo"],
                "Résine": ["Dung", "Lune"],
                "Huile": ["Gulatch", "Irin", "Koorin"],
                "Sève": ["Dante", "Silverweed"],
                "Carapace": ["Mignonne", "Cornée", "Inteligente"],
                "Écorce": ["Adriel", "Mitexi", "Perfling"],
                "Bois": ["Tama"],
                "Boucles": ["Nita", "Patee", "Scratch", "Tansy"],
            },
            "BAD": {
                "Écorce": ["Oath"],
                "Bois": ["Kachine"],
                "Sève": ["Ardente", "Enola"],
                "Huile": ["Pilan"],
                "Carapace": ["Grosse"],
                "Ambres": ["Hash"],
            },
            "GOOD": {
                "Résine": ["Fung", "Colle"],
                "Bois": ["Motega", "Abhaya"],
                "Sève": ["Visc"],
                "Ambres": ["Soo"],
                "Carapace": ["Splinter"],
                "Boucles": ["Yana"],
            },
            "BEST": {
                "Ambres": ["Sha", "Zun"],
                "Graines": ["Saurona", "Caprice"],
                "Fibres": ["Shu", "Dzao"],
                "Bois": ["Eyota"],
                "Écorce": ["Beckers"],
            },
        },
    },
    "AUTOMNE": {
        "Sources Interdites": {
            "WORST": {
                "Ambres": ["Beng", "Pha", "Sha", "Zun"],
                "Graines": ["Caprice", "Silvio"],
                "Fibres": ["Anète", "Buo"],
                "Résine": ["Dung", "Colle", "Lune"],
                "Huile": ["Gulatch", "Irin", "Pilan"],
                "Sève": ["Dante", "Redhot", "Silverweed"],
                "Carapace": ["Mignonne", "Inteligente"],
                "Écorce": ["Beckers", "Oath", "Perfling"],
                "Bois": ["Eyota", "Kachine", "Tama"],
                "Boucles": ["Nita", "Patee", "Scratch", "Yana"],
            },
            "BAD": {
                "Boucles": ["Tansy"],
                "Ambres": ["Soo", "Hash"],
                "Écorce": ["Adriel"],
            },
            "GOOD": {
                "Résine": ["Fung"],
                "Huile": ["Enola", "Koorin"],
                "Bois": ["Motega"],
                "Fibres": ["Dzao"],
                "Sève": ["Visc"],
                "Graines": ["Saurona", "Sarina"],
                "Carapace": ["Splinter", "Cornée"],
            },
            "BEST": {
                "Carapace": ["Grosse"],
                "Écorce": ["Mitexi"],
                "Bois": ["Abhaya"],
                "Fibres": ["Shu"],
            },
        },
        "Terre de la Continuité": {
            "WORST": {
                "Ambres": ["Hash", "Pha", "Sha", "Zun"],
                "Graines": ["Caprice", "Sarina", "Silvio"],
                "Fibres": ["Shu"],
                "Résine": ["Colle", "Lune"],
                "Huile": ["Irin", "Koorin", "Pilan"],
                "Sève": ["Dante", "Enola"],
                "Carapace": ["Grosse", "Cornée", "Inteligente", "Splinter"],
                "Écorce": ["Adriel", "Beckers"],
                "Bois": ["Motega"],
                "Boucles": ["Nita", "Patee", "Scratch"],
            },
            "BAD": {
                "Carapace": ["Mignonne"],
                "Écorce": ["Perfling"],
                "Bois": ["Eyota"],
            },
            "GOOD": {
                "Sève": ["Ardente", "Silverweed"],
                "Bois": ["Abhaya", "Tama"],
                "Ambres": ["Soo"],
                "Boucles": ["Tansy", "Yana"],
                "Résine": ["Fung"],
                "Huile": ["Gulatch"],
            },
            "BEST": {
                "Ambres": ["Beng"],
                "Graines": ["Saurona"],
                "Fibres": ["Dzao", "Buo", "Anète"],
                "Résine": ["Dung"],
                "Sève": ["Visc"],
                "Bois": ["Kachine"],
                "Boucles": ["Scratch"],
                "Écorce": ["Oath"],
            },
        },
        "Cité Engloutie": {
            "WORST": {
                "Ambres": ["Pha"],
                "Graines": ["Caprice", "Saurona", "Silvio"],
                "Fibres": ["Anète", "Buo", "Dzao", "Shu"],
                "Résine": ["Dung", "Colle", "Lune"],
                "Huile": ["Gulatch", "Koorin"],
                "Sève": ["Dante"],
                "Carapace": ["Grosse", "Cornée", "Inteligente", "Splinter"],
                "Écorce": ["Adriel", "Beckers", "Mitexi"],
                "Bois": ["Abhaya", "Tama"],
                "Boucles": ["Nita", "Patee", "Scratch", "Tansy"],
            },
            "BAD": {
                "Huile": ["Irin"],
                "Bois": ["Eyota", "Kachine"],
                "Boucles": ["Yana ?"],
                "Graines": ["Sarina"],
            },
            "GOOD": {
                "Sève": ["Enola", "Visc agro KKT"],
                "Ambres": ["Beng"],
                "Carapace": ["Mignonne"],
                "Boucles": ["Yana ?"],
                "Résine": ["Fung"],
                "Huile": ["Pilan"],
            },
            "BEST": {
                "Ambres": ["Sha", "Hash", "Zun", "Soo"],
                "Sève": ["Silverweed", "Ardente"],
                "Écorce": ["Perfling", "Oath"],
                "Bois": ["Motega"],
            },
        },
        "Profondeurs Interdites": {
            "WORST": {
                "Ambres": ["Beng", "Pha"],
                "Graines": ["Sarina", "Silvio"],
                "Fibres": ["Anète", "Buo"],
                "Résine": ["Dung", "Lune"],
                "Huile": ["Gulatch", "Irin", "Koorin"],
                "Sève": ["Dante", "Silverweed"],
                "Carapace": ["Mignonne", "Cornée", "Inteligente"],
                "Écorce": ["Adriel", "Mitexi", "Perfling"],
                "Bois": ["Tama"],
                "Boucles": ["Nita", "Patee", "Scratch", "Tansy"],
            },
            "BAD": {
                "Sève": ["Ardente ?", "Enola"],
                "Huile": ["Pilan"],
                "Carapace": ["Grosse"],
                "Ambres": ["Hash"],
                "Écorce": ["Oath"],
                "Bois": ["Kachine"],
            },
            "GOOD": {
                "Sève": ["Ardente ?", "Visc"],
                "Bois": ["Motega", "Abhaya"],
                "Ambres": ["Soo"],
                "Carapace": ["Splinter"],
                "Boucles": ["Yana"],
                "Résine": ["Fung", "Colle"],
            },
            "BEST": {
                "Ambres": ["Zun", "Sha"],
                "Graines": ["Caprice", "Saurona"],
                "Sève": ["Ardente ?"],
                "Écorce": ["Beckers"],
                "Bois": ["Eyota"],
                "Fibres": ["Dzao", "Shu"],
            },
        },
    },
    "HIVER": {
        "Sources Interdites": {
            "WORST": {
                "Ambres": ["Beng", "Pha", "Sha", "Zun"],
                "Graines": ["Caprice", "Silvio"],
                "Fibres": ["Anète", "Buo"],
                "Résine": ["Dung", "Colle", "Lune"],
                "Huile": ["Gulatch", "Irin", "Pilan"],
                "Sève": ["Dante", "Redhot", "Silverweed"],
                "Carapace": ["Mignonne", "Inteligente"],
                "Écorce": ["Beckers", "Oath", "Perfling"],
                "Bois": ["Eyota", "Kachine", "Tama"],
                "Boucles": ["Nita", "Patee", "Scratch", "Yana"],
            },
            "BAD": {
                "Ambres": ["Soo", "Hash"],
                "Écorce": ["Adriel"],
                "Boucles": ["Tansy"],
            },
            "GOOD": {
                "Fibres": ["Dzao"],
                "Huile": ["Koorin", "Enola"],
                "Sève": ["Visc"],
                "Graines": ["Saurona", "Sarina"],
                "Carapace": ["Splinter", "Cornée"],
                "Résine": ["Fung"],
                "Bois": ["Motega"],
            },
            "BEST": {
                "Fibres": ["Shu"],
                "Écorce": ["Mitexi"],
                "Carapace": ["Grosse"],
                "Bois": ["Abhaya"],
            },
        },
        "Terre de la Continuité": {
            "WORST": {
                "Ambres": ["Hash", "Pha", "Sha", "Zun"],
                "Graines": ["Caprice", "Sarina", "Silvio"],
                "Fibres": ["Shu"],
                "Résine": ["Colle", "Lune"],
                "Huile": ["Irin", "Koorin", "Pilan"],
                "Sève": ["Dante", "Enola"],
                "Carapace": ["Grosse", "Cornée", "Inteligente", "Splinter"],
                "Écorce": ["Adriel", "Beckers"],
                "Bois": ["Motega"],
                "Boucles": ["Nita", "Patee", "Scratch"],
            },
            "BAD": {
                "Carapace": ["Mignonne"],
                "Écorce": ["Perfling"],
                "Bois": ["Eyota"],
            },
            "GOOD": {
                "Ambres": ["Soo"],
                "Bois": ["Tama", "Abhaya"],
                "Boucles": ["Tansy", "Yana"],
                "Résine": ["Fung"],
                "Huile": ["Gulatch"],
                "Sève": ["Ardente", "Silverweed"],
            },
            "BEST": {
                "Ambres": ["Beng"],
                "Fibres": ["Buo", "Dzao", "Anète"],
                "Résine": ["Dung"],
                "Sève": ["Visc"],
                "Bois": ["Kachine"],
                "Boucles": ["Scratch"],
                "Écorce": ["Oath"],
                "Graines": ["Saurona"],
            },
        },
        "Cité Engloutie": {
            "WORST": {
                "Ambres": ["Pha"],
                "Graines": ["Caprice", "Saurona", "Silvio"],
                "Fibres": ["Anète", "Buo", "Dzao", "Shu"],
                "Résine": ["Dung", "Colle", "Lune"],
                "Huile": ["Gulatch", "Koorin"],
                "Sève": ["Dante"],
                "Carapace": ["Grosse", "Cornée", "Inteligente", "Splinter"],
                "Écorce": ["Adriel", "Beckers", "Mitexi"],
                "Bois": ["Abhaya", "Tama"],
                "Boucles": ["Nita", "Patee", "Scratch", "Tansy"],
            },
            "BAD": {
                "Huile": ["Irin"],
                "Bois": ["Eyota", "Kachine"],
                "Boucles": ["Yana ?"],
                "Graines": ["Sarina"],
            },
            "GOOD": {
                "Ambres": ["Beng"],
                "Sève": ["Visc agro KKT", "Enola"],
                "Carapace": ["Mignonne"],
                "Boucles": ["Yana ?"],
                "Résine": ["Fung"],
                "Huile": ["Pilan"],
            },
            "BEST": {
                "Ambres": ["Hash", "Sha", "Zun", "Soo"],
                "Écorce": ["Perfling", "Oath"],
                "Sève": ["Ardente", "Silverweed"],
                "Bois": ["Motega"],
            },
        },
        "Profondeurs Interdites": {
            "WORST": {
                "Ambres": ["Beng", "Pha"],
                "Graines": ["Sarina", "Silvio"],
                "Fibres": ["Anète", "Buo"],
                "Résine": ["Dung", "Lune"],
                "Huile": ["Gulatch", "Irin", "Koorin"],
                "Sève": ["Dante", "Silverweed"],
                "Carapace": ["Mignonne", "Cornée", "Inteligente"],
                "Écorce": ["Adriel", "Mitexi", "Perfling"],
                "Bois": ["Tama"],
                "Boucles": ["Nita", "Patee", "Scratch", "Tansy"],
            },
            "BAD": {
                "Huile": ["Pilan"],
                "Carapace": ["Grosse"],
                "Ambres": ["Hash"],
                "Sève": ["Enola", "Ardente ?"],
                "Écorce": ["Oath"],
                "Bois": ["Kachine"],
            },
            "GOOD": {
                "Ambres": ["Soo"],
                "Bois": ["Abhaya", "Motega"],
                "Carapace": ["Splinter"],
                "Boucles": ["Yana"],
                "Résine": ["Fung", "Colle"],
                "Sève": ["Ardente ?", "Visc"],
            },
            "BEST": {
                "Graines": ["Caprice", "Saurona"],
                "Fibres": ["Dzao", "Shu"],
                "Ambres": ["Sha", "Zun"],
                "Écorce": ["Beckers"],
                "Bois": ["Eyota"],
                "Sève": ["Ardente ?"],
            },
        },
    },
}

#: Zone du relevé -> continent interrogé pour la météo.
CONTINENT_DE_ZONE = {
    "Sources Interdites": "sources",
    "Terre de la Continuité": "terre",
    "Cité Engloutie": "terre",
    "Profondeurs Interdites": "terre",
}
