package net.ryzom.zyroom.model

// Fichier produit par outils/table_armory.py — ne pas modifier à la main.

/**
 * Les matières suprêmes, par saison et par zone des Primes.
 *
 * Relevé de Ryzom Armory, figé ici : ces listes ne changent qu'avec le jeu,
 * et l'application doit tenir le jour où ce site fermera.
 */
val SUPREMES: Map<String, Map<String, Map<String, List<String>>>> = mapOf(
    "PRINTEMPS" to mapOf(
        "Profondeurs Interdites" to mapOf(
            "Graines" to listOf("Sarina", "Silvio"),
            "Carapace" to listOf("Cuty", "Horny", "Smart", "Splinter"),
            "Fibres" to listOf("Anete", "Buo", "Dzao", "Shu"),
            "Bois" to listOf("Abhaya", "Eyota", "Motega"),
            "Boucles" to listOf("Nita", "Patee", "Scrath", "Tansy", "Yana"),
            "Ambres" to listOf("Beng", "Hash", "Pha", "Zun"),
            "Huile" to listOf("Gulatch", "Irin", "Koorin"),
            "Résine" to listOf("Dung", "Moon"),
            "Écorce" to listOf("Adriel", "Beckers", "Mitexi", "Perfling"),
            "Sève" to listOf("Dante", "Enola", "Silverweed"),
        ),
        "Terre de la Continuité" to mapOf(
            "Graines" to listOf("Caprice", "Sarina", "Silvio"),
            "Carapace" to listOf("Big", "Horny", "Smart", "Splinter"),
            "Fibres" to listOf("Anete", "Buo", "Shu"),
            "Bois" to listOf("Motega"),
            "Boucles" to listOf("Nita", "Patee", "Tansy", "Yana"),
            "Ambres" to listOf("Hash", "Pha", "Sha", "Zun"),
            "Huile" to listOf("Irin", "Koorin", "Pilan"),
            "Résine" to listOf("Glue", "Moon"),
            "Écorce" to listOf("Adriel", "Beckers", "Perfling"),
            "Sève" to listOf("Dante", "Enola", "Visc"),
        ),
        "Sources Interdites" to mapOf(
            "Graines" to listOf("Caprice", "Sarina", "Saurona", "Silvio"),
            "Carapace" to listOf("Big", "Cuty", "Smart", "Splinter"),
            "Fibres" to listOf("Anete", "Buo"),
            "Bois" to listOf("Eyota", "Kachine", "Tama"),
            "Boucles" to listOf("Nita", "Patee", "Scrath", "Yana"),
            "Ambres" to listOf("Beng", "Pha", "Sha", "Soo", "Zun"),
            "Huile" to listOf("Gulatch", "Irin", "Pilan"),
            "Résine" to listOf("Dung", "Glue", "Moon"),
            "Écorce" to listOf("Beckers", "Oath", "Perfling"),
            "Sève" to listOf("Dante", "Redhot", "Silverweed"),
        ),
        "Cité Engloutie" to mapOf(
            "Graines" to listOf("Caprice", "Saurona", "Silvio"),
            "Carapace" to listOf("Big", "Cuty", "Horny", "Smart", "Splinter"),
            "Fibres" to listOf("Anete", "Buo", "Dzao", "Shu"),
            "Bois" to listOf("Abhaya", "Eyota", "Motega"),
            "Boucles" to listOf("Nita", "Patee", "Scrath", "Tansy", "Yana"),
            "Ambres" to listOf("Pha", "Soo"),
            "Huile" to listOf("Gulatch", "Koorin"),
            "Résine" to listOf("Dung", "Moon"),
            "Écorce" to listOf("Adriel", "Beckers", "Mitexi", "Oath"),
            "Sève" to listOf("Dante", "Redhot"),
        ),
    ),
    "ETE" to mapOf(
        "Terre de la Continuité" to mapOf(
            "Graines" to listOf("Caprice", "Sarina", "Saurona", "Silvio"),
            "Carapace" to listOf("Big", "Horny", "Smart", "Splinter"),
            "Fibres" to listOf("Anete", "Shu"),
            "Bois" to listOf("Kachine", "Motega"),
            "Boucles" to listOf("Nita", "Patee", "Scrath"),
            "Ambres" to listOf("Hash", "Pha", "Sha", "Zun"),
            "Huile" to listOf("Gulatch", "Irin", "Koorin", "Pilan"),
            "Résine" to listOf("Fung", "Glue", "Moon"),
            "Écorce" to listOf("Adriel", "Beckers", "Mitexi", "Oath"),
            "Sève" to listOf("Dante", "Enola"),
        ),
        "Profondeurs Interdites" to mapOf(
            "Graines" to listOf("Sarina", "Saurona", "Silvio"),
            "Carapace" to listOf("Cuty", "Horny", "Smart"),
            "Fibres" to listOf("Anete", "Buo", "Shu"),
            "Bois" to listOf("Eyota", "Kachine", "Tama"),
            "Boucles" to listOf("Nita", "Patee", "Scrath", "Tansy"),
            "Huile" to listOf("Gulatch", "Irin", "Koorin"),
            "Résine" to listOf("Dung", "Fung", "Glue", "Moon"),
            "Ambres" to listOf("Beng", "Pha", "Sha"),
            "Écorce" to listOf("Adriel", "Mitexi", "Oath", "Perfling"),
            "Sève" to listOf("Dante", "Silverweed"),
        ),
        "Sources Interdites" to mapOf(
            "Graines" to listOf("Caprice", "Sarina", "Silvio"),
            "Carapace" to listOf("Cuty", "Horny", "Smart"),
            "Fibres" to listOf("Anete", "Buo", "Shu"),
            "Bois" to listOf("Abhaya", "Eyota", "Kachine", "Tama"),
            "Boucles" to listOf("Nita", "Patee", "Scrath", "Yana"),
            "Ambres" to listOf("Beng", "Hash", "Pha", "Sha", "Zun"),
            "Huile" to listOf("Gulatch", "Irin", "Pilan"),
            "Résine" to listOf("Dung", "Glue", "Moon"),
            "Écorce" to listOf("Adriel", "Beckers", "Oath", "Perfling"),
            "Sève" to listOf("Dante", "Redhot", "Silverweed"),
        ),
        "Cité Engloutie" to mapOf(
            "Graines" to listOf("Caprice", "Sarina", "Saurona", "Silvio"),
            "Carapace" to listOf("Big", "Horny", "Smart", "Splinter"),
            "Fibres" to listOf("Anete", "Buo", "Dzao", "Shu"),
            "Bois" to listOf("Abhaya", "Kachine", "Motega", "Tama"),
            "Boucles" to listOf("Nita", "Patee", "Scrath", "Tansy"),
            "Ambres" to listOf("Hash", "Pha", "Soo", "Zun"),
            "Huile" to listOf("Gulatch", "Koorin", "Pilan"),
            "Résine" to listOf("Dung", "Fung", "Glue", "Moon"),
            "Écorce" to listOf("Adriel", "Beckers", "Mitexi", "Oath"),
            "Sève" to listOf("Dante", "Redhot", "Silverweed"),
        ),
    ),
    "AUTOMNE" to mapOf(
        "Profondeurs Interdites" to mapOf(
            "Graines" to listOf("Caprice", "Sarina", "Silvio"),
            "Carapace" to listOf("Cuty", "Horny", "Smart"),
            "Fibres" to listOf("Anete", "Buo"),
            "Bois" to listOf("Eyota", "Motega", "Tama"),
            "Boucles" to listOf("Nita", "Patee", "Scrath", "Tansy"),
            "Ambres" to listOf("Beng", "Pha", "Zun"),
            "Huile" to listOf("Gulatch", "Irin", "Koorin"),
            "Résine" to listOf("Dung", "Fung", "Moon"),
            "Écorce" to listOf("Adriel", "Beckers", "Mitexi", "Perfling"),
            "Sève" to listOf("Dante", "Redhot", "Silverweed", "Visc"),
        ),
        "Cité Engloutie" to mapOf(
            "Graines" to listOf("Caprice", "Saurona", "Silvio"),
            "Carapace" to listOf("Big", "Horny", "Smart", "Splinter"),
            "Fibres" to listOf("Anete", "Buo", "Dzao", "Shu"),
            "Bois" to listOf("Abhaya", "Motega", "Tama"),
            "Boucles" to listOf("Nita", "Patee", "Scrath", "Tansy"),
            "Huile" to listOf("Gulatch", "Koorin"),
            "Résine" to listOf("Dung", "Glue", "Moon"),
            "Ambres" to listOf("Pha", "Sha"),
            "Écorce" to listOf("Adriel", "Mitexi", "Perfling"),
            "Sève" to listOf("Dante", "Enola", "Silverweed"),
        ),
        "Terre de la Continuité" to mapOf(
            "Graines" to listOf("Caprice", "Sarina", "Saurona", "Silvio"),
            "Carapace" to listOf("Big", "Horny", "Smart", "Splinter"),
            "Fibres" to listOf("Buo", "Dzao", "Shu"),
            "Bois" to listOf("Abhaya", "Motega"),
            "Boucles" to listOf("Nita", "Patee"),
            "Ambres" to listOf("Beng", "Hash", "Pha", "Sha", "Zun"),
            "Huile" to listOf("Irin", "Koorin", "Pilan"),
            "Résine" to listOf("Glue", "Moon"),
            "Écorce" to listOf("Adriel", "Beckers"),
            "Sève" to listOf("Dante", "Enola", "Redhot", "Silverweed"),
        ),
        "Sources Interdites" to mapOf(
            "Graines" to listOf("Caprice", "Silvio"),
            "Carapace" to listOf("Big", "Cuty", "Smart"),
            "Fibres" to listOf("Anete", "Buo"),
            "Bois" to listOf("Abhaya", "Eyota", "Kachine", "Motega", "Tama"),
            "Boucles" to listOf("Nita", "Patee", "Scrath", "Tansy", "Yana"),
            "Ambres" to listOf("Beng", "Pha", "Sha", "Zun"),
            "Huile" to listOf("Gulatch", "Irin", "Pilan"),
            "Résine" to listOf("Dung", "Fung", "Glue", "Moon"),
            "Écorce" to listOf("Beckers", "Mitexi", "Oath", "Perfling"),
            "Sève" to listOf("Dante", "Enola", "Redhot", "Silverweed"),
        ),
    ),
    "HIVER" to mapOf(
        "Terre de la Continuité" to mapOf(
            "Graines" to listOf("Caprice", "Sarina", "Silvio"),
            "Carapace" to listOf("Big", "Cuty", "Horny", "Smart", "Splinter"),
            "Fibres" to listOf("Buo", "Dzao", "Shu"),
            "Bois" to listOf("Kachine", "Motega", "Tama"),
            "Boucles" to listOf("Nita", "Patee", "Scrath"),
            "Ambres" to listOf("Beng", "Hash", "Pha", "Sha", "Soo", "Zun"),
            "Huile" to listOf("Irin", "Koorin", "Pilan"),
            "Résine" to listOf("Dung", "Glue", "Moon"),
            "Écorce" to listOf("Adriel", "Beckers"),
            "Sève" to listOf("Dante", "Enola", "Visc"),
        ),
        "Sources Interdites" to mapOf(
            "Graines" to listOf("Caprice", "Silvio"),
            "Carapace" to listOf("Cuty", "Smart"),
            "Fibres" to listOf("Anete", "Buo", "Dzao", "Shu"),
            "Bois" to listOf("Eyota", "Kachine", "Tama"),
            "Boucles" to listOf("Nita", "Patee", "Scrath", "Yana"),
            "Ambres" to listOf("Beng", "Pha", "Sha", "Zun"),
            "Huile" to listOf("Gulatch", "Irin", "Koorin", "Pilan"),
            "Résine" to listOf("Dung", "Glue", "Moon"),
            "Écorce" to listOf("Beckers", "Mitexi", "Oath", "Perfling"),
            "Sève" to listOf("Dante", "Redhot", "Silverweed", "Visc"),
        ),
        "Cité Engloutie" to mapOf(
            "Graines" to listOf("Caprice", "Saurona", "Silvio"),
            "Carapace" to listOf("Big", "Horny", "Smart", "Splinter"),
            "Fibres" to listOf("Anete", "Buo", "Dzao", "Shu"),
            "Bois" to listOf("Abhaya", "Tama"),
            "Boucles" to listOf("Nita", "Patee", "Scrath", "Tansy"),
            "Ambres" to listOf("Beng", "Hash", "Pha", "Sha", "Zun"),
            "Huile" to listOf("Gulatch", "Irin", "Koorin"),
            "Résine" to listOf("Dung", "Glue", "Moon"),
            "Écorce" to listOf("Mitexi", "Perfling"),
            "Sève" to listOf("Dante", "Enola", "Silverweed", "Visc"),
        ),
        "Profondeurs Interdites" to mapOf(
            "Graines" to listOf("Caprice", "Sarina", "Saurona", "Silvio"),
            "Carapace" to listOf("Big", "Cuty", "Horny", "Smart"),
            "Fibres" to listOf("Anete", "Buo", "Dzao"),
            "Bois" to listOf("Abhaya", "Tama"),
            "Boucles" to listOf("Nita", "Patee", "Scrath", "Tansy"),
            "Ambres" to listOf("Beng", "Pha", "Soo"),
            "Huile" to listOf("Gulatch", "Irin", "Koorin", "Pilan"),
            "Résine" to listOf("Dung", "Moon"),
            "Écorce" to listOf("Adriel", "Mitexi", "Perfling"),
            "Sève" to listOf("Dante", "Silverweed"),
        ),
    ),
)

/**
 * Les matières excellentes, par saison, de jour et de nuit.
 *
 * L'API ne les répartit pas par zone mais par moment de la journée :
 * c'est ainsi que le jeu les fait apparaître.
 */
val EXCELLENTES: Map<String, Map<String, Map<String, List<String>>>> = mapOf(
    "PRINTEMPS" to mapOf(
        "JOUR" to mapOf(
            "Carapace" to listOf("Big", "Cuty", "Horny", "Smart", "Splinter"),
            "Bois" to listOf("Eyota", "Kachine", "Tama"),
            "Boucles" to listOf("Tansy"),
            "Écorce" to listOf("Beckers", "Mitexi", "Perfling"),
            "Sève" to listOf("Dante", "Enola", "Redhot", "Silverweed", "Visc"),
        ),
        "NUIT" to mapOf(
            "Fibres" to listOf("Anete", "Dzao", "Shu"),
            "Résine" to listOf("Dung", "Fung", "Glue", "Moon"),
        ),
    ),
    "ETE" to mapOf(
        "JOUR" to mapOf(
            "Graines" to listOf("Caprice", "Sarina", "Saurona", "Silvio"),
            "Fibres" to listOf("Buo"),
            "Bois" to listOf("Eyota", "Kachine", "Tama"),
            "Boucles" to listOf("Nita", "Patee", "Scrath", "Yana"),
            "Ambres" to listOf("Pha", "Zun"),
            "Écorce" to listOf("Adriel"),
            "Sève" to listOf("Dante", "Redhot", "Visc"),
        ),
        "NUIT" to mapOf(
            "Fibres" to listOf("Anete", "Dzao", "Shu"),
            "Résine" to listOf("Dung", "Fung", "Glue", "Moon"),
        ),
    ),
    "AUTOMNE" to mapOf(
        "JOUR" to mapOf(
            "Carapace" to listOf("Big", "Cuty", "Horny", "Smart", "Splinter"),
            "Bois" to listOf("Abhaya", "Motega"),
            "Boucles" to listOf("Nita", "Patee", "Scrath", "Tansy", "Yana"),
            "Ambres" to listOf("Beng", "Hash", "Pha", "Sha", "Soo", "Zun"),
        ),
        "NUIT" to mapOf(
            "Huile" to listOf("Gulatch", "Irin", "Koorin", "Pilan"),
            "Résine" to listOf("Dung"),
        ),
    ),
    "HIVER" to mapOf(
        "JOUR" to mapOf(
            "Graines" to listOf("Caprice", "Sarina", "Saurona", "Silvio"),
            "Bois" to listOf("Abhaya", "Motega"),
            "Ambres" to listOf("Beng", "Hash", "Sha", "Soo"),
            "Écorce" to listOf("Adriel", "Beckers", "Mitexi", "Oath", "Perfling"),
            "Sève" to listOf("Enola", "Silverweed"),
        ),
        "NUIT" to mapOf(
            "Huile" to listOf("Gulatch", "Irin", "Koorin", "Pilan"),
            "Résine" to listOf("Dung"),
        ),
    ),
)
