package net.ryzom.zyroom.model

// Fichier produit par outils/table_forage.py — ne pas modifier à la main.

/**
 * Le suprême des Primes, créneau par créneau : zone, matière, saison et
 * temps. Relevé de terrain des foreuses de la guilde sur xiom.be/forage —
 * la même table que `forage.py` dans ZyRoom-GTK, et rien ne la contredit.
 */
internal val RELEVE_SUPREME: List<String> = listOf(
    "Sources Interdites|Ambres|Beng|AUTOMNE|WORST",
    "Sources Interdites|Ambres|Beng|ETE|WORST",
    "Sources Interdites|Ambres|Beng|HIVER|WORST",
    "Sources Interdites|Ambres|Beng|PRINTEMPS|WORST",
    "Sources Interdites|Ambres|Hash|ETE|BAD",
    "Sources Interdites|Ambres|Pha|AUTOMNE|WORST",
    "Sources Interdites|Ambres|Pha|ETE|WORST",
    "Sources Interdites|Ambres|Pha|HIVER|WORST",
    "Sources Interdites|Ambres|Pha|PRINTEMPS|WORST",
    "Sources Interdites|Ambres|Sha|AUTOMNE|WORST",
    "Sources Interdites|Ambres|Sha|ETE|WORST",
    "Sources Interdites|Ambres|Sha|HIVER|WORST",
    "Sources Interdites|Ambres|Sha|PRINTEMPS|WORST",
    "Sources Interdites|Ambres|Soo|PRINTEMPS|BAD",
    "Sources Interdites|Ambres|Zun|AUTOMNE|WORST",
    "Sources Interdites|Ambres|Zun|ETE|WORST",
    "Sources Interdites|Ambres|Zun|HIVER|WORST",
    "Sources Interdites|Ambres|Zun|PRINTEMPS|WORST",
    "Sources Interdites|Bois|Abhaya|AUTOMNE|BEST",
    "Sources Interdites|Bois|Abhaya|ETE|BEST",
    "Sources Interdites|Bois|Eyota|AUTOMNE|WORST",
    "Sources Interdites|Bois|Eyota|ETE|WORST",
    "Sources Interdites|Bois|Eyota|HIVER|WORST",
    "Sources Interdites|Bois|Eyota|PRINTEMPS|WORST",
    "Sources Interdites|Bois|Motega|AUTOMNE|BAD",
    "Sources Interdites|Bois|Motega|AUTOMNE|GOOD",
    "Sources Interdites|Bois|Tama|AUTOMNE|WORST",
    "Sources Interdites|Bois|Tama|ETE|WORST",
    "Sources Interdites|Bois|Tama|HIVER|WORST",
    "Sources Interdites|Bois|Tama|PRINTEMPS|WORST",
    "Sources Interdites|Boucles|Patee|AUTOMNE|WORST",
    "Sources Interdites|Boucles|Patee|ETE|WORST",
    "Sources Interdites|Boucles|Patee|HIVER|WORST",
    "Sources Interdites|Boucles|Patee|PRINTEMPS|WORST",
    "Sources Interdites|Boucles|Tansy|AUTOMNE|BAD",
    "Sources Interdites|Boucles|Tansy|AUTOMNE|GOOD",
    "Sources Interdites|Boucles|Yana|AUTOMNE|WORST",
    "Sources Interdites|Boucles|Yana|ETE|WORST",
    "Sources Interdites|Boucles|Yana|HIVER|WORST",
    "Sources Interdites|Boucles|Yana|PRINTEMPS|WORST",
    "Sources Interdites|Carapace|Big|AUTOMNE|BEST",
    "Sources Interdites|Carapace|Big|ETE|BEST",
    "Sources Interdites|Carapace|Big|PRINTEMPS|BEST",
    "Sources Interdites|Carapace|Cuty|AUTOMNE|WORST",
    "Sources Interdites|Carapace|Cuty|ETE|WORST",
    "Sources Interdites|Carapace|Cuty|HIVER|WORST",
    "Sources Interdites|Carapace|Cuty|PRINTEMPS|WORST",
    "Sources Interdites|Carapace|Splinter|PRINTEMPS|GOOD",
    "Sources Interdites|Fibres|Anete|AUTOMNE|WORST",
    "Sources Interdites|Fibres|Anete|ETE|WORST",
    "Sources Interdites|Fibres|Anete|HIVER|WORST",
    "Sources Interdites|Fibres|Anete|PRINTEMPS|WORST",
    "Sources Interdites|Fibres|Buo|AUTOMNE|WORST",
    "Sources Interdites|Fibres|Buo|ETE|WORST",
    "Sources Interdites|Fibres|Buo|HIVER|WORST",
    "Sources Interdites|Fibres|Buo|PRINTEMPS|WORST",
    "Sources Interdites|Fibres|Dzao|HIVER|GOOD",
    "Sources Interdites|Fibres|Shu|ETE|BEST",
    "Sources Interdites|Fibres|Shu|HIVER|BEST",
    "Sources Interdites|Graines|Caprice|AUTOMNE|WORST",
    "Sources Interdites|Graines|Caprice|ETE|WORST",
    "Sources Interdites|Graines|Caprice|HIVER|WORST",
    "Sources Interdites|Graines|Caprice|PRINTEMPS|WORST",
    "Sources Interdites|Graines|Sarina|ETE|GOOD",
    "Sources Interdites|Graines|Saurona|PRINTEMPS|GOOD",
    "Sources Interdites|Graines|Silvio|AUTOMNE|WORST",
    "Sources Interdites|Graines|Silvio|ETE|WORST",
    "Sources Interdites|Graines|Silvio|HIVER|WORST",
    "Sources Interdites|Graines|Silvio|PRINTEMPS|WORST",
    "Sources Interdites|Huile|Gulatch|AUTOMNE|WORST",
    "Sources Interdites|Huile|Gulatch|ETE|WORST",
    "Sources Interdites|Huile|Gulatch|HIVER|WORST",
    "Sources Interdites|Huile|Gulatch|PRINTEMPS|WORST",
    "Sources Interdites|Huile|Irin|AUTOMNE|WORST",
    "Sources Interdites|Huile|Irin|ETE|WORST",
    "Sources Interdites|Huile|Irin|HIVER|WORST",
    "Sources Interdites|Huile|Irin|PRINTEMPS|WORST",
    "Sources Interdites|Huile|Koorin|AUTOMNE|WORST",
    "Sources Interdites|Huile|Koorin|ETE|WORST",
    "Sources Interdites|Huile|Koorin|HIVER|WORST",
    "Sources Interdites|Huile|Koorin|PRINTEMPS|WORST",
    "Sources Interdites|Résine|Dung|ETE|WORST",
    "Sources Interdites|Résine|Dung|HIVER|WORST",
    "Sources Interdites|Résine|Dung|PRINTEMPS|WORST",
    "Sources Interdites|Résine|Fung|AUTOMNE|GOOD",
    "Sources Interdites|Résine|Glue|ETE|WORST",
    "Sources Interdites|Résine|Glue|HIVER|WORST",
    "Sources Interdites|Résine|Glue|PRINTEMPS|WORST",
    "Sources Interdites|Résine|Moon|ETE|WORST",
    "Sources Interdites|Résine|Moon|HIVER|WORST",
    "Sources Interdites|Résine|Moon|PRINTEMPS|WORST",
    "Sources Interdites|Sève|Dante|AUTOMNE|WORST",
    "Sources Interdites|Sève|Dante|ETE|WORST",
    "Sources Interdites|Sève|Dante|HIVER|WORST",
    "Sources Interdites|Sève|Dante|PRINTEMPS|WORST",
    "Sources Interdites|Sève|Enola|AUTOMNE|GOOD",
    "Sources Interdites|Sève|Silverweed|AUTOMNE|WORST",
    "Sources Interdites|Sève|Silverweed|ETE|WORST",
    "Sources Interdites|Sève|Silverweed|HIVER|WORST",
    "Sources Interdites|Sève|Silverweed|PRINTEMPS|WORST",
    "Sources Interdites|Sève|Visc|HIVER|BEST",
    "Sources Interdites|Écorce|Adriel|ETE|BAD",
    "Sources Interdites|Écorce|Beckers|AUTOMNE|WORST",
    "Sources Interdites|Écorce|Beckers|ETE|WORST",
    "Sources Interdites|Écorce|Beckers|HIVER|WORST",
    "Sources Interdites|Écorce|Beckers|PRINTEMPS|WORST",
    "Sources Interdites|Écorce|Mitexi|AUTOMNE|BEST",
    "Sources Interdites|Écorce|Mitexi|AUTOMNE|WORST",
    "Sources Interdites|Écorce|Mitexi|ETE|WORST",
    "Sources Interdites|Écorce|Mitexi|HIVER|BEST",
    "Sources Interdites|Écorce|Mitexi|HIVER|WORST",
    "Sources Interdites|Écorce|Mitexi|PRINTEMPS|WORST",
    "Sources Interdites|Écorce|Oath|AUTOMNE|WORST",
    "Sources Interdites|Écorce|Oath|ETE|WORST",
    "Sources Interdites|Écorce|Oath|HIVER|WORST",
    "Sources Interdites|Écorce|Oath|PRINTEMPS|WORST",
    "Terre de la Continuité|Ambres|Beng|AUTOMNE|BEST",
    "Terre de la Continuité|Ambres|Hash|AUTOMNE|WORST",
    "Terre de la Continuité|Ambres|Hash|ETE|WORST",
    "Terre de la Continuité|Ambres|Hash|HIVER|WORST",
    "Terre de la Continuité|Ambres|Hash|PRINTEMPS|WORST",
    "Terre de la Continuité|Ambres|Pha|AUTOMNE|WORST",
    "Terre de la Continuité|Ambres|Pha|ETE|WORST",
    "Terre de la Continuité|Ambres|Pha|HIVER|WORST",
    "Terre de la Continuité|Ambres|Pha|PRINTEMPS|WORST",
    "Terre de la Continuité|Ambres|Sha|AUTOMNE|WORST",
    "Terre de la Continuité|Ambres|Sha|ETE|WORST",
    "Terre de la Continuité|Ambres|Sha|HIVER|WORST",
    "Terre de la Continuité|Ambres|Sha|PRINTEMPS|WORST",
    "Terre de la Continuité|Ambres|Soo|HIVER|GOOD",
    "Terre de la Continuité|Ambres|Zun|AUTOMNE|WORST",
    "Terre de la Continuité|Ambres|Zun|ETE|WORST",
    "Terre de la Continuité|Ambres|Zun|HIVER|WORST",
    "Terre de la Continuité|Ambres|Zun|PRINTEMPS|WORST",
    "Terre de la Continuité|Bois|Abhaya|AUTOMNE|GOOD",
    "Terre de la Continuité|Bois|Eyota|ETE|BAD",
    "Terre de la Continuité|Bois|Kachine|ETE|BEST",
    "Terre de la Continuité|Bois|Kachine|HIVER|BEST",
    "Terre de la Continuité|Bois|Motega|AUTOMNE|BAD",
    "Terre de la Continuité|Bois|Motega|AUTOMNE|WORST",
    "Terre de la Continuité|Bois|Motega|ETE|WORST",
    "Terre de la Continuité|Bois|Motega|HIVER|WORST",
    "Terre de la Continuité|Bois|Motega|PRINTEMPS|WORST",
    "Terre de la Continuité|Bois|Tama|HIVER|GOOD",
    "Terre de la Continuité|Boucles|Patee|AUTOMNE|WORST",
    "Terre de la Continuité|Boucles|Patee|ETE|WORST",
    "Terre de la Continuité|Boucles|Patee|HIVER|WORST",
    "Terre de la Continuité|Boucles|Patee|PRINTEMPS|WORST",
    "Terre de la Continuité|Boucles|Scrath|ETE|BEST",
    "Terre de la Continuité|Boucles|Scrath|HIVER|BEST",
    "Terre de la Continuité|Boucles|Tansy|PRINTEMPS|GOOD",
    "Terre de la Continuité|Boucles|Yana|PRINTEMPS|GOOD",
    "Terre de la Continuité|Carapace|Big|AUTOMNE|WORST",
    "Terre de la Continuité|Carapace|Big|ETE|WORST",
    "Terre de la Continuité|Carapace|Big|HIVER|WORST",
    "Terre de la Continuité|Carapace|Big|PRINTEMPS|WORST",
    "Terre de la Continuité|Carapace|Cuty|HIVER|BAD",
    "Terre de la Continuité|Carapace|Splinter|AUTOMNE|WORST",
    "Terre de la Continuité|Carapace|Splinter|ETE|WORST",
    "Terre de la Continuité|Carapace|Splinter|HIVER|WORST",
    "Terre de la Continuité|Carapace|Splinter|PRINTEMPS|WORST",
    "Terre de la Continuité|Fibres|Anete|ETE|BEST",
    "Terre de la Continuité|Fibres|Anete|PRINTEMPS|BEST",
    "Terre de la Continuité|Fibres|Buo|PRINTEMPS|BEST",
    "Terre de la Continuité|Fibres|Dzao|AUTOMNE|BEST",
    "Terre de la Continuité|Fibres|Dzao|HIVER|BEST",
    "Terre de la Continuité|Fibres|Shu|AUTOMNE|WORST",
    "Terre de la Continuité|Fibres|Shu|ETE|WORST",
    "Terre de la Continuité|Fibres|Shu|HIVER|WORST",
    "Terre de la Continuité|Fibres|Shu|PRINTEMPS|WORST",
    "Terre de la Continuité|Graines|Caprice|AUTOMNE|WORST",
    "Terre de la Continuité|Graines|Caprice|ETE|WORST",
    "Terre de la Continuité|Graines|Caprice|HIVER|WORST",
    "Terre de la Continuité|Graines|Caprice|PRINTEMPS|WORST",
    "Terre de la Continuité|Graines|Sarina|AUTOMNE|WORST",
    "Terre de la Continuité|Graines|Sarina|ETE|WORST",
    "Terre de la Continuité|Graines|Sarina|HIVER|WORST",
    "Terre de la Continuité|Graines|Sarina|PRINTEMPS|WORST",
    "Terre de la Continuité|Graines|Saurona|ETE|BEST",
    "Terre de la Continuité|Graines|Silvio|AUTOMNE|WORST",
    "Terre de la Continuité|Graines|Silvio|ETE|WORST",
    "Terre de la Continuité|Graines|Silvio|HIVER|WORST",
    "Terre de la Continuité|Graines|Silvio|PRINTEMPS|WORST",
    "Terre de la Continuité|Huile|Gulatch|ETE|GOOD",
    "Terre de la Continuité|Huile|Irin|AUTOMNE|WORST",
    "Terre de la Continuité|Huile|Irin|ETE|WORST",
    "Terre de la Continuité|Huile|Irin|HIVER|WORST",
    "Terre de la Continuité|Huile|Irin|PRINTEMPS|WORST",
    "Terre de la Continuité|Huile|Koorin|AUTOMNE|WORST",
    "Terre de la Continuité|Huile|Koorin|ETE|WORST",
    "Terre de la Continuité|Huile|Koorin|HIVER|WORST",
    "Terre de la Continuité|Huile|Koorin|PRINTEMPS|WORST",
    "Terre de la Continuité|Résine|Dung|HIVER|BAD",
    "Terre de la Continuité|Résine|Fung|ETE|GOOD",
    "Terre de la Continuité|Résine|Glue|AUTOMNE|WORST",
    "Terre de la Continuité|Résine|Glue|ETE|WORST",
    "Terre de la Continuité|Résine|Glue|HIVER|WORST",
    "Terre de la Continuité|Résine|Glue|PRINTEMPS|WORST",
    "Terre de la Continuité|Résine|Moon|ETE|WORST",
    "Terre de la Continuité|Résine|Moon|HIVER|WORST",
    "Terre de la Continuité|Résine|Moon|PRINTEMPS|WORST",
    "Terre de la Continuité|Sève|Dante|AUTOMNE|WORST",
    "Terre de la Continuité|Sève|Dante|ETE|WORST",
    "Terre de la Continuité|Sève|Dante|HIVER|WORST",
    "Terre de la Continuité|Sève|Dante|PRINTEMPS|WORST",
    "Terre de la Continuité|Sève|Redhot|AUTOMNE|GOOD",
    "Terre de la Continuité|Sève|Silverweed|AUTOMNE|GOOD",
    "Terre de la Continuité|Sève|Visc|HIVER|BEST",
    "Terre de la Continuité|Écorce|Beckers|AUTOMNE|WORST",
    "Terre de la Continuité|Écorce|Beckers|ETE|WORST",
    "Terre de la Continuité|Écorce|Beckers|HIVER|WORST",
    "Terre de la Continuité|Écorce|Beckers|PRINTEMPS|WORST",
    "Terre de la Continuité|Écorce|Mitexi|ETE|BAD",
    "Terre de la Continuité|Écorce|Oath|ETE|BEST",
    "Terre de la Continuité|Écorce|Oath|PRINTEMPS|BEST",
    "Terre de la Continuité|Écorce|Perfling|PRINTEMPS|BAD",
    "Cité Engloutie|Ambres|Beng|HIVER|GOOD",
    "Cité Engloutie|Ambres|Hash|ETE|BEST",
    "Cité Engloutie|Ambres|Hash|HIVER|BEST",
    "Cité Engloutie|Ambres|Pha|AUTOMNE|WORST",
    "Cité Engloutie|Ambres|Pha|ETE|WORST",
    "Cité Engloutie|Ambres|Pha|HIVER|WORST",
    "Cité Engloutie|Ambres|Pha|PRINTEMPS|WORST",
    "Cité Engloutie|Ambres|Sha|AUTOMNE|BEST",
    "Cité Engloutie|Ambres|Sha|HIVER|BEST",
    "Cité Engloutie|Ambres|Soo|ETE|BEST",
    "Cité Engloutie|Ambres|Soo|PRINTEMPS|BEST",
    "Cité Engloutie|Ambres|Zun|ETE|BEST",
    "Cité Engloutie|Ambres|Zun|HIVER|BEST",
    "Cité Engloutie|Bois|Abhaya|AUTOMNE|WORST",
    "Cité Engloutie|Bois|Abhaya|ETE|WORST",
    "Cité Engloutie|Bois|Abhaya|HIVER|WORST",
    "Cité Engloutie|Bois|Abhaya|PRINTEMPS|WORST",
    "Cité Engloutie|Bois|Eyota|PRINTEMPS|BAD",
    "Cité Engloutie|Bois|Kachine|ETE|BAD",
    "Cité Engloutie|Bois|Kachine|ETE|BEST",
    "Cité Engloutie|Bois|Motega|AUTOMNE|GOOD",
    "Cité Engloutie|Bois|Tama|AUTOMNE|WORST",
    "Cité Engloutie|Bois|Tama|ETE|WORST",
    "Cité Engloutie|Bois|Tama|HIVER|WORST",
    "Cité Engloutie|Bois|Tama|PRINTEMPS|WORST",
    "Cité Engloutie|Boucles|Patee|AUTOMNE|WORST",
    "Cité Engloutie|Boucles|Patee|ETE|WORST",
    "Cité Engloutie|Boucles|Patee|HIVER|WORST",
    "Cité Engloutie|Boucles|Patee|PRINTEMPS|WORST",
    "Cité Engloutie|Carapace|Cuty|PRINTEMPS|GOOD",
    "Cité Engloutie|Carapace|Splinter|AUTOMNE|WORST",
    "Cité Engloutie|Carapace|Splinter|ETE|WORST",
    "Cité Engloutie|Carapace|Splinter|HIVER|WORST",
    "Cité Engloutie|Carapace|Splinter|PRINTEMPS|WORST",
    "Cité Engloutie|Fibres|Anete|AUTOMNE|WORST",
    "Cité Engloutie|Fibres|Anete|ETE|WORST",
    "Cité Engloutie|Fibres|Anete|HIVER|WORST",
    "Cité Engloutie|Fibres|Anete|PRINTEMPS|WORST",
    "Cité Engloutie|Fibres|Buo|AUTOMNE|WORST",
    "Cité Engloutie|Fibres|Buo|ETE|WORST",
    "Cité Engloutie|Fibres|Buo|HIVER|WORST",
    "Cité Engloutie|Fibres|Buo|PRINTEMPS|WORST",
    "Cité Engloutie|Fibres|Dzao|AUTOMNE|WORST",
    "Cité Engloutie|Fibres|Dzao|ETE|WORST",
    "Cité Engloutie|Fibres|Dzao|HIVER|WORST",
    "Cité Engloutie|Fibres|Dzao|PRINTEMPS|WORST",
    "Cité Engloutie|Fibres|Shu|AUTOMNE|WORST",
    "Cité Engloutie|Fibres|Shu|ETE|WORST",
    "Cité Engloutie|Fibres|Shu|HIVER|WORST",
    "Cité Engloutie|Fibres|Shu|PRINTEMPS|WORST",
    "Cité Engloutie|Graines|Caprice|AUTOMNE|WORST",
    "Cité Engloutie|Graines|Caprice|ETE|WORST",
    "Cité Engloutie|Graines|Caprice|HIVER|WORST",
    "Cité Engloutie|Graines|Caprice|PRINTEMPS|WORST",
    "Cité Engloutie|Graines|Sarina|ETE|BAD",
    "Cité Engloutie|Graines|Saurona|AUTOMNE|WORST",
    "Cité Engloutie|Graines|Saurona|ETE|WORST",
    "Cité Engloutie|Graines|Saurona|HIVER|WORST",
    "Cité Engloutie|Graines|Saurona|PRINTEMPS|WORST",
    "Cité Engloutie|Graines|Silvio|AUTOMNE|WORST",
    "Cité Engloutie|Graines|Silvio|ETE|WORST",
    "Cité Engloutie|Graines|Silvio|HIVER|WORST",
    "Cité Engloutie|Graines|Silvio|PRINTEMPS|WORST",
    "Cité Engloutie|Huile|Gulatch|AUTOMNE|WORST",
    "Cité Engloutie|Huile|Gulatch|ETE|WORST",
    "Cité Engloutie|Huile|Gulatch|HIVER|WORST",
    "Cité Engloutie|Huile|Gulatch|PRINTEMPS|WORST",
    "Cité Engloutie|Huile|Irin|HIVER|BAD",
    "Cité Engloutie|Huile|Koorin|AUTOMNE|WORST",
    "Cité Engloutie|Huile|Koorin|ETE|WORST",
    "Cité Engloutie|Huile|Koorin|HIVER|WORST",
    "Cité Engloutie|Huile|Koorin|PRINTEMPS|WORST",
    "Cité Engloutie|Huile|Pilan|ETE|GOOD",
    "Cité Engloutie|Résine|Dung|AUTOMNE|WORST",
    "Cité Engloutie|Résine|Dung|ETE|WORST",
    "Cité Engloutie|Résine|Dung|HIVER|WORST",
    "Cité Engloutie|Résine|Dung|PRINTEMPS|WORST",
    "Cité Engloutie|Résine|Fung|ETE|GOOD",
    "Cité Engloutie|Résine|Glue|AUTOMNE|WORST",
    "Cité Engloutie|Résine|Glue|ETE|WORST",
    "Cité Engloutie|Résine|Glue|HIVER|WORST",
    "Cité Engloutie|Résine|Glue|PRINTEMPS|WORST",
    "Cité Engloutie|Résine|Moon|AUTOMNE|WORST",
    "Cité Engloutie|Résine|Moon|ETE|WORST",
    "Cité Engloutie|Résine|Moon|HIVER|WORST",
    "Cité Engloutie|Résine|Moon|PRINTEMPS|WORST",
    "Cité Engloutie|Sève|Dante|AUTOMNE|WORST",
    "Cité Engloutie|Sève|Dante|ETE|WORST",
    "Cité Engloutie|Sève|Dante|HIVER|WORST",
    "Cité Engloutie|Sève|Dante|PRINTEMPS|WORST",
    "Cité Engloutie|Sève|Enola|AUTOMNE|GOOD",
    "Cité Engloutie|Sève|Redhot|PRINTEMPS|BEST",
    "Cité Engloutie|Sève|Silverweed|AUTOMNE|BEST",
    "Cité Engloutie|Sève|Silverweed|ETE|BEST",
    "Cité Engloutie|Sève|Visc|HIVER|GOOD",
    "Cité Engloutie|Écorce|Adriel|AUTOMNE|BEST",
    "Cité Engloutie|Écorce|Adriel|PRINTEMPS|BEST",
    "Cité Engloutie|Écorce|Beckers|ETE|BEST",
    "Cité Engloutie|Écorce|Beckers|PRINTEMPS|BEST",
    "Cité Engloutie|Écorce|Mitexi|AUTOMNE|WORST",
    "Cité Engloutie|Écorce|Mitexi|ETE|WORST",
    "Cité Engloutie|Écorce|Mitexi|HIVER|WORST",
    "Cité Engloutie|Écorce|Mitexi|PRINTEMPS|WORST",
    "Cité Engloutie|Écorce|Oath|PRINTEMPS|BEST",
    "Cité Engloutie|Écorce|Perfling|AUTOMNE|BEST",
    "Cité Engloutie|Écorce|Perfling|HIVER|BEST",
    "Profondeurs Interdites|Ambres|Beng|AUTOMNE|WORST",
    "Profondeurs Interdites|Ambres|Beng|ETE|WORST",
    "Profondeurs Interdites|Ambres|Beng|HIVER|WORST",
    "Profondeurs Interdites|Ambres|Beng|PRINTEMPS|WORST",
    "Profondeurs Interdites|Ambres|Hash|PRINTEMPS|BAD",
    "Profondeurs Interdites|Ambres|Pha|AUTOMNE|WORST",
    "Profondeurs Interdites|Ambres|Pha|ETE|WORST",
    "Profondeurs Interdites|Ambres|Pha|HIVER|WORST",
    "Profondeurs Interdites|Ambres|Pha|PRINTEMPS|WORST",
    "Profondeurs Interdites|Ambres|Sha|ETE|BEST",
    "Profondeurs Interdites|Ambres|Sha|PRINTEMPS|BEST",
    "Profondeurs Interdites|Ambres|Soo|HIVER|GOOD",
    "Profondeurs Interdites|Ambres|Zun|AUTOMNE|BEST",
    "Profondeurs Interdites|Ambres|Zun|PRINTEMPS|BEST",
    "Profondeurs Interdites|Bois|Abhaya|HIVER|GOOD",
    "Profondeurs Interdites|Bois|Eyota|AUTOMNE|BEST",
    "Profondeurs Interdites|Bois|Eyota|ETE|BEST",
    "Profondeurs Interdites|Bois|Kachine|ETE|BAD",
    "Profondeurs Interdites|Bois|Motega|AUTOMNE|GOOD",
    "Profondeurs Interdites|Bois|Tama|AUTOMNE|WORST",
    "Profondeurs Interdites|Bois|Tama|ETE|WORST",
    "Profondeurs Interdites|Bois|Tama|HIVER|WORST",
    "Profondeurs Interdites|Bois|Tama|PRINTEMPS|WORST",
    "Profondeurs Interdites|Boucles|Nita|AUTOMNE|WORST",
    "Profondeurs Interdites|Boucles|Nita|ETE|WORST",
    "Profondeurs Interdites|Boucles|Nita|HIVER|WORST",
    "Profondeurs Interdites|Boucles|Nita|PRINTEMPS|WORST",
    "Profondeurs Interdites|Boucles|Patee|AUTOMNE|WORST",
    "Profondeurs Interdites|Boucles|Patee|ETE|WORST",
    "Profondeurs Interdites|Boucles|Patee|HIVER|WORST",
    "Profondeurs Interdites|Boucles|Patee|PRINTEMPS|WORST",
    "Profondeurs Interdites|Boucles|Yana|PRINTEMPS|GOOD",
    "Profondeurs Interdites|Carapace|Big|HIVER|BAD",
    "Profondeurs Interdites|Carapace|Cuty|AUTOMNE|WORST",
    "Profondeurs Interdites|Carapace|Cuty|ETE|WORST",
    "Profondeurs Interdites|Carapace|Cuty|HIVER|WORST",
    "Profondeurs Interdites|Carapace|Cuty|PRINTEMPS|WORST",
    "Profondeurs Interdites|Carapace|Splinter|PRINTEMPS|GOOD",
    "Profondeurs Interdites|Fibres|Anete|AUTOMNE|WORST",
    "Profondeurs Interdites|Fibres|Anete|ETE|WORST",
    "Profondeurs Interdites|Fibres|Anete|HIVER|WORST",
    "Profondeurs Interdites|Fibres|Anete|PRINTEMPS|WORST",
    "Profondeurs Interdites|Fibres|Buo|AUTOMNE|WORST",
    "Profondeurs Interdites|Fibres|Buo|ETE|WORST",
    "Profondeurs Interdites|Fibres|Buo|HIVER|WORST",
    "Profondeurs Interdites|Fibres|Buo|PRINTEMPS|WORST",
    "Profondeurs Interdites|Fibres|Dzao|HIVER|BEST",
    "Profondeurs Interdites|Fibres|Dzao|PRINTEMPS|BEST",
    "Profondeurs Interdites|Fibres|Shu|ETE|BEST",
    "Profondeurs Interdites|Fibres|Shu|PRINTEMPS|BEST",
    "Profondeurs Interdites|Graines|Caprice|AUTOMNE|BEST",
    "Profondeurs Interdites|Graines|Sarina|AUTOMNE|WORST",
    "Profondeurs Interdites|Graines|Sarina|ETE|WORST",
    "Profondeurs Interdites|Graines|Sarina|HIVER|WORST",
    "Profondeurs Interdites|Graines|Sarina|PRINTEMPS|WORST",
    "Profondeurs Interdites|Graines|Saurona|ETE|BEST",
    "Profondeurs Interdites|Graines|Saurona|HIVER|BEST",
    "Profondeurs Interdites|Graines|Silvio|AUTOMNE|WORST",
    "Profondeurs Interdites|Graines|Silvio|ETE|WORST",
    "Profondeurs Interdites|Graines|Silvio|HIVER|WORST",
    "Profondeurs Interdites|Graines|Silvio|PRINTEMPS|WORST",
    "Profondeurs Interdites|Huile|Gulatch|AUTOMNE|WORST",
    "Profondeurs Interdites|Huile|Gulatch|ETE|WORST",
    "Profondeurs Interdites|Huile|Gulatch|HIVER|WORST",
    "Profondeurs Interdites|Huile|Gulatch|PRINTEMPS|WORST",
    "Profondeurs Interdites|Huile|Irin|AUTOMNE|WORST",
    "Profondeurs Interdites|Huile|Irin|ETE|WORST",
    "Profondeurs Interdites|Huile|Irin|HIVER|WORST",
    "Profondeurs Interdites|Huile|Irin|PRINTEMPS|WORST",
    "Profondeurs Interdites|Huile|Pilan|AUTOMNE|WORST",
    "Profondeurs Interdites|Huile|Pilan|ETE|WORST",
    "Profondeurs Interdites|Huile|Pilan|HIVER|BAD",
    "Profondeurs Interdites|Huile|Pilan|HIVER|WORST",
    "Profondeurs Interdites|Huile|Pilan|PRINTEMPS|WORST",
    "Profondeurs Interdites|Résine|Dung|AUTOMNE|WORST",
    "Profondeurs Interdites|Résine|Dung|ETE|WORST",
    "Profondeurs Interdites|Résine|Dung|HIVER|WORST",
    "Profondeurs Interdites|Résine|Dung|PRINTEMPS|WORST",
    "Profondeurs Interdites|Résine|Fung|ETE|GOOD",
    "Profondeurs Interdites|Résine|Glue|ETE|GOOD",
    "Profondeurs Interdites|Résine|Moon|AUTOMNE|WORST",
    "Profondeurs Interdites|Résine|Moon|ETE|WORST",
    "Profondeurs Interdites|Résine|Moon|HIVER|WORST",
    "Profondeurs Interdites|Résine|Moon|PRINTEMPS|WORST",
    "Profondeurs Interdites|Sève|Dante|AUTOMNE|WORST",
    "Profondeurs Interdites|Sève|Dante|ETE|WORST",
    "Profondeurs Interdites|Sève|Dante|HIVER|WORST",
    "Profondeurs Interdites|Sève|Dante|PRINTEMPS|WORST",
    "Profondeurs Interdites|Sève|Enola|PRINTEMPS|BAD",
    "Profondeurs Interdites|Sève|Redhot|AUTOMNE|BEST",
    "Profondeurs Interdites|Sève|Silverweed|AUTOMNE|WORST",
    "Profondeurs Interdites|Sève|Silverweed|ETE|WORST",
    "Profondeurs Interdites|Sève|Silverweed|HIVER|WORST",
    "Profondeurs Interdites|Sève|Silverweed|PRINTEMPS|WORST",
    "Profondeurs Interdites|Sève|Visc|AUTOMNE|GOOD",
    "Profondeurs Interdites|Écorce|Adriel|AUTOMNE|WORST",
    "Profondeurs Interdites|Écorce|Adriel|ETE|WORST",
    "Profondeurs Interdites|Écorce|Adriel|HIVER|WORST",
    "Profondeurs Interdites|Écorce|Adriel|PRINTEMPS|WORST",
    "Profondeurs Interdites|Écorce|Beckers|AUTOMNE|BEST",
    "Profondeurs Interdites|Écorce|Beckers|PRINTEMPS|BEST",
    "Profondeurs Interdites|Écorce|Mitexi|AUTOMNE|WORST",
    "Profondeurs Interdites|Écorce|Mitexi|ETE|WORST",
    "Profondeurs Interdites|Écorce|Mitexi|HIVER|WORST",
    "Profondeurs Interdites|Écorce|Mitexi|PRINTEMPS|WORST",
    "Profondeurs Interdites|Écorce|Oath|ETE|BAD",
)

/**
 * L'excellente, du même relevé. Les créneaux à confirmer en font partie :
 * `Forage` les retire de ce qu'il montre, sauf dans la variante dev.
 */
internal val RELEVE_EXCELLENTE: List<String> = listOf(
    "Sources Interdites|Ambres|Beng|PRINTEMPS|BAD",
    "Sources Interdites|Ambres|Pha|HIVER|GOOD",
    "Sources Interdites|Ambres|Sha|AUTOMNE|BAD",
    "Sources Interdites|Ambres|Sha|ETE|BAD",
    "Sources Interdites|Ambres|Sha|ETE|WORST",
    "Sources Interdites|Ambres|Sha|HIVER|BAD",
    "Sources Interdites|Ambres|Zun|AUTOMNE|BAD",
    "Sources Interdites|Ambres|Zun|PRINTEMPS|BAD",
    "Sources Interdites|Boucles|Nita|AUTOMNE|BAD",
    "Sources Interdites|Boucles|Nita|HIVER|BAD",
    "Sources Interdites|Boucles|Nita|PRINTEMPS|BAD",
    "Sources Interdites|Boucles|Scrath|ETE|GOOD",
    "Sources Interdites|Boucles|Scrath|PRINTEMPS|GOOD",
    "Sources Interdites|Carapace|Big|AUTOMNE|BAD",
    "Sources Interdites|Carapace|Big|AUTOMNE|BEST",
    "Sources Interdites|Carapace|Big|AUTOMNE|GOOD",
    "Sources Interdites|Carapace|Big|ETE|BAD",
    "Sources Interdites|Carapace|Big|HIVER|BAD",
    "Sources Interdites|Carapace|Big|PRINTEMPS|BAD",
    "Sources Interdites|Carapace|Cuty|AUTOMNE|BAD",
    "Sources Interdites|Carapace|Cuty|AUTOMNE|BEST",
    "Sources Interdites|Carapace|Cuty|ETE|BAD",
    "Sources Interdites|Carapace|Cuty|HIVER|BAD",
    "Sources Interdites|Carapace|Cuty|PRINTEMPS|BAD",
    "Sources Interdites|Carapace|Horny|PRINTEMPS|BAD",
    "Sources Interdites|Carapace|Horny|PRINTEMPS|GOOD",
    "Sources Interdites|Carapace|Splinter|AUTOMNE|BAD",
    "Sources Interdites|Carapace|Splinter|HIVER|BAD",
    "Sources Interdites|Carapace|Splinter|PRINTEMPS|BAD",
    "Sources Interdites|Fibres|Anete|AUTOMNE|BEST",
    "Sources Interdites|Fibres|Anete|PRINTEMPS|BEST",
    "Sources Interdites|Fibres|Anete|PRINTEMPS|GOOD",
    "Sources Interdites|Fibres|Buo|HIVER|GOOD",
    "Sources Interdites|Fibres|Dzao|HIVER|BEST",
    "Sources Interdites|Fibres|Shu|AUTOMNE|BAD",
    "Sources Interdites|Fibres|Shu|ETE|BAD",
    "Sources Interdites|Fibres|Shu|HIVER|BAD",
    "Sources Interdites|Fibres|Shu|HIVER|BEST",
    "Sources Interdites|Fibres|Shu|PRINTEMPS|BAD",
    "Sources Interdites|Graines|Sarina|AUTOMNE|BAD",
    "Sources Interdites|Graines|Silvio|AUTOMNE|GOOD",
    "Sources Interdites|Huile|Gulatch|AUTOMNE|BEST",
    "Sources Interdites|Huile|Gulatch|AUTOMNE|GOOD",
    "Sources Interdites|Huile|Gulatch|PRINTEMPS|BEST",
    "Sources Interdites|Huile|Irin|AUTOMNE|BAD",
    "Sources Interdites|Huile|Irin|AUTOMNE|GOOD",
    "Sources Interdites|Huile|Koorin|AUTOMNE|BAD",
    "Sources Interdites|Huile|Koorin|ETE|BAD",
    "Sources Interdites|Huile|Koorin|PRINTEMPS|BAD",
    "Sources Interdites|Huile|Pilan|AUTOMNE|BAD",
    "Sources Interdites|Huile|Pilan|ETE|BAD",
    "Sources Interdites|Huile|Pilan|HIVER|BAD",
    "Sources Interdites|Huile|Pilan|PRINTEMPS|BAD",
    "Sources Interdites|Résine|Dung|AUTOMNE|BAD",
    "Sources Interdites|Résine|Dung|AUTOMNE|GOOD",
    "Sources Interdites|Résine|Dung|ETE|GOOD",
    "Sources Interdites|Résine|Dung|PRINTEMPS|GOOD",
    "Sources Interdites|Résine|Glue|AUTOMNE|BAD",
    "Sources Interdites|Résine|Glue|AUTOMNE|WORST",
    "Sources Interdites|Résine|Moon|AUTOMNE|BEST",
    "Sources Interdites|Résine|Moon|AUTOMNE|GOOD",
    "Sources Interdites|Sève|Dante|HIVER|BAD",
    "Sources Interdites|Sève|Visc|AUTOMNE|BAD",
    "Sources Interdites|Sève|Visc|AUTOMNE|BEST",
    "Sources Interdites|Sève|Visc|AUTOMNE|GOOD",
    "Sources Interdites|Sève|Visc|HIVER|GOOD",
    "Sources Interdites|Sève|Visc|PRINTEMPS|BAD",
    "Sources Interdites|Sève|Visc|PRINTEMPS|GOOD",
    "Sources Interdites|Écorce|Adriel|AUTOMNE|BAD",
    "Sources Interdites|Écorce|Adriel|AUTOMNE|GOOD",
    "Sources Interdites|Écorce|Adriel|ETE|BAD",
    "Sources Interdites|Écorce|Adriel|HIVER|BAD",
    "Sources Interdites|Écorce|Adriel|PRINTEMPS|BAD",
    "Sources Interdites|Écorce|Beckers|AUTOMNE|GOOD",
    "Sources Interdites|Écorce|Beckers|HIVER|GOOD",
    "Sources Interdites|Écorce|Beckers|PRINTEMPS|GOOD",
    "Sources Interdites|Écorce|Oath|AUTOMNE|BAD",
    "Sources Interdites|Écorce|Oath|ETE|BAD",
    "Sources Interdites|Écorce|Oath|HIVER|BAD",
    "Sources Interdites|Écorce|Oath|PRINTEMPS|BAD",
    "Sources Interdites|Écorce|Perfling|PRINTEMPS|BEST",
    "Sources Interdites|Écorce|Perfling|PRINTEMPS|GOOD",
    "Terre de la Continuité|Ambres|Hash|AUTOMNE|BAD",
    "Terre de la Continuité|Ambres|Sha|AUTOMNE|BAD",
    "Terre de la Continuité|Ambres|Sha|ETE|BAD",
    "Terre de la Continuité|Ambres|Sha|HIVER|BAD",
    "Terre de la Continuité|Ambres|Sha|PRINTEMPS|BAD",
    "Terre de la Continuité|Ambres|Soo|HIVER|BEST",
    "Terre de la Continuité|Bois|Eyota|HIVER|BAD",
    "Terre de la Continuité|Bois|Kachine|AUTOMNE|BAD",
    "Terre de la Continuité|Bois|Motega|HIVER|BAD",
    "Terre de la Continuité|Bois|Tama|ETE|BEST",
    "Terre de la Continuité|Boucles|Tansy|AUTOMNE|GOOD",
    "Terre de la Continuité|Boucles|Tansy|AUTOMNE|WORST",
    "Terre de la Continuité|Boucles|Tansy|HIVER|GOOD",
    "Terre de la Continuité|Boucles|Tansy|PRINTEMPS|GOOD",
    "Terre de la Continuité|Carapace|Big|ETE|BAD",
    "Terre de la Continuité|Carapace|Big|HIVER|BAD",
    "Terre de la Continuité|Carapace|Horny|PRINTEMPS|BAD",
    "Terre de la Continuité|Fibres|Anete|AUTOMNE|GOOD",
    "Terre de la Continuité|Fibres|Anete|HIVER|BAD",
    "Terre de la Continuité|Fibres|Anete|HIVER|GOOD",
    "Terre de la Continuité|Fibres|Anete|PRINTEMPS|GOOD",
    "Terre de la Continuité|Fibres|Buo|PRINTEMPS|GOOD",
    "Terre de la Continuité|Fibres|Shu|AUTOMNE|BAD",
    "Terre de la Continuité|Fibres|Shu|HIVER|BAD",
    "Terre de la Continuité|Graines|Caprice|AUTOMNE|GOOD",
    "Terre de la Continuité|Graines|Caprice|HIVER|GOOD",
    "Terre de la Continuité|Graines|Sarina|AUTOMNE|BAD",
    "Terre de la Continuité|Graines|Sarina|ETE|BAD",
    "Terre de la Continuité|Graines|Sarina|HIVER|BAD",
    "Terre de la Continuité|Graines|Sarina|PRINTEMPS|BAD",
    "Terre de la Continuité|Graines|Silvio|AUTOMNE|BAD",
    "Terre de la Continuité|Huile|Gulatch|ETE|BEST",
    "Terre de la Continuité|Huile|Gulatch|PRINTEMPS|GOOD",
    "Terre de la Continuité|Huile|Irin|ETE|GOOD",
    "Terre de la Continuité|Huile|Koorin|HIVER|BAD",
    "Terre de la Continuité|Huile|Koorin|HIVER|WORST",
    "Terre de la Continuité|Huile|Pilan|AUTOMNE|BAD",
    "Terre de la Continuité|Huile|Pilan|HIVER|BAD",
    "Terre de la Continuité|Résine|Glue|AUTOMNE|BAD",
    "Terre de la Continuité|Résine|Glue|ETE|BAD",
    "Terre de la Continuité|Résine|Glue|PRINTEMPS|BAD",
    "Terre de la Continuité|Résine|Moon|AUTOMNE|BAD",
    "Terre de la Continuité|Résine|Moon|HIVER|BAD",
    "Terre de la Continuité|Sève|Dante|HIVER|BAD",
    "Terre de la Continuité|Sève|Enola|AUTOMNE|BAD",
    "Terre de la Continuité|Sève|Enola|ETE|BAD",
    "Terre de la Continuité|Sève|Enola|HIVER|BAD",
    "Terre de la Continuité|Sève|Enola|PRINTEMPS|BAD",
    "Terre de la Continuité|Sève|Redhot|PRINTEMPS|BAD",
    "Terre de la Continuité|Sève|Visc|AUTOMNE|BAD",
    "Terre de la Continuité|Sève|Visc|HIVER|BAD",
    "Terre de la Continuité|Sève|Visc|PRINTEMPS|BAD",
    "Terre de la Continuité|Écorce|Adriel|PRINTEMPS|BEST",
    "Terre de la Continuité|Écorce|Adriel|PRINTEMPS|GOOD",
    "Terre de la Continuité|Écorce|Mitexi|AUTOMNE|BAD",
    "Terre de la Continuité|Écorce|Mitexi|ETE|BAD",
    "Terre de la Continuité|Écorce|Mitexi|HIVER|BAD",
    "Terre de la Continuité|Écorce|Mitexi|PRINTEMPS|BAD",
    "Cité Engloutie|Ambres|Beng|AUTOMNE|BAD",
    "Cité Engloutie|Ambres|Beng|ETE|BAD",
    "Cité Engloutie|Ambres|Beng|HIVER|BAD",
    "Cité Engloutie|Ambres|Beng|PRINTEMPS|BAD",
    "Cité Engloutie|Ambres|Hash|AUTOMNE|BAD",
    "Cité Engloutie|Ambres|Pha|AUTOMNE|BAD",
    "Cité Engloutie|Ambres|Pha|ETE|BAD",
    "Cité Engloutie|Ambres|Pha|HIVER|BAD",
    "Cité Engloutie|Ambres|Pha|PRINTEMPS|BAD",
    "Cité Engloutie|Ambres|Sha|AUTOMNE|GOOD",
    "Cité Engloutie|Ambres|Sha|ETE|BAD",
    "Cité Engloutie|Ambres|Sha|ETE|GOOD",
    "Cité Engloutie|Ambres|Sha|HIVER|GOOD",
    "Cité Engloutie|Ambres|Soo|AUTOMNE|GOOD",
    "Cité Engloutie|Ambres|Soo|HIVER|GOOD",
    "Cité Engloutie|Ambres|Zun|AUTOMNE|BAD",
    "Cité Engloutie|Ambres|Zun|AUTOMNE|WORST",
    "Cité Engloutie|Ambres|Zun|ETE|BAD",
    "Cité Engloutie|Ambres|Zun|ETE|GOOD",
    "Cité Engloutie|Ambres|Zun|ETE|WORST",
    "Cité Engloutie|Ambres|Zun|HIVER|BAD",
    "Cité Engloutie|Ambres|Zun|HIVER|WORST",
    "Cité Engloutie|Bois|Kachine|PRINTEMPS|WORST",
    "Cité Engloutie|Bois|Motega|HIVER|BEST",
    "Cité Engloutie|Carapace|Horny|AUTOMNE|BAD",
    "Cité Engloutie|Carapace|Horny|AUTOMNE|GOOD",
    "Cité Engloutie|Carapace|Horny|HIVER|BAD",
    "Cité Engloutie|Carapace|Splinter|AUTOMNE|BAD",
    "Cité Engloutie|Carapace|Splinter|ETE|BAD",
    "Cité Engloutie|Carapace|Splinter|PRINTEMPS|BAD",
    "Cité Engloutie|Carapace|Splinter|PRINTEMPS|WORST",
    "Cité Engloutie|Fibres|Buo|PRINTEMPS|GOOD",
    "Cité Engloutie|Fibres|Dzao|AUTOMNE|GOOD",
    "Cité Engloutie|Fibres|Dzao|HIVER|GOOD",
    "Cité Engloutie|Fibres|Dzao|PRINTEMPS|GOOD",
    "Cité Engloutie|Fibres|Shu|AUTOMNE|BAD",
    "Cité Engloutie|Fibres|Shu|ETE|BAD",
    "Cité Engloutie|Fibres|Shu|HIVER|BAD",
    "Cité Engloutie|Fibres|Shu|PRINTEMPS|BAD",
    "Cité Engloutie|Graines|Caprice|AUTOMNE|BAD",
    "Cité Engloutie|Graines|Caprice|PRINTEMPS|BAD",
    "Cité Engloutie|Graines|Sarina|AUTOMNE|BEST",
    "Cité Engloutie|Graines|Sarina|AUTOMNE|GOOD",
    "Cité Engloutie|Graines|Sarina|HIVER|GOOD",
    "Cité Engloutie|Graines|Saurona|AUTOMNE|GOOD",
    "Cité Engloutie|Graines|Saurona|PRINTEMPS|GOOD",
    "Cité Engloutie|Graines|Silvio|AUTOMNE|BAD",
    "Cité Engloutie|Huile|Irin|HIVER|GOOD",
    "Cité Engloutie|Huile|Koorin|AUTOMNE|BEST",
    "Cité Engloutie|Huile|Koorin|AUTOMNE|GOOD",
    "Cité Engloutie|Huile|Koorin|ETE|BEST",
    "Cité Engloutie|Huile|Koorin|ETE|GOOD",
    "Cité Engloutie|Huile|Koorin|PRINTEMPS|GOOD",
    "Cité Engloutie|Résine|Dung|AUTOMNE|BAD",
    "Cité Engloutie|Résine|Glue|AUTOMNE|BEST",
    "Cité Engloutie|Résine|Glue|AUTOMNE|GOOD",
    "Cité Engloutie|Résine|Glue|ETE|BEST",
    "Cité Engloutie|Résine|Glue|ETE|GOOD",
    "Cité Engloutie|Résine|Moon|HIVER|BAD",
    "Cité Engloutie|Résine|Moon|PRINTEMPS|BAD",
    "Cité Engloutie|Sève|Dante|AUTOMNE|BAD",
    "Cité Engloutie|Sève|Dante|ETE|BAD",
    "Cité Engloutie|Sève|Dante|HIVER|BAD",
    "Cité Engloutie|Sève|Dante|PRINTEMPS|BAD",
    "Cité Engloutie|Sève|Redhot|AUTOMNE|GOOD",
    "Cité Engloutie|Sève|Redhot|ETE|GOOD",
    "Cité Engloutie|Sève|Visc|PRINTEMPS|WORST",
    "Cité Engloutie|Écorce|Beckers|HIVER|GOOD",
    "Cité Engloutie|Écorce|Oath|AUTOMNE|GOOD",
    "Cité Engloutie|Écorce|Oath|HIVER|GOOD",
    "Cité Engloutie|Écorce|Oath|PRINTEMPS|GOOD",
    "Profondeurs Interdites|Ambres|Hash|AUTOMNE|BAD",
    "Profondeurs Interdites|Ambres|Hash|ETE|BAD",
    "Profondeurs Interdites|Ambres|Hash|HIVER|BAD",
    "Profondeurs Interdites|Ambres|Hash|PRINTEMPS|BAD",
    "Profondeurs Interdites|Ambres|Pha|AUTOMNE|BAD",
    "Profondeurs Interdites|Ambres|Pha|ETE|BAD",
    "Profondeurs Interdites|Ambres|Pha|HIVER|BAD",
    "Profondeurs Interdites|Ambres|Pha|PRINTEMPS|BAD",
    "Profondeurs Interdites|Ambres|Sha|AUTOMNE|BAD",
    "Profondeurs Interdites|Ambres|Sha|ETE|BAD",
    "Profondeurs Interdites|Ambres|Sha|HIVER|BAD",
    "Profondeurs Interdites|Ambres|Sha|PRINTEMPS|BAD",
    "Profondeurs Interdites|Ambres|Soo|AUTOMNE|BAD",
    "Profondeurs Interdites|Ambres|Soo|ETE|BAD",
    "Profondeurs Interdites|Ambres|Soo|HIVER|BAD",
    "Profondeurs Interdites|Ambres|Soo|PRINTEMPS|BAD",
    "Profondeurs Interdites|Ambres|Zun|AUTOMNE|BAD",
    "Profondeurs Interdites|Ambres|Zun|ETE|BAD",
    "Profondeurs Interdites|Ambres|Zun|HIVER|BAD",
    "Profondeurs Interdites|Ambres|Zun|PRINTEMPS|BAD",
    "Profondeurs Interdites|Bois|Abhaya|AUTOMNE|BAD",
    "Profondeurs Interdites|Bois|Abhaya|HIVER|BAD",
    "Profondeurs Interdites|Bois|Abhaya|PRINTEMPS|BAD",
    "Profondeurs Interdites|Bois|Motega|AUTOMNE|GOOD",
    "Profondeurs Interdites|Bois|Motega|PRINTEMPS|GOOD",
    "Profondeurs Interdites|Bois|Tama|HIVER|BAD",
    "Profondeurs Interdites|Boucles|Patee|AUTOMNE|GOOD",
    "Profondeurs Interdites|Boucles|Patee|HIVER|GOOD",
    "Profondeurs Interdites|Boucles|Scrath|AUTOMNE|GOOD",
    "Profondeurs Interdites|Boucles|Scrath|ETE|GOOD",
    "Profondeurs Interdites|Boucles|Scrath|HIVER|GOOD",
    "Profondeurs Interdites|Boucles|Scrath|PRINTEMPS|GOOD",
    "Profondeurs Interdites|Boucles|Tansy|AUTOMNE|GOOD",
    "Profondeurs Interdites|Boucles|Tansy|HIVER|GOOD",
    "Profondeurs Interdites|Carapace|Big|AUTOMNE|GOOD",
    "Profondeurs Interdites|Carapace|Big|ETE|GOOD",
    "Profondeurs Interdites|Carapace|Cuty|AUTOMNE|BAD",
    "Profondeurs Interdites|Carapace|Cuty|ETE|BAD",
    "Profondeurs Interdites|Carapace|Cuty|HIVER|BAD",
    "Profondeurs Interdites|Carapace|Cuty|PRINTEMPS|BAD",
    "Profondeurs Interdites|Fibres|Buo|AUTOMNE|BAD",
    "Profondeurs Interdites|Fibres|Buo|HIVER|BAD",
    "Profondeurs Interdites|Fibres|Buo|PRINTEMPS|BAD",
    "Profondeurs Interdites|Fibres|Dzao|AUTOMNE|BAD",
    "Profondeurs Interdites|Graines|Sarina|AUTOMNE|BAD",
    "Profondeurs Interdites|Graines|Sarina|AUTOMNE|GOOD",
    "Profondeurs Interdites|Graines|Sarina|ETE|BAD",
    "Profondeurs Interdites|Graines|Sarina|HIVER|BAD",
    "Profondeurs Interdites|Graines|Sarina|PRINTEMPS|BAD",
    "Profondeurs Interdites|Graines|Saurona|AUTOMNE|BAD",
    "Profondeurs Interdites|Graines|Saurona|AUTOMNE|GOOD",
    "Profondeurs Interdites|Graines|Saurona|ETE|BAD",
    "Profondeurs Interdites|Graines|Saurona|HIVER|BAD",
    "Profondeurs Interdites|Graines|Saurona|PRINTEMPS|BAD",
    "Profondeurs Interdites|Huile|Gulatch|AUTOMNE|GOOD",
    "Profondeurs Interdites|Huile|Gulatch|ETE|GOOD",
    "Profondeurs Interdites|Huile|Gulatch|PRINTEMPS|GOOD",
    "Profondeurs Interdites|Huile|Pilan|AUTOMNE|BAD",
    "Profondeurs Interdites|Huile|Pilan|ETE|BAD",
    "Profondeurs Interdites|Huile|Pilan|HIVER|BAD",
    "Profondeurs Interdites|Huile|Pilan|PRINTEMPS|BAD",
    "Profondeurs Interdites|Résine|Dung|AUTOMNE|BAD",
    "Profondeurs Interdites|Résine|Dung|ETE|BAD",
    "Profondeurs Interdites|Résine|Dung|HIVER|BAD",
    "Profondeurs Interdites|Résine|Dung|PRINTEMPS|BAD",
    "Profondeurs Interdites|Résine|Fung|AUTOMNE|BAD",
    "Profondeurs Interdites|Résine|Fung|HIVER|BAD",
    "Profondeurs Interdites|Résine|Fung|PRINTEMPS|BAD",
    "Profondeurs Interdites|Résine|Glue|HIVER|BEST",
    "Profondeurs Interdites|Résine|Moon|AUTOMNE|BAD",
    "Profondeurs Interdites|Résine|Moon|ETE|BAD",
    "Profondeurs Interdites|Résine|Moon|HIVER|BAD",
    "Profondeurs Interdites|Résine|Moon|PRINTEMPS|BAD",
    "Profondeurs Interdites|Sève|Silverweed|AUTOMNE|GOOD",
    "Profondeurs Interdites|Écorce|Adriel|AUTOMNE|BAD",
    "Profondeurs Interdites|Écorce|Adriel|ETE|BAD",
    "Profondeurs Interdites|Écorce|Adriel|HIVER|BAD",
    "Profondeurs Interdites|Écorce|Adriel|PRINTEMPS|BAD",
    "Profondeurs Interdites|Écorce|Oath|ETE|BAD",
)

/** Les croix oranges : rapportées d'une autre source, jamais vues en jeu. */
internal val RELEVE_A_CONFIRMER: List<String> = listOf(
    "Sources Interdites|Ambres|Sha|ETE|BAD",
    "Sources Interdites|Ambres|Sha|ETE|WORST",
    "Sources Interdites|Boucles|Scrath|ETE|GOOD",
    "Sources Interdites|Carapace|Big|AUTOMNE|BEST",
    "Sources Interdites|Carapace|Big|ETE|BAD",
    "Sources Interdites|Carapace|Big|PRINTEMPS|BAD",
    "Sources Interdites|Carapace|Cuty|AUTOMNE|BEST",
    "Sources Interdites|Carapace|Cuty|ETE|BAD",
    "Sources Interdites|Carapace|Cuty|PRINTEMPS|BAD",
    "Sources Interdites|Carapace|Horny|PRINTEMPS|BAD",
    "Sources Interdites|Fibres|Shu|ETE|BAD",
    "Sources Interdites|Fibres|Shu|HIVER|BEST",
    "Sources Interdites|Fibres|Shu|PRINTEMPS|BAD",
    "Sources Interdites|Huile|Irin|AUTOMNE|BAD",
    "Sources Interdites|Huile|Koorin|PRINTEMPS|BAD",
    "Sources Interdites|Huile|Pilan|ETE|BAD",
    "Sources Interdites|Huile|Pilan|PRINTEMPS|BAD",
    "Sources Interdites|Résine|Dung|AUTOMNE|BAD",
    "Sources Interdites|Résine|Dung|ETE|GOOD",
    "Sources Interdites|Sève|Visc|AUTOMNE|BAD",
    "Sources Interdites|Écorce|Adriel|AUTOMNE|GOOD",
    "Sources Interdites|Écorce|Adriel|ETE|BAD",
    "Sources Interdites|Écorce|Adriel|PRINTEMPS|BAD",
    "Sources Interdites|Écorce|Oath|ETE|BAD",
    "Terre de la Continuité|Ambres|Sha|PRINTEMPS|BAD",
    "Terre de la Continuité|Bois|Eyota|HIVER|BAD",
    "Terre de la Continuité|Bois|Tama|ETE|BEST",
    "Terre de la Continuité|Boucles|Tansy|AUTOMNE|WORST",
    "Terre de la Continuité|Boucles|Tansy|PRINTEMPS|GOOD",
    "Terre de la Continuité|Carapace|Big|ETE|BAD",
    "Terre de la Continuité|Fibres|Anete|HIVER|BAD",
    "Terre de la Continuité|Fibres|Shu|HIVER|BAD",
    "Terre de la Continuité|Graines|Sarina|AUTOMNE|BAD",
    "Terre de la Continuité|Graines|Sarina|ETE|BAD",
    "Terre de la Continuité|Graines|Sarina|HIVER|BAD",
    "Terre de la Continuité|Graines|Sarina|PRINTEMPS|BAD",
    "Terre de la Continuité|Huile|Gulatch|ETE|BEST",
    "Terre de la Continuité|Résine|Glue|AUTOMNE|BAD",
    "Terre de la Continuité|Résine|Glue|ETE|BAD",
    "Terre de la Continuité|Résine|Glue|PRINTEMPS|BAD",
    "Terre de la Continuité|Résine|Moon|AUTOMNE|BAD",
    "Terre de la Continuité|Sève|Enola|AUTOMNE|BAD",
    "Terre de la Continuité|Sève|Enola|ETE|BAD",
    "Terre de la Continuité|Sève|Enola|PRINTEMPS|BAD",
    "Terre de la Continuité|Écorce|Mitexi|AUTOMNE|BAD",
    "Terre de la Continuité|Écorce|Mitexi|ETE|BAD",
    "Terre de la Continuité|Écorce|Mitexi|HIVER|BAD",
    "Terre de la Continuité|Écorce|Mitexi|PRINTEMPS|BAD",
    "Cité Engloutie|Ambres|Beng|AUTOMNE|BAD",
    "Cité Engloutie|Ambres|Beng|ETE|BAD",
    "Cité Engloutie|Ambres|Beng|PRINTEMPS|BAD",
    "Cité Engloutie|Ambres|Pha|AUTOMNE|BAD",
    "Cité Engloutie|Ambres|Pha|ETE|BAD",
    "Cité Engloutie|Ambres|Pha|HIVER|BAD",
    "Cité Engloutie|Ambres|Pha|PRINTEMPS|BAD",
    "Cité Engloutie|Ambres|Sha|ETE|BAD",
    "Cité Engloutie|Ambres|Sha|ETE|GOOD",
    "Cité Engloutie|Ambres|Zun|ETE|GOOD",
    "Cité Engloutie|Carapace|Horny|AUTOMNE|BAD",
    "Cité Engloutie|Carapace|Splinter|AUTOMNE|BAD",
    "Cité Engloutie|Carapace|Splinter|ETE|BAD",
    "Cité Engloutie|Carapace|Splinter|PRINTEMPS|BAD",
    "Cité Engloutie|Fibres|Shu|ETE|BAD",
    "Cité Engloutie|Fibres|Shu|HIVER|BAD",
    "Cité Engloutie|Graines|Sarina|HIVER|GOOD",
    "Cité Engloutie|Huile|Koorin|AUTOMNE|BEST",
    "Cité Engloutie|Huile|Koorin|ETE|BEST",
    "Cité Engloutie|Huile|Koorin|ETE|GOOD",
    "Cité Engloutie|Sève|Dante|AUTOMNE|BAD",
    "Cité Engloutie|Sève|Dante|ETE|BAD",
    "Cité Engloutie|Sève|Dante|HIVER|BAD",
    "Cité Engloutie|Sève|Dante|PRINTEMPS|BAD",
    "Cité Engloutie|Sève|Redhot|ETE|GOOD",
    "Cité Engloutie|Écorce|Oath|AUTOMNE|GOOD",
    "Cité Engloutie|Écorce|Oath|HIVER|GOOD",
    "Cité Engloutie|Écorce|Oath|PRINTEMPS|GOOD",
    "Profondeurs Interdites|Ambres|Hash|AUTOMNE|BAD",
    "Profondeurs Interdites|Ambres|Hash|ETE|BAD",
    "Profondeurs Interdites|Ambres|Hash|PRINTEMPS|BAD",
    "Profondeurs Interdites|Ambres|Pha|ETE|BAD",
    "Profondeurs Interdites|Ambres|Pha|PRINTEMPS|BAD",
    "Profondeurs Interdites|Ambres|Sha|AUTOMNE|BAD",
    "Profondeurs Interdites|Ambres|Sha|ETE|BAD",
    "Profondeurs Interdites|Ambres|Sha|HIVER|BAD",
    "Profondeurs Interdites|Ambres|Soo|AUTOMNE|BAD",
    "Profondeurs Interdites|Ambres|Soo|ETE|BAD",
    "Profondeurs Interdites|Ambres|Soo|HIVER|BAD",
    "Profondeurs Interdites|Ambres|Soo|PRINTEMPS|BAD",
    "Profondeurs Interdites|Ambres|Zun|AUTOMNE|BAD",
    "Profondeurs Interdites|Ambres|Zun|ETE|BAD",
    "Profondeurs Interdites|Ambres|Zun|PRINTEMPS|BAD",
    "Profondeurs Interdites|Bois|Abhaya|AUTOMNE|BAD",
    "Profondeurs Interdites|Bois|Abhaya|HIVER|BAD",
    "Profondeurs Interdites|Bois|Abhaya|PRINTEMPS|BAD",
    "Profondeurs Interdites|Bois|Motega|AUTOMNE|GOOD",
    "Profondeurs Interdites|Bois|Motega|PRINTEMPS|GOOD",
    "Profondeurs Interdites|Boucles|Scrath|AUTOMNE|GOOD",
    "Profondeurs Interdites|Boucles|Scrath|ETE|GOOD",
    "Profondeurs Interdites|Boucles|Scrath|HIVER|GOOD",
    "Profondeurs Interdites|Boucles|Scrath|PRINTEMPS|GOOD",
    "Profondeurs Interdites|Boucles|Tansy|AUTOMNE|GOOD",
    "Profondeurs Interdites|Boucles|Tansy|HIVER|GOOD",
    "Profondeurs Interdites|Carapace|Big|AUTOMNE|GOOD",
    "Profondeurs Interdites|Carapace|Big|ETE|GOOD",
    "Profondeurs Interdites|Carapace|Cuty|AUTOMNE|BAD",
    "Profondeurs Interdites|Carapace|Cuty|ETE|BAD",
    "Profondeurs Interdites|Carapace|Cuty|HIVER|BAD",
    "Profondeurs Interdites|Carapace|Cuty|PRINTEMPS|BAD",
    "Profondeurs Interdites|Fibres|Buo|AUTOMNE|BAD",
    "Profondeurs Interdites|Fibres|Buo|HIVER|BAD",
    "Profondeurs Interdites|Fibres|Dzao|AUTOMNE|BAD",
    "Profondeurs Interdites|Graines|Sarina|AUTOMNE|BAD",
    "Profondeurs Interdites|Graines|Sarina|ETE|BAD",
    "Profondeurs Interdites|Graines|Sarina|HIVER|BAD",
    "Profondeurs Interdites|Graines|Sarina|PRINTEMPS|BAD",
    "Profondeurs Interdites|Graines|Saurona|AUTOMNE|BAD",
    "Profondeurs Interdites|Graines|Saurona|ETE|BAD",
    "Profondeurs Interdites|Graines|Saurona|HIVER|BAD",
    "Profondeurs Interdites|Graines|Saurona|PRINTEMPS|BAD",
    "Profondeurs Interdites|Huile|Gulatch|ETE|GOOD",
    "Profondeurs Interdites|Huile|Pilan|AUTOMNE|BAD",
    "Profondeurs Interdites|Huile|Pilan|ETE|BAD",
    "Profondeurs Interdites|Huile|Pilan|HIVER|BAD",
    "Profondeurs Interdites|Huile|Pilan|PRINTEMPS|BAD",
    "Profondeurs Interdites|Résine|Dung|AUTOMNE|BAD",
    "Profondeurs Interdites|Résine|Dung|ETE|BAD",
    "Profondeurs Interdites|Résine|Dung|HIVER|BAD",
    "Profondeurs Interdites|Résine|Dung|PRINTEMPS|BAD",
    "Profondeurs Interdites|Résine|Fung|AUTOMNE|BAD",
    "Profondeurs Interdites|Résine|Fung|HIVER|BAD",
    "Profondeurs Interdites|Résine|Fung|PRINTEMPS|BAD",
    "Profondeurs Interdites|Résine|Moon|AUTOMNE|BAD",
    "Profondeurs Interdites|Résine|Moon|ETE|BAD",
    "Profondeurs Interdites|Résine|Moon|HIVER|BAD",
    "Profondeurs Interdites|Sève|Silverweed|AUTOMNE|GOOD",
    "Profondeurs Interdites|Écorce|Adriel|AUTOMNE|BAD",
    "Profondeurs Interdites|Écorce|Adriel|ETE|BAD",
    "Profondeurs Interdites|Écorce|Adriel|HIVER|BAD",
    "Profondeurs Interdites|Écorce|Adriel|PRINTEMPS|BAD",
)
