package net.ryzom.zyroom.model

// Fichier produit par outils/table_pop.py — ne pas modifier à la main.

/**
 * Ce qui peut apparaître, par saison, par zone et par condition météo.
 *
 * Le relevé est celui de La Lune Eternelle, et c'est la seule source connue
 * pour cette correspondance : les sites publics disent quelles matières sont
 * suprêmes à une saison, jamais dans quelle météo elles sortent.
 *
 * Il est **incomplet par construction** — il se remplit au fil des sorties des
 * joueurs. Une case vide veut donc dire « pas encore relevé », et non « rien ».
 */
val POP: Map<String, Map<String, Map<String, Map<String, List<String>>>>> = mapOf(
    "PRINTEMPS" to mapOf(
        "Sources Interdites" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Beng", "Pha", "Sha", "Zun"),
                "Graines" to listOf("Caprice", "Silvio"),
                "Fibres" to listOf("Anète", "Buo"),
                "Résine" to listOf("Dung", "Colle", "Lune"),
                "Huile" to listOf("Gulatch", "Irin", "Pilan"),
                "Sève" to listOf("Dante", "Ardente", "Silverweed"),
                "Carapace" to listOf("Mignonne", "Inteligente"),
                "Écorce" to listOf("Beckers", "Oath", "Perfling"),
                "Bois" to listOf("Eyota", "Kachine", "Tama"),
                "Boucles" to listOf("Nita", "Patee", "Scratch", "Yana"),
            ),
            "BAD" to mapOf(
                "Ambres" to listOf("Soo", "Hash"),
                "Écorce" to listOf("Adriel"),
                "Boucles" to listOf("Tansy"),
            ),
            "GOOD" to mapOf(
                "Graines" to listOf("Saurona", "Sarina"),
                "Carapace" to listOf("Splinter", "Cornée"),
                "Résine" to listOf("Fung"),
                "Huile" to listOf("Enola", "Koorin"),
                "Bois" to listOf("Motega"),
                "Fibres" to listOf("Dzao"),
                "Sève" to listOf("Visc"),
            ),
            "BEST" to mapOf(
                "Carapace" to listOf("Grosse"),
                "Fibres" to listOf("Shu"),
                "Bois" to listOf("Abhaya"),
                "Écorce" to listOf("Mitexi"),
            ),
        ),
        "Terre de la Continuité" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Hash", "Pha", "Sha", "Zun"),
                "Graines" to listOf("Caprice", "Sarina", "Silvio"),
                "Fibres" to listOf("Shu"),
                "Résine" to listOf("Colle", "Lune"),
                "Huile" to listOf("Irin", "Koorin", "Pilan"),
                "Sève" to listOf("Dante", "Enola"),
                "Carapace" to listOf("Grosse", "Cornée", "Inteligente", "Splinter"),
                "Écorce" to listOf("Adriel", "Beckers"),
                "Bois" to listOf("Motega"),
                "Boucles" to listOf("Nita", "Patee", "Scratch"),
            ),
            "BAD" to mapOf(
                "Écorce" to listOf("Perfling"),
                "Bois" to listOf("Eyota"),
                "Carapace" to listOf("Mignonne"),
            ),
            "GOOD" to mapOf(
                "Boucles" to listOf("Tansy", "Yana"),
                "Résine" to listOf("Fung"),
                "Huile" to listOf("Gulatch"),
                "Sève" to listOf("Ardente", "Silverweed"),
                "Bois" to listOf("Abhaya", "Tama"),
                "Ambres" to listOf("Soo"),
            ),
            "BEST" to mapOf(
                "Fibres" to listOf("Anète", "Buo", "Dzao"),
                "Sève" to listOf("Visc"),
                "Écorce" to listOf("Oath"),
                "Graines" to listOf("Saurona"),
                "Bois" to listOf("Kachine"),
                "Ambres" to listOf("Beng"),
                "Résine" to listOf("Dung"),
                "Boucles" to listOf("Scratch"),
            ),
        ),
        "Cité Engloutie" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Pha"),
                "Graines" to listOf("Caprice", "Saurona", "Silvio"),
                "Fibres" to listOf("Anète", "Buo", "Dzao", "Shu"),
                "Résine" to listOf("Dung", "Colle", "Lune"),
                "Huile" to listOf("Gulatch", "Koorin"),
                "Sève" to listOf("Dante"),
                "Carapace" to listOf("Grosse", "Cornée", "Inteligente", "Splinter"),
                "Écorce" to listOf("Adriel", "Beckers", "Mitexi"),
                "Bois" to listOf("Abhaya", "Tama"),
                "Boucles" to listOf("Nita", "Patee", "Scratch", "Tansy"),
            ),
            "BAD" to mapOf(
                "Bois" to listOf("Eyota", "Kachine"),
                "Boucles" to listOf("Yana ?"),
                "Graines" to listOf("Sarina"),
                "Huile" to listOf("Irin"),
            ),
            "GOOD" to mapOf(
                "Carapace" to listOf("Mignonne"),
                "Boucles" to listOf("Yana ?"),
                "Résine" to listOf("Fung"),
                "Huile" to listOf("Pilan"),
                "Sève" to listOf("Enola", "Visc agro KKT"),
                "Ambres" to listOf("Beng"),
            ),
            "BEST" to mapOf(
                "Ambres" to listOf("Soo", "Hash", "Zun", "Sha"),
                "Sève" to listOf("Ardente", "Silverweed"),
                "Écorce" to listOf("Oath", "Perfling"),
                "Bois" to listOf("Motega"),
            ),
        ),
        "Profondeurs Interdites" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Beng Agro", "Pha"),
                "Graines" to listOf("Sarina", "Silvio"),
                "Fibres" to listOf("Anète", "Buo"),
                "Résine" to listOf("Dung", "Lune"),
                "Huile" to listOf("Gulatch", "Irin", "Koorin"),
                "Sève" to listOf("Dante", "Silverweed"),
                "Carapace" to listOf("Mignonne", "Cornée", "Inteligente"),
                "Écorce" to listOf("Adriel", "Mitexi", "Perfling"),
                "Bois" to listOf("Tama"),
                "Boucles" to listOf("Nita", "Patee", "Scratch", "Tansy"),
            ),
            "BAD" to mapOf(
                "Ambres" to listOf("Hash"),
                "Sève" to listOf("Enola", "Ardente ?"),
                "Écorce" to listOf("Oath"),
                "Bois" to listOf("Kachine"),
                "Huile" to listOf("Pilan"),
                "Carapace" to listOf("Grosse"),
            ),
            "GOOD" to mapOf(
                "Carapace" to listOf("Splinter"),
                "Boucles" to listOf("Yana"),
                "Résine" to listOf("Fung", "Colle"),
                "Sève" to listOf("Ardente ?", "Visc"),
                "Bois" to listOf("Motega", "Abhaya"),
                "Ambres" to listOf("Soo"),
            ),
            "BEST" to mapOf(
                "Ambres" to listOf("Sha", "Zun"),
                "Fibres" to listOf("Dzao", "Shu"),
                "Écorce" to listOf("Beckers"),
                "Graines" to listOf("Saurona", "Caprice"),
                "Bois" to listOf("Eyota"),
                "Sève" to listOf("Ardente ?"),
            ),
        ),
    ),
    "ETE" to mapOf(
        "Sources Interdites" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Beng", "Pha", "Sha", "Zun"),
                "Graines" to listOf("Caprice", "Silvio"),
                "Fibres" to listOf("Anète", "Buo"),
                "Résine" to listOf("Dung", "Colle", "Lune"),
                "Huile" to listOf("Gulatch", "Irin", "Pilan"),
                "Sève" to listOf("Dante", "Ardente", "Silverweed"),
                "Carapace" to listOf("Mignonne", "Inteligente"),
                "Écorce" to listOf("Beckers", "Oath", "Perfling"),
                "Bois" to listOf("Eyota", "Kachine", "Tama"),
                "Boucles" to listOf("Nita", "Patee", "Scratch", "Yana"),
            ),
            "BAD" to mapOf(
                "Ambres" to listOf("Hash"),
                "Écorce" to listOf("Adriel"),
                "Boucles" to listOf("Tansy"),
            ),
            "GOOD" to mapOf(
                "Graines" to listOf("Sarina"),
                "Carapace" to listOf("Cornée"),
                "Résine" to listOf("Fung"),
                "Huile" to listOf("Enola"),
                "Bois" to listOf("Motega"),
            ),
            "BEST" to mapOf(
                "Fibres" to listOf("Shu"),
                "Bois" to listOf("Abhaya"),
                "Carapace" to listOf("Grosse"),
                "Écorce" to listOf("Mitexi"),
            ),
        ),
        "Terre de la Continuité" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Hash", "Pha", "Sha", "Zun"),
                "Graines" to listOf("Caprice", "Sarina", "Silvio"),
                "Fibres" to listOf("Shu"),
                "Résine" to listOf("Colle", "Lune"),
                "Huile" to listOf("Irin", "Koorin", "Pilan"),
                "Sève" to listOf("Dante", "Enola"),
                "Carapace" to listOf("Grosse", "Cornée", "Inteligente", "Splinter"),
                "Écorce" to listOf("Adriel", "Beckers"),
                "Bois" to listOf("Motega"),
                "Boucles" to listOf("Nita", "Patee", "Scratch"),
            ),
            "BAD" to mapOf(
                "Bois" to listOf("Eyota"),
                "Carapace" to listOf("Migno Omg AGGRO"),
                "Écorce" to listOf("Perfling"),
            ),
            "GOOD" to mapOf(
                "Résine" to listOf("Fung"),
                "Huile" to listOf("Gulatch"),
                "Sève" to listOf("Ardente", "Silverweed"),
                "Bois" to listOf("Abhaya", "Tama"),
                "Ambres" to listOf("Soo"),
                "Boucles" to listOf("Tansy", "Yana"),
            ),
            "BEST" to mapOf(
                "Graines" to listOf("Saurona"),
                "Fibres" to listOf("Anète", "Dzao", "Buo"),
                "Bois" to listOf("Kachine"),
                "Ambres" to listOf("Beng"),
                "Résine" to listOf("Dung"),
                "Sève" to listOf("Visc"),
                "Boucles" to listOf("Scratch"),
                "Écorce" to listOf("Oath"),
            ),
        ),
        "Cité Engloutie" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Pha"),
                "Graines" to listOf("Caprice", "Saurona", "Silvio"),
                "Fibres" to listOf("Anète", "Buo", "Dzao", "Shu"),
                "Résine" to listOf("Dung", "Colle", "Lune"),
                "Huile" to listOf("Gulatch", "Koorin"),
                "Sève" to listOf("Dante"),
                "Carapace" to listOf("Grosse", "Cornée", "Inteligente", "Splinter"),
                "Écorce" to listOf("Adriel", "Beckers", "Mitexi"),
                "Bois" to listOf("Abhaya", "Tama"),
                "Boucles" to listOf("Nita", "Patee", "Scratch", "Tansy"),
            ),
            "BAD" to mapOf(
                "Graines" to listOf("Sarina"),
                "Bois" to listOf("Kachine", "Eyota"),
                "Huile" to listOf("Irin"),
                "Boucles" to listOf("Yana ?"),
            ),
            "GOOD" to mapOf(
                "Résine" to listOf("Fung"),
                "Huile" to listOf("Pilan"),
                "Sève" to listOf("Enola", "Visc agro KKT"),
                "Ambres" to listOf("Beng"),
                "Carapace" to listOf("Mignonne"),
                "Boucles" to listOf("Yana ?"),
            ),
            "BEST" to mapOf(
                "Ambres" to listOf("Hash", "Soo", "Zun", "Sha"),
                "Sève" to listOf("Ardente", "Silverweed"),
                "Écorce" to listOf("Oath", "Perfling"),
                "Bois" to listOf("Motega"),
            ),
        ),
        "Profondeurs Interdites" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Beng", "Pha"),
                "Graines" to listOf("Sarina", "Silvio"),
                "Fibres" to listOf("Anète", "Buo"),
                "Résine" to listOf("Dung", "Lune"),
                "Huile" to listOf("Gulatch", "Irin", "Koorin"),
                "Sève" to listOf("Dante", "Silverweed"),
                "Carapace" to listOf("Mignonne", "Cornée", "Inteligente"),
                "Écorce" to listOf("Adriel", "Mitexi", "Perfling"),
                "Bois" to listOf("Tama"),
                "Boucles" to listOf("Nita", "Patee", "Scratch", "Tansy"),
            ),
            "BAD" to mapOf(
                "Écorce" to listOf("Oath"),
                "Bois" to listOf("Kachine"),
                "Sève" to listOf("Ardente", "Enola"),
                "Huile" to listOf("Pilan"),
                "Carapace" to listOf("Grosse"),
                "Ambres" to listOf("Hash"),
            ),
            "GOOD" to mapOf(
                "Résine" to listOf("Fung", "Colle"),
                "Bois" to listOf("Motega", "Abhaya"),
                "Sève" to listOf("Visc"),
                "Ambres" to listOf("Soo"),
                "Carapace" to listOf("Splinter"),
                "Boucles" to listOf("Yana"),
            ),
            "BEST" to mapOf(
                "Ambres" to listOf("Sha", "Zun"),
                "Graines" to listOf("Saurona", "Caprice"),
                "Fibres" to listOf("Shu", "Dzao"),
                "Bois" to listOf("Eyota"),
                "Écorce" to listOf("Beckers"),
            ),
        ),
    ),
    "AUTOMNE" to mapOf(
        "Sources Interdites" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Beng", "Pha", "Sha", "Zun"),
                "Graines" to listOf("Caprice", "Silvio"),
                "Fibres" to listOf("Anète", "Buo"),
                "Résine" to listOf("Dung", "Colle", "Lune"),
                "Huile" to listOf("Gulatch", "Irin", "Pilan"),
                "Sève" to listOf("Dante", "Redhot", "Silverweed"),
                "Carapace" to listOf("Mignonne", "Inteligente"),
                "Écorce" to listOf("Beckers", "Oath", "Perfling"),
                "Bois" to listOf("Eyota", "Kachine", "Tama"),
                "Boucles" to listOf("Nita", "Patee", "Scratch", "Yana"),
            ),
            "BAD" to mapOf(
                "Boucles" to listOf("Tansy"),
                "Ambres" to listOf("Soo", "Hash"),
                "Écorce" to listOf("Adriel"),
            ),
            "GOOD" to mapOf(
                "Résine" to listOf("Fung"),
                "Huile" to listOf("Enola", "Koorin"),
                "Bois" to listOf("Motega"),
                "Fibres" to listOf("Dzao"),
                "Sève" to listOf("Visc"),
                "Graines" to listOf("Saurona", "Sarina"),
                "Carapace" to listOf("Splinter", "Cornée"),
            ),
            "BEST" to mapOf(
                "Carapace" to listOf("Grosse"),
                "Écorce" to listOf("Mitexi"),
                "Bois" to listOf("Abhaya"),
                "Fibres" to listOf("Shu"),
            ),
        ),
        "Terre de la Continuité" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Hash", "Pha", "Sha", "Zun"),
                "Graines" to listOf("Caprice", "Sarina", "Silvio"),
                "Fibres" to listOf("Shu"),
                "Résine" to listOf("Colle", "Lune"),
                "Huile" to listOf("Irin", "Koorin", "Pilan"),
                "Sève" to listOf("Dante", "Enola"),
                "Carapace" to listOf("Grosse", "Cornée", "Inteligente", "Splinter"),
                "Écorce" to listOf("Adriel", "Beckers"),
                "Bois" to listOf("Motega"),
                "Boucles" to listOf("Nita", "Patee", "Scratch"),
            ),
            "BAD" to mapOf(
                "Carapace" to listOf("Mignonne"),
                "Écorce" to listOf("Perfling"),
                "Bois" to listOf("Eyota"),
            ),
            "GOOD" to mapOf(
                "Sève" to listOf("Ardente", "Silverweed"),
                "Bois" to listOf("Abhaya", "Tama"),
                "Ambres" to listOf("Soo"),
                "Boucles" to listOf("Tansy", "Yana"),
                "Résine" to listOf("Fung"),
                "Huile" to listOf("Gulatch"),
            ),
            "BEST" to mapOf(
                "Ambres" to listOf("Beng"),
                "Graines" to listOf("Saurona"),
                "Fibres" to listOf("Dzao", "Buo", "Anète"),
                "Résine" to listOf("Dung"),
                "Sève" to listOf("Visc"),
                "Bois" to listOf("Kachine"),
                "Boucles" to listOf("Scratch"),
                "Écorce" to listOf("Oath"),
            ),
        ),
        "Cité Engloutie" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Pha"),
                "Graines" to listOf("Caprice", "Saurona", "Silvio"),
                "Fibres" to listOf("Anète", "Buo", "Dzao", "Shu"),
                "Résine" to listOf("Dung", "Colle", "Lune"),
                "Huile" to listOf("Gulatch", "Koorin"),
                "Sève" to listOf("Dante"),
                "Carapace" to listOf("Grosse", "Cornée", "Inteligente", "Splinter"),
                "Écorce" to listOf("Adriel", "Beckers", "Mitexi"),
                "Bois" to listOf("Abhaya", "Tama"),
                "Boucles" to listOf("Nita", "Patee", "Scratch", "Tansy"),
            ),
            "BAD" to mapOf(
                "Huile" to listOf("Irin"),
                "Bois" to listOf("Eyota", "Kachine"),
                "Boucles" to listOf("Yana ?"),
                "Graines" to listOf("Sarina"),
            ),
            "GOOD" to mapOf(
                "Sève" to listOf("Enola", "Visc agro KKT"),
                "Ambres" to listOf("Beng"),
                "Carapace" to listOf("Mignonne"),
                "Boucles" to listOf("Yana ?"),
                "Résine" to listOf("Fung"),
                "Huile" to listOf("Pilan"),
            ),
            "BEST" to mapOf(
                "Ambres" to listOf("Sha", "Hash", "Zun", "Soo"),
                "Sève" to listOf("Silverweed", "Ardente"),
                "Écorce" to listOf("Perfling", "Oath"),
                "Bois" to listOf("Motega"),
            ),
        ),
        "Profondeurs Interdites" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Beng", "Pha"),
                "Graines" to listOf("Sarina", "Silvio"),
                "Fibres" to listOf("Anète", "Buo"),
                "Résine" to listOf("Dung", "Lune"),
                "Huile" to listOf("Gulatch", "Irin", "Koorin"),
                "Sève" to listOf("Dante", "Silverweed"),
                "Carapace" to listOf("Mignonne", "Cornée", "Inteligente"),
                "Écorce" to listOf("Adriel", "Mitexi", "Perfling"),
                "Bois" to listOf("Tama"),
                "Boucles" to listOf("Nita", "Patee", "Scratch", "Tansy"),
            ),
            "BAD" to mapOf(
                "Sève" to listOf("Ardente ?", "Enola"),
                "Huile" to listOf("Pilan"),
                "Carapace" to listOf("Grosse"),
                "Ambres" to listOf("Hash"),
                "Écorce" to listOf("Oath"),
                "Bois" to listOf("Kachine"),
            ),
            "GOOD" to mapOf(
                "Sève" to listOf("Ardente ?", "Visc"),
                "Bois" to listOf("Motega", "Abhaya"),
                "Ambres" to listOf("Soo"),
                "Carapace" to listOf("Splinter"),
                "Boucles" to listOf("Yana"),
                "Résine" to listOf("Fung", "Colle"),
            ),
            "BEST" to mapOf(
                "Ambres" to listOf("Zun", "Sha"),
                "Graines" to listOf("Caprice", "Saurona"),
                "Sève" to listOf("Ardente ?"),
                "Écorce" to listOf("Beckers"),
                "Bois" to listOf("Eyota"),
                "Fibres" to listOf("Dzao", "Shu"),
            ),
        ),
    ),
    "HIVER" to mapOf(
        "Sources Interdites" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Beng", "Pha", "Sha", "Zun"),
                "Graines" to listOf("Caprice", "Silvio"),
                "Fibres" to listOf("Anète", "Buo"),
                "Résine" to listOf("Dung", "Colle", "Lune"),
                "Huile" to listOf("Gulatch", "Irin", "Pilan"),
                "Sève" to listOf("Dante", "Redhot", "Silverweed"),
                "Carapace" to listOf("Mignonne", "Inteligente"),
                "Écorce" to listOf("Beckers", "Oath", "Perfling"),
                "Bois" to listOf("Eyota", "Kachine", "Tama"),
                "Boucles" to listOf("Nita", "Patee", "Scratch", "Yana"),
            ),
            "BAD" to mapOf(
                "Ambres" to listOf("Soo", "Hash"),
                "Écorce" to listOf("Adriel"),
                "Boucles" to listOf("Tansy"),
            ),
            "GOOD" to mapOf(
                "Fibres" to listOf("Dzao"),
                "Huile" to listOf("Koorin", "Enola"),
                "Sève" to listOf("Visc"),
                "Graines" to listOf("Saurona", "Sarina"),
                "Carapace" to listOf("Splinter", "Cornée"),
                "Résine" to listOf("Fung"),
                "Bois" to listOf("Motega"),
            ),
            "BEST" to mapOf(
                "Fibres" to listOf("Shu"),
                "Écorce" to listOf("Mitexi"),
                "Carapace" to listOf("Grosse"),
                "Bois" to listOf("Abhaya"),
            ),
        ),
        "Terre de la Continuité" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Hash", "Pha", "Sha", "Zun"),
                "Graines" to listOf("Caprice", "Sarina", "Silvio"),
                "Fibres" to listOf("Shu"),
                "Résine" to listOf("Colle", "Lune"),
                "Huile" to listOf("Irin", "Koorin", "Pilan"),
                "Sève" to listOf("Dante", "Enola"),
                "Carapace" to listOf("Grosse", "Cornée", "Inteligente", "Splinter"),
                "Écorce" to listOf("Adriel", "Beckers"),
                "Bois" to listOf("Motega"),
                "Boucles" to listOf("Nita", "Patee", "Scratch"),
            ),
            "BAD" to mapOf(
                "Carapace" to listOf("Mignonne"),
                "Écorce" to listOf("Perfling"),
                "Bois" to listOf("Eyota"),
            ),
            "GOOD" to mapOf(
                "Ambres" to listOf("Soo"),
                "Bois" to listOf("Tama", "Abhaya"),
                "Boucles" to listOf("Tansy", "Yana"),
                "Résine" to listOf("Fung"),
                "Huile" to listOf("Gulatch"),
                "Sève" to listOf("Ardente", "Silverweed"),
            ),
            "BEST" to mapOf(
                "Ambres" to listOf("Beng"),
                "Fibres" to listOf("Buo", "Dzao", "Anète"),
                "Résine" to listOf("Dung"),
                "Sève" to listOf("Visc"),
                "Bois" to listOf("Kachine"),
                "Boucles" to listOf("Scratch"),
                "Écorce" to listOf("Oath"),
                "Graines" to listOf("Saurona"),
            ),
        ),
        "Cité Engloutie" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Pha"),
                "Graines" to listOf("Caprice", "Saurona", "Silvio"),
                "Fibres" to listOf("Anète", "Buo", "Dzao", "Shu"),
                "Résine" to listOf("Dung", "Colle", "Lune"),
                "Huile" to listOf("Gulatch", "Koorin"),
                "Sève" to listOf("Dante"),
                "Carapace" to listOf("Grosse", "Cornée", "Inteligente", "Splinter"),
                "Écorce" to listOf("Adriel", "Beckers", "Mitexi"),
                "Bois" to listOf("Abhaya", "Tama"),
                "Boucles" to listOf("Nita", "Patee", "Scratch", "Tansy"),
            ),
            "BAD" to mapOf(
                "Huile" to listOf("Irin"),
                "Bois" to listOf("Eyota", "Kachine"),
                "Boucles" to listOf("Yana ?"),
                "Graines" to listOf("Sarina"),
            ),
            "GOOD" to mapOf(
                "Ambres" to listOf("Beng"),
                "Sève" to listOf("Visc agro KKT", "Enola"),
                "Carapace" to listOf("Mignonne"),
                "Boucles" to listOf("Yana ?"),
                "Résine" to listOf("Fung"),
                "Huile" to listOf("Pilan"),
            ),
            "BEST" to mapOf(
                "Ambres" to listOf("Hash", "Sha", "Zun", "Soo"),
                "Écorce" to listOf("Perfling", "Oath"),
                "Sève" to listOf("Ardente", "Silverweed"),
                "Bois" to listOf("Motega"),
            ),
        ),
        "Profondeurs Interdites" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Beng", "Pha"),
                "Graines" to listOf("Sarina", "Silvio"),
                "Fibres" to listOf("Anète", "Buo"),
                "Résine" to listOf("Dung", "Lune"),
                "Huile" to listOf("Gulatch", "Irin", "Koorin"),
                "Sève" to listOf("Dante", "Silverweed"),
                "Carapace" to listOf("Mignonne", "Cornée", "Inteligente"),
                "Écorce" to listOf("Adriel", "Mitexi", "Perfling"),
                "Bois" to listOf("Tama"),
                "Boucles" to listOf("Nita", "Patee", "Scratch", "Tansy"),
            ),
            "BAD" to mapOf(
                "Huile" to listOf("Pilan"),
                "Carapace" to listOf("Grosse"),
                "Ambres" to listOf("Hash"),
                "Sève" to listOf("Enola", "Ardente ?"),
                "Écorce" to listOf("Oath"),
                "Bois" to listOf("Kachine"),
            ),
            "GOOD" to mapOf(
                "Ambres" to listOf("Soo"),
                "Bois" to listOf("Abhaya", "Motega"),
                "Carapace" to listOf("Splinter"),
                "Boucles" to listOf("Yana"),
                "Résine" to listOf("Fung", "Colle"),
                "Sève" to listOf("Ardente ?", "Visc"),
            ),
            "BEST" to mapOf(
                "Graines" to listOf("Caprice", "Saurona"),
                "Fibres" to listOf("Dzao", "Shu"),
                "Ambres" to listOf("Sha", "Zun"),
                "Écorce" to listOf("Beckers"),
                "Bois" to listOf("Eyota"),
                "Sève" to listOf("Ardente ?"),
            ),
        ),
    ),
)

/** Zone du relevé -> continent interrogé pour la météo. */
val CONTINENT_DE_ZONE: Map<String, String> = mapOf(
    "Sources Interdites" to "sources",
    "Terre de la Continuité" to "terre",
    "Cité Engloutie" to "terre",
    "Profondeurs Interdites" to "terre",
)
