package net.ryzom.zyroom.model

// Fichier produit par outils/table_pop.py — ne pas modifier à la main.

/**
 * Ce qui peut apparaître, par saison, par zone et par condition météo.
 *
 * Deux sources : le relevé de Ryzom Armory pour le couple saison × zone, et
 * la fourchette d'humidité de chaque gisement, relevée au tracker d'atys.us,
 * pour la condition. Le jeu range l'humidité en quatre bandes et chaque
 * gisement en occupe exactement deux — sec vaut mieux qu'humide.
 *
 * La table est donc **complète** : chaque matière de chaque zone y figure
 * sous ses deux conditions. Le classeur de la guilde, qu'elle remplace,
 * était rempli de mémoire et ne s'accordait avec le jeu que sur une matière
 * sur quarante-six.
 */
val POP: Map<String, Map<String, Map<String, Map<String, List<String>>>>> = mapOf(
    "PRINTEMPS" to mapOf(
        "Sources Interdites" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Pha", "Zun"),
                "Graines" to listOf("Sarina", "Silvio"),
                "Fibres" to listOf("Buo"),
                "Résine" to listOf("Lune"),
                "Huile" to listOf("Irin", "Pilan"),
                "Sève" to listOf("Dante"),
                "Carapace" to listOf("Grosse", "Splinter"),
                "Écorce" to listOf("Oath", "Perfling"),
                "Bois" to listOf("Kachine"),
                "Boucles" to listOf("Nita"),
            ),
            "BAD" to mapOf(
                "Ambres" to listOf("Beng", "Soo", "Zun"),
                "Graines" to listOf("Caprice", "Saurona"),
                "Fibres" to listOf("Anète", "Buo"),
                "Résine" to listOf("Colle"),
                "Huile" to listOf("Gulatch", "Pilan"),
                "Sève" to listOf("Ardente", "Dante", "Silverweed"),
                "Carapace" to listOf("Inteligente", "Mignonne"),
                "Écorce" to listOf("Beckers"),
                "Bois" to listOf("Tama"),
                "Boucles" to listOf("Scratch", "Yana"),
            ),
            "GOOD" to mapOf(
                "Ambres" to listOf("Beng", "Pha", "Sha"),
                "Graines" to listOf("Saurona", "Silvio"),
                "Résine" to listOf("Colle", "Dung", "Lune"),
                "Huile" to listOf("Irin"),
                "Sève" to listOf("Ardente"),
                "Carapace" to listOf("Mignonne", "Splinter"),
                "Écorce" to listOf("Beckers", "Oath"),
                "Bois" to listOf("Eyota"),
                "Boucles" to listOf("Patee", "Scratch"),
            ),
            "BEST" to mapOf(
                "Ambres" to listOf("Sha", "Soo"),
                "Graines" to listOf("Caprice", "Sarina"),
                "Fibres" to listOf("Anète"),
                "Résine" to listOf("Dung"),
                "Huile" to listOf("Gulatch"),
                "Sève" to listOf("Silverweed"),
                "Carapace" to listOf("Grosse", "Inteligente"),
                "Écorce" to listOf("Perfling"),
                "Bois" to listOf("Eyota", "Kachine", "Tama"),
                "Boucles" to listOf("Nita", "Patee", "Yana"),
            ),
        ),
        "Terre de la Continuité" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Hash", "Pha", "Zun"),
                "Graines" to listOf("Sarina", "Silvio"),
                "Fibres" to listOf("Buo"),
                "Résine" to listOf("Lune"),
                "Huile" to listOf("Irin", "Pilan"),
                "Sève" to listOf("Dante", "Visc"),
                "Carapace" to listOf("Grosse", "Splinter"),
                "Écorce" to listOf("Perfling"),
                "Bois" to listOf("Motega"),
                "Boucles" to listOf("Nita", "Tansy"),
            ),
            "BAD" to mapOf(
                "Ambres" to listOf("Zun"),
                "Graines" to listOf("Caprice"),
                "Fibres" to listOf("Anète", "Buo"),
                "Résine" to listOf("Colle"),
                "Huile" to listOf("Koorin", "Pilan"),
                "Sève" to listOf("Dante"),
                "Carapace" to listOf("Inteligente"),
                "Écorce" to listOf("Beckers"),
                "Bois" to listOf("Motega"),
                "Boucles" to listOf("Tansy", "Yana"),
            ),
            "GOOD" to mapOf(
                "Ambres" to listOf("Pha", "Sha"),
                "Graines" to listOf("Silvio"),
                "Fibres" to listOf("Shu"),
                "Résine" to listOf("Colle", "Lune"),
                "Huile" to listOf("Irin", "Koorin"),
                "Sève" to listOf("Enola", "Visc"),
                "Carapace" to listOf("Cornée", "Splinter"),
                "Écorce" to listOf("Adriel", "Beckers"),
                "Boucles" to listOf("Patee"),
            ),
            "BEST" to mapOf(
                "Ambres" to listOf("Hash", "Sha"),
                "Graines" to listOf("Caprice", "Sarina"),
                "Fibres" to listOf("Anète", "Shu"),
                "Sève" to listOf("Enola"),
                "Carapace" to listOf("Cornée", "Grosse", "Inteligente"),
                "Écorce" to listOf("Adriel", "Perfling"),
                "Boucles" to listOf("Nita", "Patee", "Yana"),
            ),
        ),
        "Cité Engloutie" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Pha"),
                "Graines" to listOf("Silvio"),
                "Fibres" to listOf("Buo", "Dzao"),
                "Résine" to listOf("Lune"),
                "Sève" to listOf("Dante"),
                "Carapace" to listOf("Grosse", "Splinter"),
                "Écorce" to listOf("Mitexi", "Oath"),
                "Bois" to listOf("Abhaya", "Motega"),
                "Boucles" to listOf("Nita", "Tansy"),
            ),
            "BAD" to mapOf(
                "Ambres" to listOf("Soo"),
                "Graines" to listOf("Caprice", "Saurona"),
                "Fibres" to listOf("Anète", "Buo"),
                "Huile" to listOf("Gulatch", "Koorin"),
                "Sève" to listOf("Ardente", "Dante"),
                "Carapace" to listOf("Inteligente", "Mignonne"),
                "Écorce" to listOf("Beckers", "Mitexi"),
                "Bois" to listOf("Motega"),
                "Boucles" to listOf("Scratch", "Tansy", "Yana"),
            ),
            "GOOD" to mapOf(
                "Ambres" to listOf("Pha"),
                "Graines" to listOf("Saurona", "Silvio"),
                "Fibres" to listOf("Shu"),
                "Résine" to listOf("Dung", "Lune"),
                "Huile" to listOf("Koorin"),
                "Sève" to listOf("Ardente"),
                "Carapace" to listOf("Cornée", "Mignonne", "Splinter"),
                "Écorce" to listOf("Adriel", "Beckers", "Oath"),
                "Bois" to listOf("Abhaya", "Eyota"),
                "Boucles" to listOf("Patee", "Scratch"),
            ),
            "BEST" to mapOf(
                "Ambres" to listOf("Soo"),
                "Graines" to listOf("Caprice"),
                "Fibres" to listOf("Anète", "Dzao", "Shu"),
                "Résine" to listOf("Dung"),
                "Huile" to listOf("Gulatch"),
                "Carapace" to listOf("Cornée", "Grosse", "Inteligente"),
                "Écorce" to listOf("Adriel"),
                "Bois" to listOf("Eyota"),
                "Boucles" to listOf("Nita", "Patee", "Yana"),
            ),
        ),
        "Profondeurs Interdites" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Hash", "Pha", "Zun"),
                "Graines" to listOf("Sarina", "Silvio"),
                "Fibres" to listOf("Buo", "Dzao"),
                "Résine" to listOf("Lune"),
                "Huile" to listOf("Irin"),
                "Sève" to listOf("Dante"),
                "Carapace" to listOf("Splinter"),
                "Écorce" to listOf("Mitexi", "Perfling"),
                "Bois" to listOf("Abhaya", "Motega"),
                "Boucles" to listOf("Nita", "Tansy"),
            ),
            "BAD" to mapOf(
                "Ambres" to listOf("Beng", "Zun"),
                "Fibres" to listOf("Anète", "Buo"),
                "Huile" to listOf("Gulatch", "Koorin"),
                "Sève" to listOf("Dante", "Silverweed"),
                "Carapace" to listOf("Inteligente", "Mignonne"),
                "Écorce" to listOf("Beckers", "Mitexi"),
                "Bois" to listOf("Motega"),
                "Boucles" to listOf("Scratch", "Tansy", "Yana"),
            ),
            "GOOD" to mapOf(
                "Ambres" to listOf("Beng", "Pha"),
                "Graines" to listOf("Silvio"),
                "Fibres" to listOf("Shu"),
                "Résine" to listOf("Dung", "Lune"),
                "Huile" to listOf("Irin", "Koorin"),
                "Sève" to listOf("Enola"),
                "Carapace" to listOf("Cornée", "Mignonne", "Splinter"),
                "Écorce" to listOf("Adriel", "Beckers"),
                "Bois" to listOf("Abhaya", "Eyota"),
                "Boucles" to listOf("Patee", "Scratch"),
            ),
            "BEST" to mapOf(
                "Ambres" to listOf("Hash"),
                "Graines" to listOf("Sarina"),
                "Fibres" to listOf("Anète", "Dzao", "Shu"),
                "Résine" to listOf("Dung"),
                "Huile" to listOf("Gulatch"),
                "Sève" to listOf("Enola", "Silverweed"),
                "Carapace" to listOf("Cornée", "Inteligente"),
                "Écorce" to listOf("Adriel", "Perfling"),
                "Bois" to listOf("Eyota"),
                "Boucles" to listOf("Nita", "Patee", "Yana"),
            ),
        ),
    ),
    "ETE" to mapOf(
        "Sources Interdites" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Hash", "Pha", "Zun"),
                "Graines" to listOf("Sarina", "Silvio"),
                "Fibres" to listOf("Buo"),
                "Résine" to listOf("Lune"),
                "Huile" to listOf("Irin", "Pilan"),
                "Sève" to listOf("Dante"),
                "Écorce" to listOf("Oath", "Perfling"),
                "Bois" to listOf("Abhaya", "Kachine"),
                "Boucles" to listOf("Nita"),
            ),
            "BAD" to mapOf(
                "Ambres" to listOf("Beng", "Zun"),
                "Graines" to listOf("Caprice"),
                "Fibres" to listOf("Anète", "Buo"),
                "Résine" to listOf("Colle"),
                "Huile" to listOf("Gulatch", "Pilan"),
                "Sève" to listOf("Ardente", "Dante", "Silverweed"),
                "Carapace" to listOf("Inteligente", "Mignonne"),
                "Écorce" to listOf("Beckers"),
                "Bois" to listOf("Tama"),
                "Boucles" to listOf("Scratch", "Yana"),
            ),
            "GOOD" to mapOf(
                "Ambres" to listOf("Beng", "Pha", "Sha"),
                "Graines" to listOf("Silvio"),
                "Fibres" to listOf("Shu"),
                "Résine" to listOf("Colle", "Dung", "Lune"),
                "Huile" to listOf("Irin"),
                "Sève" to listOf("Ardente"),
                "Carapace" to listOf("Cornée", "Mignonne"),
                "Écorce" to listOf("Adriel", "Beckers", "Oath"),
                "Bois" to listOf("Abhaya", "Eyota"),
                "Boucles" to listOf("Patee", "Scratch"),
            ),
            "BEST" to mapOf(
                "Ambres" to listOf("Hash", "Sha"),
                "Graines" to listOf("Caprice", "Sarina"),
                "Fibres" to listOf("Anète", "Shu"),
                "Résine" to listOf("Dung"),
                "Huile" to listOf("Gulatch"),
                "Sève" to listOf("Silverweed"),
                "Carapace" to listOf("Cornée", "Inteligente"),
                "Écorce" to listOf("Adriel", "Perfling"),
                "Bois" to listOf("Eyota", "Kachine", "Tama"),
                "Boucles" to listOf("Nita", "Patee", "Yana"),
            ),
        ),
        "Terre de la Continuité" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Hash", "Pha", "Zun"),
                "Graines" to listOf("Sarina", "Silvio"),
                "Résine" to listOf("Fung", "Lune"),
                "Huile" to listOf("Irin", "Pilan"),
                "Sève" to listOf("Dante"),
                "Carapace" to listOf("Grosse", "Splinter"),
                "Écorce" to listOf("Mitexi", "Oath"),
                "Bois" to listOf("Kachine", "Motega"),
                "Boucles" to listOf("Nita"),
            ),
            "BAD" to mapOf(
                "Ambres" to listOf("Zun"),
                "Graines" to listOf("Caprice", "Saurona"),
                "Fibres" to listOf("Anète"),
                "Résine" to listOf("Colle", "Fung"),
                "Huile" to listOf("Gulatch", "Koorin", "Pilan"),
                "Sève" to listOf("Dante"),
                "Carapace" to listOf("Inteligente"),
                "Écorce" to listOf("Beckers", "Mitexi"),
                "Bois" to listOf("Motega"),
                "Boucles" to listOf("Scratch"),
            ),
            "GOOD" to mapOf(
                "Ambres" to listOf("Pha", "Sha"),
                "Graines" to listOf("Saurona", "Silvio"),
                "Fibres" to listOf("Shu"),
                "Résine" to listOf("Colle", "Lune"),
                "Huile" to listOf("Irin", "Koorin"),
                "Sève" to listOf("Enola"),
                "Carapace" to listOf("Cornée", "Splinter"),
                "Écorce" to listOf("Adriel", "Beckers", "Oath"),
                "Boucles" to listOf("Patee", "Scratch"),
            ),
            "BEST" to mapOf(
                "Ambres" to listOf("Hash", "Sha"),
                "Graines" to listOf("Caprice", "Sarina"),
                "Fibres" to listOf("Anète", "Shu"),
                "Huile" to listOf("Gulatch"),
                "Sève" to listOf("Enola"),
                "Carapace" to listOf("Cornée", "Grosse", "Inteligente"),
                "Écorce" to listOf("Adriel"),
                "Bois" to listOf("Kachine"),
                "Boucles" to listOf("Nita", "Patee"),
            ),
        ),
        "Cité Engloutie" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Hash", "Pha", "Zun"),
                "Graines" to listOf("Sarina", "Silvio"),
                "Fibres" to listOf("Buo", "Dzao"),
                "Résine" to listOf("Fung", "Lune"),
                "Huile" to listOf("Pilan"),
                "Sève" to listOf("Dante"),
                "Carapace" to listOf("Grosse", "Splinter"),
                "Écorce" to listOf("Mitexi", "Oath"),
                "Bois" to listOf("Abhaya", "Kachine", "Motega"),
                "Boucles" to listOf("Nita", "Tansy"),
            ),
            "BAD" to mapOf(
                "Ambres" to listOf("Soo", "Zun"),
                "Graines" to listOf("Caprice", "Saurona"),
                "Fibres" to listOf("Anète", "Buo"),
                "Résine" to listOf("Colle", "Fung"),
                "Huile" to listOf("Gulatch", "Koorin", "Pilan"),
                "Sève" to listOf("Ardente", "Dante", "Silverweed"),
                "Carapace" to listOf("Inteligente"),
                "Écorce" to listOf("Beckers", "Mitexi"),
                "Bois" to listOf("Motega", "Tama"),
                "Boucles" to listOf("Scratch", "Tansy"),
            ),
            "GOOD" to mapOf(
                "Ambres" to listOf("Pha"),
                "Graines" to listOf("Saurona", "Silvio"),
                "Fibres" to listOf("Shu"),
                "Résine" to listOf("Colle", "Dung", "Lune"),
                "Huile" to listOf("Koorin"),
                "Sève" to listOf("Ardente"),
                "Carapace" to listOf("Cornée", "Splinter"),
                "Écorce" to listOf("Adriel", "Beckers", "Oath"),
                "Bois" to listOf("Abhaya"),
                "Boucles" to listOf("Patee", "Scratch"),
            ),
            "BEST" to mapOf(
                "Ambres" to listOf("Hash", "Soo"),
                "Graines" to listOf("Caprice", "Sarina"),
                "Fibres" to listOf("Anète", "Dzao", "Shu"),
                "Résine" to listOf("Dung"),
                "Huile" to listOf("Gulatch"),
                "Sève" to listOf("Silverweed"),
                "Carapace" to listOf("Cornée", "Grosse", "Inteligente"),
                "Écorce" to listOf("Adriel"),
                "Bois" to listOf("Kachine", "Tama"),
                "Boucles" to listOf("Nita", "Patee"),
            ),
        ),
        "Profondeurs Interdites" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Pha"),
                "Graines" to listOf("Sarina", "Silvio"),
                "Fibres" to listOf("Buo"),
                "Résine" to listOf("Fung", "Lune"),
                "Huile" to listOf("Irin"),
                "Sève" to listOf("Dante"),
                "Écorce" to listOf("Mitexi", "Oath", "Perfling"),
                "Bois" to listOf("Kachine"),
                "Boucles" to listOf("Nita", "Tansy"),
            ),
            "BAD" to mapOf(
                "Ambres" to listOf("Beng"),
                "Graines" to listOf("Saurona"),
                "Fibres" to listOf("Anète", "Buo"),
                "Résine" to listOf("Colle", "Fung"),
                "Huile" to listOf("Gulatch", "Koorin"),
                "Sève" to listOf("Dante", "Silverweed"),
                "Carapace" to listOf("Inteligente", "Mignonne"),
                "Écorce" to listOf("Mitexi"),
                "Bois" to listOf("Tama"),
                "Boucles" to listOf("Scratch", "Tansy"),
            ),
            "GOOD" to mapOf(
                "Ambres" to listOf("Beng", "Pha", "Sha"),
                "Graines" to listOf("Saurona", "Silvio"),
                "Fibres" to listOf("Shu"),
                "Résine" to listOf("Colle", "Dung", "Lune"),
                "Huile" to listOf("Irin", "Koorin"),
                "Carapace" to listOf("Cornée", "Mignonne"),
                "Écorce" to listOf("Adriel", "Oath"),
                "Bois" to listOf("Eyota"),
                "Boucles" to listOf("Patee", "Scratch"),
            ),
            "BEST" to mapOf(
                "Ambres" to listOf("Sha"),
                "Graines" to listOf("Sarina"),
                "Fibres" to listOf("Anète", "Shu"),
                "Résine" to listOf("Dung"),
                "Huile" to listOf("Gulatch"),
                "Sève" to listOf("Silverweed"),
                "Carapace" to listOf("Cornée", "Inteligente"),
                "Écorce" to listOf("Adriel", "Perfling"),
                "Bois" to listOf("Eyota", "Kachine", "Tama"),
                "Boucles" to listOf("Nita", "Patee"),
            ),
        ),
    ),
    "AUTOMNE" to mapOf(
        "Sources Interdites" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Pha", "Zun"),
                "Graines" to listOf("Silvio"),
                "Fibres" to listOf("Buo"),
                "Résine" to listOf("Fung", "Lune"),
                "Huile" to listOf("Irin", "Pilan"),
                "Sève" to listOf("Dante"),
                "Carapace" to listOf("Grosse"),
                "Écorce" to listOf("Mitexi", "Oath", "Perfling"),
                "Bois" to listOf("Abhaya", "Kachine", "Motega"),
                "Boucles" to listOf("Nita", "Tansy"),
            ),
            "BAD" to mapOf(
                "Ambres" to listOf("Beng", "Zun"),
                "Graines" to listOf("Caprice"),
                "Fibres" to listOf("Anète", "Buo"),
                "Résine" to listOf("Colle", "Fung"),
                "Huile" to listOf("Gulatch", "Pilan"),
                "Sève" to listOf("Ardente", "Dante", "Silverweed"),
                "Carapace" to listOf("Inteligente", "Mignonne"),
                "Écorce" to listOf("Beckers", "Mitexi"),
                "Bois" to listOf("Motega", "Tama"),
                "Boucles" to listOf("Scratch", "Tansy", "Yana"),
            ),
            "GOOD" to mapOf(
                "Ambres" to listOf("Beng", "Pha", "Sha"),
                "Graines" to listOf("Silvio"),
                "Résine" to listOf("Colle", "Dung", "Lune"),
                "Huile" to listOf("Irin"),
                "Sève" to listOf("Ardente", "Enola"),
                "Carapace" to listOf("Mignonne"),
                "Écorce" to listOf("Beckers", "Oath"),
                "Bois" to listOf("Abhaya", "Eyota"),
                "Boucles" to listOf("Patee", "Scratch"),
            ),
            "BEST" to mapOf(
                "Ambres" to listOf("Sha"),
                "Graines" to listOf("Caprice"),
                "Fibres" to listOf("Anète"),
                "Résine" to listOf("Dung"),
                "Huile" to listOf("Gulatch"),
                "Sève" to listOf("Enola", "Silverweed"),
                "Carapace" to listOf("Grosse", "Inteligente"),
                "Écorce" to listOf("Perfling"),
                "Bois" to listOf("Eyota", "Kachine", "Tama"),
                "Boucles" to listOf("Nita", "Patee", "Yana"),
            ),
        ),
        "Terre de la Continuité" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Hash", "Pha", "Zun"),
                "Graines" to listOf("Sarina", "Silvio"),
                "Fibres" to listOf("Buo", "Dzao"),
                "Résine" to listOf("Lune"),
                "Huile" to listOf("Irin", "Pilan"),
                "Sève" to listOf("Dante"),
                "Carapace" to listOf("Grosse", "Splinter"),
                "Bois" to listOf("Abhaya", "Motega"),
                "Boucles" to listOf("Nita"),
            ),
            "BAD" to mapOf(
                "Ambres" to listOf("Beng", "Zun"),
                "Graines" to listOf("Caprice", "Saurona"),
                "Fibres" to listOf("Buo"),
                "Résine" to listOf("Colle"),
                "Huile" to listOf("Koorin", "Pilan"),
                "Sève" to listOf("Ardente", "Dante", "Silverweed"),
                "Carapace" to listOf("Inteligente"),
                "Écorce" to listOf("Beckers"),
                "Bois" to listOf("Motega"),
            ),
            "GOOD" to mapOf(
                "Ambres" to listOf("Beng", "Pha", "Sha"),
                "Graines" to listOf("Saurona", "Silvio"),
                "Fibres" to listOf("Shu"),
                "Résine" to listOf("Colle", "Lune"),
                "Huile" to listOf("Irin", "Koorin"),
                "Sève" to listOf("Ardente", "Enola"),
                "Carapace" to listOf("Cornée", "Splinter"),
                "Écorce" to listOf("Adriel", "Beckers"),
                "Bois" to listOf("Abhaya"),
                "Boucles" to listOf("Patee"),
            ),
            "BEST" to mapOf(
                "Ambres" to listOf("Hash", "Sha"),
                "Graines" to listOf("Caprice", "Sarina"),
                "Fibres" to listOf("Dzao", "Shu"),
                "Sève" to listOf("Enola", "Silverweed"),
                "Carapace" to listOf("Cornée", "Grosse", "Inteligente"),
                "Écorce" to listOf("Adriel"),
                "Boucles" to listOf("Nita", "Patee"),
            ),
        ),
        "Cité Engloutie" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Pha"),
                "Graines" to listOf("Silvio"),
                "Fibres" to listOf("Buo", "Dzao"),
                "Résine" to listOf("Lune"),
                "Sève" to listOf("Dante"),
                "Carapace" to listOf("Grosse", "Splinter"),
                "Écorce" to listOf("Mitexi", "Perfling"),
                "Bois" to listOf("Abhaya", "Motega"),
                "Boucles" to listOf("Nita", "Tansy"),
            ),
            "BAD" to mapOf(
                "Graines" to listOf("Caprice", "Saurona"),
                "Fibres" to listOf("Anète", "Buo"),
                "Résine" to listOf("Colle"),
                "Huile" to listOf("Gulatch", "Koorin"),
                "Sève" to listOf("Dante", "Silverweed"),
                "Carapace" to listOf("Inteligente"),
                "Écorce" to listOf("Mitexi"),
                "Bois" to listOf("Motega", "Tama"),
                "Boucles" to listOf("Scratch", "Tansy"),
            ),
            "GOOD" to mapOf(
                "Ambres" to listOf("Pha", "Sha"),
                "Graines" to listOf("Saurona", "Silvio"),
                "Fibres" to listOf("Shu"),
                "Résine" to listOf("Colle", "Dung", "Lune"),
                "Huile" to listOf("Koorin"),
                "Sève" to listOf("Enola"),
                "Carapace" to listOf("Cornée", "Splinter"),
                "Écorce" to listOf("Adriel"),
                "Bois" to listOf("Abhaya"),
                "Boucles" to listOf("Patee", "Scratch"),
            ),
            "BEST" to mapOf(
                "Ambres" to listOf("Sha"),
                "Graines" to listOf("Caprice"),
                "Fibres" to listOf("Anète", "Dzao", "Shu"),
                "Résine" to listOf("Dung"),
                "Huile" to listOf("Gulatch"),
                "Sève" to listOf("Enola", "Silverweed"),
                "Carapace" to listOf("Cornée", "Grosse", "Inteligente"),
                "Écorce" to listOf("Adriel", "Perfling"),
                "Bois" to listOf("Tama"),
                "Boucles" to listOf("Nita", "Patee"),
            ),
        ),
        "Profondeurs Interdites" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Pha", "Zun"),
                "Graines" to listOf("Sarina", "Silvio"),
                "Fibres" to listOf("Buo"),
                "Résine" to listOf("Fung", "Lune"),
                "Huile" to listOf("Irin"),
                "Sève" to listOf("Dante", "Visc"),
                "Écorce" to listOf("Mitexi", "Perfling"),
                "Bois" to listOf("Motega"),
                "Boucles" to listOf("Nita", "Tansy"),
            ),
            "BAD" to mapOf(
                "Ambres" to listOf("Beng", "Zun"),
                "Graines" to listOf("Caprice"),
                "Fibres" to listOf("Anète", "Buo"),
                "Résine" to listOf("Fung"),
                "Huile" to listOf("Gulatch", "Koorin"),
                "Sève" to listOf("Ardente", "Dante", "Silverweed"),
                "Carapace" to listOf("Inteligente", "Mignonne"),
                "Écorce" to listOf("Beckers", "Mitexi"),
                "Bois" to listOf("Motega", "Tama"),
                "Boucles" to listOf("Scratch", "Tansy"),
            ),
            "GOOD" to mapOf(
                "Ambres" to listOf("Beng", "Pha"),
                "Graines" to listOf("Silvio"),
                "Résine" to listOf("Dung", "Lune"),
                "Huile" to listOf("Irin", "Koorin"),
                "Sève" to listOf("Ardente", "Visc"),
                "Carapace" to listOf("Cornée", "Mignonne"),
                "Écorce" to listOf("Adriel", "Beckers"),
                "Bois" to listOf("Eyota"),
                "Boucles" to listOf("Patee", "Scratch"),
            ),
            "BEST" to mapOf(
                "Graines" to listOf("Caprice", "Sarina"),
                "Fibres" to listOf("Anète"),
                "Résine" to listOf("Dung"),
                "Huile" to listOf("Gulatch"),
                "Sève" to listOf("Silverweed"),
                "Carapace" to listOf("Cornée", "Inteligente"),
                "Écorce" to listOf("Adriel", "Perfling"),
                "Bois" to listOf("Eyota", "Tama"),
                "Boucles" to listOf("Nita", "Patee"),
            ),
        ),
    ),
    "HIVER" to mapOf(
        "Sources Interdites" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Pha", "Zun"),
                "Graines" to listOf("Silvio"),
                "Fibres" to listOf("Buo", "Dzao"),
                "Résine" to listOf("Lune"),
                "Huile" to listOf("Irin", "Pilan"),
                "Sève" to listOf("Dante", "Visc"),
                "Écorce" to listOf("Mitexi", "Oath", "Perfling"),
                "Bois" to listOf("Kachine"),
                "Boucles" to listOf("Nita"),
            ),
            "BAD" to mapOf(
                "Ambres" to listOf("Beng", "Zun"),
                "Graines" to listOf("Caprice"),
                "Fibres" to listOf("Anète", "Buo"),
                "Résine" to listOf("Colle"),
                "Huile" to listOf("Gulatch", "Koorin", "Pilan"),
                "Sève" to listOf("Ardente", "Dante", "Silverweed"),
                "Carapace" to listOf("Inteligente", "Mignonne"),
                "Écorce" to listOf("Beckers", "Mitexi"),
                "Bois" to listOf("Tama"),
                "Boucles" to listOf("Scratch", "Yana"),
            ),
            "GOOD" to mapOf(
                "Ambres" to listOf("Beng", "Pha", "Sha"),
                "Graines" to listOf("Silvio"),
                "Fibres" to listOf("Shu"),
                "Résine" to listOf("Colle", "Dung", "Lune"),
                "Huile" to listOf("Irin", "Koorin"),
                "Sève" to listOf("Ardente", "Visc"),
                "Carapace" to listOf("Mignonne"),
                "Écorce" to listOf("Beckers", "Oath"),
                "Bois" to listOf("Eyota"),
                "Boucles" to listOf("Patee", "Scratch"),
            ),
            "BEST" to mapOf(
                "Ambres" to listOf("Sha"),
                "Graines" to listOf("Caprice"),
                "Fibres" to listOf("Anète", "Dzao", "Shu"),
                "Résine" to listOf("Dung"),
                "Huile" to listOf("Gulatch"),
                "Sève" to listOf("Silverweed"),
                "Carapace" to listOf("Inteligente"),
                "Écorce" to listOf("Perfling"),
                "Bois" to listOf("Eyota", "Kachine", "Tama"),
                "Boucles" to listOf("Nita", "Patee", "Yana"),
            ),
        ),
        "Terre de la Continuité" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Hash", "Pha", "Zun"),
                "Graines" to listOf("Sarina", "Silvio"),
                "Fibres" to listOf("Buo", "Dzao"),
                "Résine" to listOf("Lune"),
                "Huile" to listOf("Irin", "Pilan"),
                "Sève" to listOf("Dante", "Visc"),
                "Carapace" to listOf("Grosse", "Splinter"),
                "Bois" to listOf("Kachine", "Motega"),
                "Boucles" to listOf("Nita"),
            ),
            "BAD" to mapOf(
                "Ambres" to listOf("Beng", "Soo", "Zun"),
                "Graines" to listOf("Caprice"),
                "Fibres" to listOf("Buo"),
                "Résine" to listOf("Colle"),
                "Huile" to listOf("Koorin", "Pilan"),
                "Sève" to listOf("Dante"),
                "Carapace" to listOf("Inteligente", "Mignonne"),
                "Écorce" to listOf("Beckers"),
                "Bois" to listOf("Motega", "Tama"),
                "Boucles" to listOf("Scratch"),
            ),
            "GOOD" to mapOf(
                "Ambres" to listOf("Beng", "Pha", "Sha"),
                "Graines" to listOf("Silvio"),
                "Fibres" to listOf("Shu"),
                "Résine" to listOf("Colle", "Dung", "Lune"),
                "Huile" to listOf("Irin", "Koorin"),
                "Sève" to listOf("Enola", "Visc"),
                "Carapace" to listOf("Cornée", "Mignonne", "Splinter"),
                "Écorce" to listOf("Adriel", "Beckers"),
                "Boucles" to listOf("Patee", "Scratch"),
            ),
            "BEST" to mapOf(
                "Ambres" to listOf("Hash", "Sha", "Soo"),
                "Graines" to listOf("Caprice", "Sarina"),
                "Fibres" to listOf("Dzao", "Shu"),
                "Résine" to listOf("Dung"),
                "Sève" to listOf("Enola"),
                "Carapace" to listOf("Cornée", "Grosse", "Inteligente"),
                "Écorce" to listOf("Adriel"),
                "Bois" to listOf("Kachine", "Tama"),
                "Boucles" to listOf("Nita", "Patee"),
            ),
        ),
        "Cité Engloutie" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Hash", "Pha", "Zun"),
                "Graines" to listOf("Silvio"),
                "Fibres" to listOf("Buo", "Dzao"),
                "Résine" to listOf("Lune"),
                "Huile" to listOf("Irin"),
                "Sève" to listOf("Dante", "Visc"),
                "Carapace" to listOf("Grosse", "Splinter"),
                "Écorce" to listOf("Mitexi", "Perfling"),
                "Bois" to listOf("Abhaya"),
                "Boucles" to listOf("Nita", "Tansy"),
            ),
            "BAD" to mapOf(
                "Ambres" to listOf("Beng", "Zun"),
                "Graines" to listOf("Caprice", "Saurona"),
                "Fibres" to listOf("Anète", "Buo"),
                "Résine" to listOf("Colle"),
                "Huile" to listOf("Gulatch", "Koorin"),
                "Sève" to listOf("Dante", "Silverweed"),
                "Carapace" to listOf("Inteligente"),
                "Écorce" to listOf("Mitexi"),
                "Bois" to listOf("Tama"),
                "Boucles" to listOf("Scratch", "Tansy"),
            ),
            "GOOD" to mapOf(
                "Ambres" to listOf("Beng", "Pha", "Sha"),
                "Graines" to listOf("Saurona", "Silvio"),
                "Fibres" to listOf("Shu"),
                "Résine" to listOf("Colle", "Dung", "Lune"),
                "Huile" to listOf("Irin", "Koorin"),
                "Sève" to listOf("Enola", "Visc"),
                "Carapace" to listOf("Cornée", "Splinter"),
                "Bois" to listOf("Abhaya"),
                "Boucles" to listOf("Patee", "Scratch"),
            ),
            "BEST" to mapOf(
                "Ambres" to listOf("Hash", "Sha"),
                "Graines" to listOf("Caprice"),
                "Fibres" to listOf("Anète", "Dzao", "Shu"),
                "Résine" to listOf("Dung"),
                "Huile" to listOf("Gulatch"),
                "Sève" to listOf("Enola", "Silverweed"),
                "Carapace" to listOf("Cornée", "Grosse", "Inteligente"),
                "Écorce" to listOf("Perfling"),
                "Bois" to listOf("Tama"),
                "Boucles" to listOf("Nita", "Patee"),
            ),
        ),
        "Profondeurs Interdites" to mapOf(
            "WORST" to mapOf(
                "Ambres" to listOf("Pha"),
                "Graines" to listOf("Sarina", "Silvio"),
                "Fibres" to listOf("Buo", "Dzao"),
                "Résine" to listOf("Lune"),
                "Huile" to listOf("Irin", "Pilan"),
                "Sève" to listOf("Dante"),
                "Carapace" to listOf("Grosse"),
                "Écorce" to listOf("Mitexi", "Perfling"),
                "Bois" to listOf("Abhaya"),
                "Boucles" to listOf("Nita", "Tansy"),
            ),
            "BAD" to mapOf(
                "Ambres" to listOf("Beng", "Soo"),
                "Graines" to listOf("Caprice", "Saurona"),
                "Fibres" to listOf("Anète", "Buo"),
                "Huile" to listOf("Gulatch", "Koorin", "Pilan"),
                "Sève" to listOf("Dante", "Silverweed"),
                "Carapace" to listOf("Inteligente", "Mignonne"),
                "Écorce" to listOf("Mitexi"),
                "Bois" to listOf("Tama"),
                "Boucles" to listOf("Scratch", "Tansy"),
            ),
            "GOOD" to mapOf(
                "Ambres" to listOf("Beng", "Pha"),
                "Graines" to listOf("Saurona", "Silvio"),
                "Résine" to listOf("Dung", "Lune"),
                "Huile" to listOf("Irin", "Koorin"),
                "Carapace" to listOf("Cornée", "Mignonne"),
                "Écorce" to listOf("Adriel"),
                "Bois" to listOf("Abhaya"),
                "Boucles" to listOf("Patee", "Scratch"),
            ),
            "BEST" to mapOf(
                "Ambres" to listOf("Soo"),
                "Graines" to listOf("Caprice", "Sarina"),
                "Fibres" to listOf("Anète", "Dzao"),
                "Résine" to listOf("Dung"),
                "Huile" to listOf("Gulatch"),
                "Sève" to listOf("Silverweed"),
                "Carapace" to listOf("Cornée", "Grosse", "Inteligente"),
                "Écorce" to listOf("Adriel", "Perfling"),
                "Bois" to listOf("Tama"),
                "Boucles" to listOf("Nita", "Patee"),
            ),
        ),
    ),
)

/** Zone du relevé -> continent interrogé pour la météo. */
val CONTINENT_DE_ZONE: Map<String, String> = mapOf(
    "Sources Interdites" to "sources",
    "Terre de la Continuité" to "terre",
    "Cité Engloutie" to "terre",
    "Profondeurs Interdites" to "terre",
)
